Luna: Examples/Arclength_Falkner.cpp File Reference
Arclength_Falkner.cpp File Reference
TODO description of the problem.
#include "Luna/Core"
#include "Luna/ODE"
Classes
class Luna::Example::test_equation
class Luna::Example::plate_BC
class Luna::Example::free_BC
Namespaces
Luna
Luna::Example
Enumerations
enum { f, fd, fdd }
Functions
double Luna::Example::KB (0.0)
int main ()
Detailed Description
TODO description of the problem.
Definition in file Arclength_Falkner.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
f
fd
fdd
Definition at line 9 of file Arclength_Falkner.cpp.
 { f, fd, fdd };
Function Documentation
main()
int main ()
Definition at line 67 of file Arclength_Falkner.cpp.
References Luna::ODE_BVP< T, X >::arclength_solve(), Luna::Example::test_equation::beta, Falkner_3D_alternative_plot::eta, f, fd, fdd, Luna::ODE_BVP< T, X >::init_arc(), Luna::Vector< T >::linspace(), Luna::ODE_BVP< T, X >::solution(), and Luna::ODE_BVP< T, X >::solve_bvp().
Referenced by Luna::Tridiagonal< T >::set_main(), and Luna::Tridiagonal< T >::Tridiagonal().
 {
   cout << "----- TESTING ODE_BVP (arc-length continuation) -----" << endl;
   /* ----- TESTING ODE_BVP class ----- */
     double Inf( 10.0 );                                   // Infinite boundary
     size_t N_nodes( 1000 );
     Vector<double> nodes;                       // Declare vector of nodes ( uniformly spaced )
     nodes.linspace(0,Inf,N_nodes);
   // Create instances of the equation and BCs
   Example::test_equation equation;
   Example::plate_BC left_BC;
   Example::free_BC right_BC;
     // Create boundary value problem
   ODE_BVP<double> ode( &equation, nodes, &left_BC, &right_BC );
     /* ----- Set the initial guess ----- */
     for (std::size_t j=0; j < N_nodes; ++j )
     {
         double eta = nodes[ j ];                    // eta value at node j
         ode.solution()( j , f )         = eta + exp( -eta );
     ode.solution()( j , fd )        = 1.0 - exp( -eta );
         ode.solution()( j , fdd )   = exp( -eta );
     }
   ode.solve_bvp();                        // Solve the system numerically
   ode.solution().output( "./DATA/Solution_mesh_test.dat" );
   // Output initial solution
   cout << "beta = 0" << ", U'(0) = " << ode.solution()( 0, fdd ) << endl;
   // Arc-length continuation
   // Instantiate the problem
   Example::test_equation arc_eqn;
   arc_eqn.beta = 0.0;
   // ODE boundary value problem
   ODE_BVP<double> ode_bvp_arc( &arc_eqn, nodes, &left_BC, &right_BC );
   // Initialise
   for (std::size_t j=0; j < N_nodes; ++j )
     {
         double eta = nodes[ j ];                    // eta value at node j
         ode_bvp_arc.solution()( j , f )         = eta + exp( -eta );
     ode_bvp_arc.solution()( j , fd )        = 1.0 - exp( -eta );
         ode_bvp_arc.solution()( j , fdd )   = exp( -eta );
     }
   ode_bvp_arc.init_arc( &arc_eqn.beta, 0.01, 0.1 );
   // Arc-length solve the system
   double arc_step( 0.01 );
   // Output initial solution
   cout << "beta = " << arc_eqn.beta << ", U'(0) = " << ode_bvp_arc.solution()( 0, fdd );
   cout << endl;
   do
   {
     arc_step = ode_bvp_arc.arclength_solve( arc_step );
     cout << "beta = " << arc_eqn.beta << ", U'(0) = " << ode_bvp_arc.solution()( 0, fdd );
     cout << endl;
   }while( arc_eqn.beta < 1.0 );
     cout << "FINISHED" << endl;
 }