Luna: Examples/Banded_test.cpp File Reference
Banded_test.cpp File Reference
TODO description / rename file.
#include "Luna/Core"
#include "Luna/Sparse"
Functions
int main ()
Detailed Description
TODO description / rename file.
Definition in file Banded_test.cpp.
Function Documentation
main()
int main ()
Definition at line 11 of file Banded_test.cpp.
References Luna::BandedMatrix< T >::det(), Luna::Matrix< T >::fill_band(), Luna::BandedMatrix< T >::size(), Luna::BandedMatrix< T >::size_above(), Luna::BandedMatrix< T >::size_below(), Luna::BandedMatrix< T >::solve(), and Heat_plot::x.
 {
   cout << "--------------------- Banded Matrices --------------------" << endl;
   std::size_t n( 4 );
   Matrix<double> dense( n, n, 0.0 );
   dense.fill_band( -2, 1.0 );
   dense.fill_band( -1, 2.0 );
   dense.fill_band(  0, 3.0 );
   dense.fill_band(  1, 4.0 );
   cout << " dense = " << dense << endl;
   // Create a BandedMatrix
   std::size_t bands_below( 2 );
   std::size_t bands_above( 1 );
   BandedMatrix<double> band( dense, bands_below, bands_above );
   cout << " band = " << band << endl;
   Vector<double> b( n, 1.0 );
   cout << " b = " << b << endl;
   Vector<double> x;
   x = band.solve( b );
   cout << " x = " << x << endl;
   cout << " det = " << band.det() << endl;
   cout << " band.size() = " << band.size() << endl;
   cout << " band.size_below() = " << band.size_below() << endl;
   cout << " band.size_above() = " << band.size_above() << endl;
   //BandedMatrix<double> B( n, bands_below, bands_above );
   //B( 0, 0 ) = 17.0;
   //B = band;
   //cout << " B * b = " << B * b << endl;
   Matrix<double> B( n, 2, 1.0 );
   B( 1, 1 ) = 2.0; B( 2, 1 ) = 3.0; B( 3, 1 ) = 4.0;
   cout << " B = " << B << endl;
   Matrix<double> X;
   X = band.solve( B );
   cout << " X = " << X << endl;
   /*typedef std::complex<double> cmplx;
   Matrix<cmplx> dense_cmplx( n, n, 0.0 );
   dense_cmplx.fill_band( -2, 1.0 );
   dense_cmplx.fill_band( -1, 2.0 );
   dense_cmplx.fill_band(  0, cmplx( 3.0, 1.0 ) );
   dense_cmplx.fill_band(  1, 4.0 );
   cout << " dense_cmplx = " << dense_cmplx << endl;
   BandedMatrix<cmplx> band_cmplx( dense_cmplx, bands_below, bands_above );
   cout << " band_cmplx = " << band_cmplx.compact() << endl;
   Vector<cmplx> b_cmplx( n, 1.0 );
   cout << " b_cmplx = " << b_cmplx << endl;
   Vector<cmplx> x_cmplx;
   x_cmplx = band_cmplx.solve( b_cmplx );
   cout << " x_cmplx = " << x_cmplx << endl;
   cout << " det_cmplx = " << band_cmplx.det() << endl;*/
   cout << "--- FINISHED ---" << endl;
 }