Luna: Luna::Polynomial< T > Class Template Reference
Luna::Polynomial< T > Class Template Reference
A templated class for defining polynomials.
#include <Polynomial.h>
Public Member Functions
Polynomial ()
Constructor for a unspecified polynomial.
Polynomial (const Vector< T > &coeffs)
Constructor for a polynomial with specified coefficients.
Polynomial (const std::vector< T > &coeffs)
Constructor for a polynomial of given coefficients (using std::vector)
~Polynomial ()
Destructor.
const T & operator[] (const std::size_t &i) const
Indexing operator (read only)
T & operator[] (const std::size_t &i)
Indexing operator.
T operator() (const T &x)
Evaluation operator.
Vector< T > coeffs ()
Return the Vector of coefficients.
std::size_t degree ()
Return the degree of the Polynomial.
void set_degree (const std::size_t &n)
Set the degree of the Polynomial.
T evaluate (const T &x)
Evaluation of the Polynomial.
void quadratic (const T &a, const T &b, const T &c)
Quadratic initialisation \(ax^2 + bx + c \).
Vector< std::complex< double > > quadratic_solve (const T &a, const T &b, const T &c)
Solve the quadratic equation \(ax^2 + bx + c = 0 \).
void cubic (const T &a, const T &b, const T &c, const T &d)
Cubic initialisation \(ax^3 + bx^2 + cx + d \).
Vector< std::complex< double > > cubic_solve (const T &a, const T &b, const T &c, const T &d)
Solve the cubic equation \(ax^3 + bx^2 + cx + d = 0 \).
void polydiv (Polynomial< T > &v, Polynomial< T > &q, Polynomial< T > &r)
Divide the polynomial \(u\) by another \(v\) to find the quotient \(q\) and the remainder \(r\) such that \(u = vq + r \).
Vector< std::complex< double > > roots (const bool &polish)
Find all the roots of the polynomial using Laguerre's method.
Vector< T > derivatives (const T &x)
Determine all the derivatives of the polynomial at a given value.
Detailed Description
template<class T>
class Luna::Polynomial< T >
A templated class for defining polynomials.
Definition at line 20 of file Polynomial.h.
Constructor & Destructor Documentation
Polynomial() [1/3]
template<class T> Luna::Polynomial< T >::Polynomial () inline
Constructor for a unspecified polynomial.
Definition at line 35 of file Polynomial.h.
 {}
Polynomial() [2/3]
template<class T> Luna::Polynomial< T >::Polynomial (const Vector< T > & coeffs) inline
Constructor for a polynomial with specified coefficients.
Definition at line 38 of file Polynomial.h.
References Luna::Vector< T >::size().
                                                   : COEFFS( coeffs )
             {
                 N = coeffs.size() - 1;
             }
Polynomial() [3/3]
template<class T> Luna::Polynomial< T >::Polynomial (const std::vector< T > & coeffs) inline
Constructor for a polynomial of given coefficients (using std::vector)
Definition at line 44 of file Polynomial.h.
References Luna::Polynomial< T >::coeffs().
             {
                 COEFFS.VECTOR = coeffs;
                 N = coeffs.size() - 1;
             }
~Polynomial()
template<class T> Luna::Polynomial< T >::~Polynomial () inline
Destructor.
Definition at line 51 of file Polynomial.h.
References Spectral_ODE_BVP_plot::c, Luna::Polynomial< T >::coeffs(), Luna::Polynomial< T >::cubic(), Luna::Polynomial< T >::cubic_solve(), Luna::Polynomial< T >::degree(), Luna::Polynomial< T >::derivatives(), Luna::Polynomial< T >::evaluate(), Luna::Polynomial< T >::operator()(), Luna::Polynomial< T >::operator[](), Luna::Polynomial< T >::polydiv(), Luna::Polynomial< T >::quadratic(), Luna::Polynomial< T >::quadratic_solve(), Luna::Polynomial< T >::roots(), Luna::Polynomial< T >::set_degree(), and ODE_BVP_System_plot::v.
 {}
Member Function Documentation
coeffs()
template<typename T > Vector< T > Luna::Polynomial< T >::coeffs () inline
Return the Vector of coefficients.
Returns
The Vector of coefficients
Definition at line 167 of file Polynomial.h.
Referenced by main(), Luna::Polynomial< T >::Polynomial(), and Luna::Polynomial< T >::~Polynomial().
{
         return COEFFS;
     }
cubic()
template<typename T > void Luna::Polynomial< T >::cubic (const T & a, const T & b, const T & c, const T & d) inline
Cubic initialisation \(ax^3 + bx^2 + cx + d \).
Parameters
a Coefficient of \(x^3 \)
b Coefficient of \(x^2 \)
c Coefficient of \(x \)
d Constant value in the quadratic
Definition at line 231 of file Polynomial.h.
References Spectral_ODE_BVP_plot::c.
Referenced by Luna::Polynomial< T >::cubic_solve(), and Luna::Polynomial< T >::~Polynomial().
     {
         N = 3;
         COEFFS.resize( 4 );
         COEFFS[ 0 ] = d;
         COEFFS[ 1 ] = c;
         COEFFS[ 2 ] = b;
         COEFFS[ 3 ] = a;
     }
cubic_solve()
template<typename T > Vector< std::complex< double > > Luna::Polynomial< T >::cubic_solve (const T & a, const T & b, const T & c, const T & d) inline
Solve the cubic equation \(ax^3 + bx^2 + cx + d = 0 \).
Parameters
a Coefficient of \(x^3 \)
b Coefficient of \(x^2 \)
c Coefficient of \(x \)
d Constant value in the quadratic
Returns
A Vector< std::complex<double> > containing the three roots
Definition at line 243 of file Polynomial.h.
References Luna::Polynomial< T >::cubic(), f, and Falkner_3D_alternative_plot::g.
Referenced by Luna::Polynomial< T >::roots(), and Luna::Polynomial< T >::~Polynomial().
     {
         this->cubic( a, b, c, d );
         Vector< std::complex<double> > result( 3 );
         T e, f, g;
         e = b / a;
         f = c / a;
         g = d / a;
         T Q, R;
         Q = ( e * e - 3. * f ) / 9.;
         R = ( 2. * e * e * e - 9. * e * f + 27. * g ) / 54.;
         std::complex<double> A, B;
         A = - std::pow( R + std::sqrt( R * R - Q * Q * Q ) , 1. / 3. );
         if ( A != 0. ) {
             B = Q / A;
         } else {
             B = 0.;
         }
         result[ 0 ] = A + B - ( e / 3. );
         std::complex<double> first, second;
         std::complex<double> i( 0.0, 1.0 );
         first  = - 0.5 * ( A + B ) - ( e / 3. );
         second = i * 0.5 * std::sqrt( 3. ) * ( A - B );
         result[ 1 ] = first + second;
         result[ 2 ] = first - second;
         return result;
     }
degree()
template<typename T > std::size_t Luna::Polynomial< T >::degree () inline
Return the degree of the Polynomial.
Returns
The degree of the Polynomial
Definition at line 172 of file Polynomial.h.
Referenced by Luna::Polynomial< T >::~Polynomial().
     {
         return N;
     }
derivatives()
template<typename T > Vector< T > Luna::Polynomial< T >::derivatives (const T & x) inline
Determine all the derivatives of the polynomial at a given value.
Parameters
x Arguement of the Polynomial function
Returns
A Vector of the N + 1 derivatives at the point x where N is the degree of the polynomial
Definition at line 400 of file Polynomial.h.
References f, Falkner_3D_alternative_plot::g, and Heat_plot::x.
Referenced by Luna::Polynomial< T >::~Polynomial().
     {
         Vector<T> derivs( N + 1, 0.0 );
         int nnd, j, i;
         double cnst = 1.0;
         derivs[ 0 ] = COEFFS[ N ];
         for ( i = N - 1; i >= 0; i-- )
         {
             nnd = ( N < ( N - i ) ? N : N-i );
             for ( j = nnd; j > 0; j-- )
             {
                  derivs[ j ] = derivs[ j ] * x + derivs[ j - 1 ];
             }
             derivs[ 0 ] = derivs[ 0 ] * x + COEFFS[ i ];
         }
         for ( i = 2; i < N + 1; i++ )
         {
             cnst *= i;
             derivs[ i ] *= cnst;
         }
         return derivs;
     }
evaluate()
template<typename T > T Luna::Polynomial< T >::evaluate (const T & x) inline
Evaluation of the Polynomial.
Parameters
x Arguement of the Polynomial function
Returns
Value of the Polynomial function
Definition at line 185 of file Polynomial.h.
Referenced by Luna::Polynomial< T >::operator()(), and Luna::Polynomial< T >::~Polynomial().
     {
         T p( COEFFS[ N ] );
         for ( std::size_t j = 0; j < N; j++ )
         {
             p = p * x + COEFFS[ N - j - 1 ];
         }
         return p;
     }
operator()()
template<typename T > T Luna::Polynomial< T >::operator() (const T & x) inline
Evaluation operator.
Parameters
x Arguement of the Polynomial function
Returns
Value of the Polynomial function
Definition at line 161 of file Polynomial.h.
References Luna::Polynomial< T >::evaluate().
Referenced by Luna::Polynomial< T >::~Polynomial().
     {
         return evaluate( x );
     }
operator[]() [1/2]
template<typename T > const T & Luna::Polynomial< T >::operator[] (const std::size_t & i) const inline
Indexing operator (read only)
Parameters
i Index
Returns
A constant reference to the coefficient at the given index
Definition at line 141 of file Polynomial.h.
Referenced by Luna::Polynomial< T >::~Polynomial().
   {
     if ( i < 0 || N < i )
     {
       throw Error( "Polynomial operator [] range error" );
     }
     return COEFFS[ i ];
   }
operator[]() [2/2]
template<typename T > T & Luna::Polynomial< T >::operator[] (const std::size_t & i) inline
Indexing operator.
Parameters
i Index
Returns
A constant reference to the coefficient at the given index
Definition at line 151 of file Polynomial.h.
   {
     if ( i < 0 || N < i )
     {
       throw Error( "Polynomial operator [] range error" );
     }
     return COEFFS[ i ];
   }
polydiv()
template<typename T > void Luna::Polynomial< T >::polydiv (Polynomial< T > & v, Polynomial< T > & q, Polynomial< T > & r) inline
Divide the polynomial \(u\) by another \(v\) to find the quotient \(q\) and the remainder \(r\) such that \(u = vq + r \).
Parameters
v The divisor polynomial
q The quotient polynomial
r The remainder polynomial
Definition at line 278 of file Polynomial.h.
Referenced by Luna::Polynomial< T >::~Polynomial().
     {
         int k, j, n=N, nv=v.N;
         if ( nv == 0 )
         {
              throw Error( "Polynomial.polydiv() divide by zero polynomial");
         }
         while ( nv >= 0 && v[nv] == 0.) nv--;
         if ( nv < 0 )
         {
              throw Error( "Polynomial.polydiv() divide by zero polynomial");
         }
         r.COEFFS = COEFFS;
         r.N = N;
         q.COEFFS.assign( COEFFS.size(), 0.0 );
         q.N = N;
         for ( k = n - nv; k >= 0; k-- )
         {
             q.COEFFS[ k ] = r.COEFFS[ nv + k ] / v.COEFFS[ nv ];
             for ( j = nv + k - 1; j >= k; j-- )
             {
                  r.COEFFS[ j ] -= q.COEFFS[ k ] * v.COEFFS[ j - k ];
             }
         }
         for ( j = nv; j <= n; j++ )
         {
              r.COEFFS[ j ] = 0.0;
         }
         // Remove leading zeros from r and q polynomials
         T r_val( r.COEFFS[ n ] );
         while ( std::abs( r_val ) == 0.0 )
         {
             r.COEFFS.pop_back();
             r.N--;
             n--;
             r_val = r.COEFFS[ n ];
         }
         n = N;
         T q_val( q.COEFFS[ n ] );
         while ( std::abs( q_val ) == 0.0 )
         {
             q.COEFFS.pop_back();
             q.N--;
             n--;
             q_val = q.COEFFS[ n ];
         }
     }
quadratic()
template<typename T > void Luna::Polynomial< T >::quadratic (const T & a, const T & b, const T & c) inline
Quadratic initialisation \(ax^2 + bx + c \).
Parameters
a Coefficient of \(x^2 \)
b Coefficient of \(x \)
c Constant value in the quadratic
Definition at line 196 of file Polynomial.h.
References Spectral_ODE_BVP_plot::c.
Referenced by Luna::Polynomial< T >::quadratic_solve(), and Luna::Polynomial< T >::~Polynomial().
     {
         N = 2;
         COEFFS.resize( 3 );
         COEFFS[ 0 ] = c;
         COEFFS[ 1 ] = b;
         COEFFS[ 2 ] = a;
     }
quadratic_solve()
template<typename T > Vector< std::complex< double > > Luna::Polynomial< T >::quadratic_solve (const T & a, const T & b, const T & c) inline
Solve the quadratic equation \(ax^2 + bx + c = 0 \).
Parameters
a Coefficient of \(x^2 \)
b Coefficient of \(x \)
c Constant value in the quadratic
Returns
A Vector< std::complex<double> > containing the two roots
Definition at line 206 of file Polynomial.h.
References Luna::Polynomial< T >::quadratic().
Referenced by main(), Luna::Polynomial< T >::roots(), and Luna::Polynomial< T >::~Polynomial().
     {
         this->quadratic( a, b, c );
         Vector< std::complex<double> > result( 2 );
         std::complex<double> disc( b * b - 4. * a * c );
         double sgn;
         sgn = std::real( std::conj( b ) * std::sqrt( disc ) );
         if ( sgn >= 0.0 ){
             sgn = 1.0;
         } else {
             sgn = - 1.0;
         }
         std::complex<double> q;
         q = - 0.5 * ( b + sgn * std::sqrt( disc ) );
         result[ 0 ] = q / a;
         result[ 1 ] = c / q;
         return result;
     }
roots()
template<typename T > Vector< std::complex< double > > Luna::Polynomial< T >::roots (const bool & polish) inline
Find all the roots of the polynomial using Laguerre's method.
Parameters
polish True if you want to refine/polish the roots
Returns
A Vector<std::complex<double>> containing the roots
Definition at line 329 of file Polynomial.h.
References Spectral_ODE_BVP_plot::c, Luna::Polynomial< T >::cubic_solve(), Luna::Polynomial< T >::quadratic_solve(), and Heat_plot::x.
Referenced by main(), and Luna::Polynomial< T >::~Polynomial().
     {
         Vector<std::complex<double>> poly_roots( N );
         if ( N <= 0 )
         {
             std::string problem;
             problem = "Polynomial roots: degree must be at least 1";
             throw Error( problem );
         }
         if ( N == 1 )
         {
             poly_roots[ 0 ] = - COEFFS[ 0 ] / COEFFS[ 1 ];
             return poly_roots;
         }
         if ( N == 2 )
         {
             poly_roots = quadratic_solve( COEFFS[ 2 ], COEFFS[ 1 ], COEFFS[ 0 ] );
             return poly_roots;
         }
         if ( N == 3 )
         {
             poly_roots = cubic_solve( COEFFS[ 3 ], COEFFS[ 2 ], COEFFS[ 1 ],
                                                                 COEFFS[ 0 ] );
             return poly_roots;
         }
         const double EPS( 1.0e-14 );
         std::size_t i, its;
         std::complex<double> x, b, c;
         Vector< std::complex<double> > a( N + 1 );
         for ( std::size_t n = 0; n < N + 1; n++ )
         {
             a[ n ] = COEFFS[ n ];
         }
         Vector< std::complex<double> > ad( a );
         for ( int j = N - 1; j >= 0; j-- )
         {
             x = 0.0;
             Vector< std::complex<double> > ad_v( j + 2 );
             for ( int jj = 0; jj < j + 2; jj++ ) ad_v[ jj ] = ad[ jj ];
             laguer( ad_v, x, its );
             if ( std::abs( std::imag(x) ) <=
                      2.0 * EPS * std::abs( std::real( x ) ) )
             {
                 x = std::complex<double>( std::real( x ), 0.0 );
             }
             poly_roots[ j ] = x;
             b = ad[ j + 1 ];
             for ( int jj = j; jj >= 0; jj-- ) {
                 c = ad[ jj ];
                 ad[ jj ] = b ;
                 b = x * b + c;
             }
         }
         // Polish the roots
         if ( polish )
         {
             for ( std::size_t j = 0; j < N; j++ )
             {
                 laguer( a, poly_roots[ j ], its );
             }
         }
         return poly_roots;
     }
set_degree()
template<typename T > void Luna::Polynomial< T >::set_degree (const std::size_t & n) inline
Set the degree of the Polynomial.
Parameters
n The degree of the Polynomial
Definition at line 178 of file Polynomial.h.
Referenced by Luna::Polynomial< T >::~Polynomial().
     {
         N = n;
         COEFFS.resize( n + 1 );
     }
The documentation for this class was generated from the following file:
include/Luna/Polynomial.h