Luna: Luna::RationalSemi< T > Class Template Reference
Luna::RationalSemi< T > Class Template Reference
A templated class for Rational Chebyshev basis functions TL_n(y)
#include <RationalSemi.h>
Public Member Functions
RationalSemi ()
Empty constructor (L = 1.0)
RationalSemi (const double &l)
Constructor.
virtual ~RationalSemi ()
Destructor (virtual since we have virtual functions)
T operator() (const T &y, const int &n)
Evaluation operator for the nth Semi-infinite Rational Chebyshev polynomial at point y.
Vector< T > operator() (const Vector< T > &y, const int &n)
Evaluation operator for the nth Semi-infinite Rational Chebyshev polynomial at a Vector of points.
T operator() (const T &y, const int &n, const int &d)
Evaluation operator for the dth derivative of the nth Semi-infinite Rational Chebyshev polynomial at point y.
Vector< T > operator() (const Vector< T > &y, const int &n, const int &d)
Evaluation operator for the dth derivative of the nth Semi-infinite Rational Chebyshev polynomial at a Vector of points.
RationalSemi< T > & operator= (const RationalSemi< T > &orig)
Copy assignment.
T evaluate (const T &y, const int &n)
Return the nth Semi-infinite Rational Chebyshev polynomial at point y.
Vector< T > evaluate (const Vector< T > &y, const int &n)
Return the nth Semi-infinite Rational Chebyshev polynomial at a Vector of points.
T derivative (const T &y, const int &n, const int &d)
Evaluation of the dth derivative of the nth Semi-infinite Rational Chebyshev polynomial at point y.
Vector< T > derivative (const Vector< T > &y, const int &n, const int &d)
Evaluation of the dth derivative of the nth Semi-infinite Rational Chebyshev polynomial at point y.
Vector< T > approximate (T func(const T &), const int &N)
Approximate a given function by a Semi-infinite Rational Chebyshev polynomial in the interval [0, infinity)
Public Member Functions inherited from Luna::Basis< T >
Basis ()
Constructor.
virtual ~Basis ()
Destructor (virtual since we have virtual functions)
virtual T operator() (const T &x, const std::size_t &n)
Evaluation operator for the nth basis function at point x.
virtual Vector< T > operator() (const Vector< T > &x, const std::size_t &n)
Evaluation operator for the nth basis function at a Vector of points.
virtual T operator() (const T &x, const std::size_t &n, const std::size_t &d)
Evaluation operator for the dth derivative of the nth basis function at point x.
virtual Vector< T > operator() (const Vector< T > &x, const std::size_t &n, const std::size_t &d)
Evaluation operator for the dth derivative of the nth basis function at a Vector of points.
Basis< T > & operator= (const Basis< T > &original)
Copy assignment.
void set_identifier (std::string identifier)
Set the basis function identification string.
std::string get_identifier ()
Get the basis function identification string.
Detailed Description
template<class T>
class Luna::RationalSemi< T >
A templated class for Rational Chebyshev basis functions TL_n(y)
Definition at line 25 of file RationalSemi.h.
Constructor & Destructor Documentation
RationalSemi() [1/2]
template<typename T > Luna::RationalSemi< T >::RationalSemi ()
Empty constructor (L = 1.0)
Definition at line 123 of file RationalSemi.h.
References Luna::Basis< T >::set_identifier().
     {
         L = 1.0;
         this->set_identifier( "RationalSemi" );
     }
RationalSemi() [2/2]
template<typename T > Luna::RationalSemi< T >::RationalSemi (const double & l)
Constructor.
Parameters
l The map parameter
Definition at line 130 of file RationalSemi.h.
References Luna::Basis< T >::set_identifier().
     {
         L = l;
         this->set_identifier( "RationalSemi" );
     }
~RationalSemi()
template<typename T > Luna::RationalSemi< T >::~RationalSemi () virtual
Destructor (virtual since we have virtual functions)
Definition at line 137 of file RationalSemi.h.
     {}
Member Function Documentation
approximate()
template<typename T > Vector< T > Luna::RationalSemi< T >::approximate (T funcconst T &, const int & N) inline
Approximate a given function by a Semi-infinite Rational Chebyshev polynomial in the interval [0, infinity)
Parameters
func The function to be approximated
N The number of coefficients to calculate
Returns
A Vector containing the coefficients
Definition at line 274 of file RationalSemi.h.
References Spectral_ODE_BVP_plot::c, Heat_plot::N, Luna::Vector< T >::rational_semi_grid(), and Spectral_ODE_Rational_plot::y.
Referenced by main().
     {
         Vector<T> c( N );
         Vector<double> y;
         y.rational_semi_grid( N, L );
         for ( std::size_t j = 0; j < N; j++ )
         {
             T sum( 0.0 );
             for ( std::size_t k = 0; k < N; k++ )
             {
                 sum += func( y[ k ] ) * std::cos( ( j * M_PI * ( k + 0.5 ) ) / N );
             }
             c[ j ] = ( 2.0 / N ) * sum;
         }
         c[ 0 ] /= 2;    // - 0.5 * c_0
         return c;
     }
derivative() [1/2]
template<typename T > T Luna::RationalSemi< T >::derivative (const T & y, const int & n, const int & d) inline
Evaluation of the dth derivative of the nth Semi-infinite Rational Chebyshev polynomial at point y.
Parameters
y The point where the polynomial is evaluated
n The degree of the polynomial
d The derivative to return
Returns
The dth derivative of the nth degree polynomial at the point y
Definition at line 200 of file RationalSemi.h.
References Heat_plot::x.
Referenced by Luna::RationalSemi< T >::derivative(), and Luna::RationalSemi< T >::operator()().
     {
         if ( d == 1 )
         {
             Chebyshev<T> cheby;
             T x( ( y - L ) / ( y + L ) );
             T dxdy( 2 * L / std::pow( y + L, 2 ) );
             return dxdy * cheby( x, n, 1 );
             /*T t, s, c;
             t = 2 * std::atan( std::sqrt( L / y ) );
             s = std::sin( t / 2 );
             c = std::cos( t / 2 );
             return n * s * s * s * std::sin( n * t ) / ( L * c );*/
         }
         if ( d == 2 )
         {
             Chebyshev<T> cheby;
             T x( ( y - L ) / ( y + L ) );
             T dxdy( 2 * L / std::pow( y + L, 2 ) );
             T d2xdy2( - 4 * L / std::pow( y + L, 3 ) );
             return dxdy * dxdy * cheby( x, n, 2 ) + d2xdy2 * cheby( x, n, 1 );
             /*T t, s, c;
             t = 2 * std::atan( std::sqrt( L / y ) );
             s = std::sin( t / 2 );
             c = std::cos( t / 2 );
             return std::pow( s, 5 ) * ( 2 * c * s * ( - n * n * std::cos( n * t ) )
                          + ( 3 - 2 * s * s ) * ( - n * std::sin( n * t ) ) )
                          / ( 2 * L * L * std::pow( c, 3 ) );*/
         }
         if ( d == 3 )
         {
             Chebyshev<T> cheby;
             T x( ( y - L ) / ( y + L ) );
             T dxdy( 2 * L / std::pow( y + L, 2 ) );
             T d2xdy2( - 4 * L / std::pow( y + L, 3 ) );
             T d3xdy3( 12 * L / std::pow( y + L, 4 ) );
             return std::pow( dxdy, 3 ) * cheby( x, n, 3 ) +
                          3 * dxdy * d2xdy2 * cheby( x, n, 2 ) + d3xdy3 * cheby( x, n, 1 );
         }
         if ( d == 4 )
         {
             Chebyshev<T> cheby;
             T x( ( y - L ) / ( y + L ) );
             T dxdy( 2 * L / std::pow( y + L, 2 ) );
             T d2xdy2( - 4 * L / std::pow( y + L, 3 ) );
             T d3xdy3( 12 * L / std::pow( y + L, 4 ) );
             T d4xdy4( - 48 * L / std::pow( y + L, 5 ) );
             return std::pow( dxdy, 4 ) * cheby( x, n, 4 ) +
                          6 * dxdy * dxdy * d2xdy2 * cheby( x, n, 3 ) +
                          ( 4 * dxdy * d3xdy3 + 3 * d2xdy2 * d2xdy2 ) * cheby( x, n, 2 ) +
                          d4xdy4 * cheby( x, n, 1 );
         }
         else {
             std::string problem;
             problem += "RationalSemi: Only upto the 4th derivative has been";
             problem += "implemented so far.";
             throw Error( problem );
         }
     }
derivative() [2/2]
template<typename T > Vector< T > Luna::RationalSemi< T >::derivative (const Vector< T > & y, const int & n, const int & d) inline
Evaluation of the dth derivative of the nth Semi-infinite Rational Chebyshev polynomial at point y.
Parameters
y A Vector of points where the polynomial is evaluated
n The degree of the polynomial
d The derivative to return
Returns
The dth derivative of the nth degree polynomial at the point y
Definition at line 263 of file RationalSemi.h.
References Luna::RationalSemi< T >::derivative(), and Luna::Vector< T >::size().
     {
         Vector<T> temp( y.size() );
         for ( std::size_t i = 0; i != y.size(); i++) {
             temp[ i ] = derivative( y[ i ], n, d );
         }
         return temp;
     }
evaluate() [1/2]
template<typename T > T Luna::RationalSemi< T >::evaluate (const T & y, const int & n) inline
Return the nth Semi-infinite Rational Chebyshev polynomial at point y.
Parameters
y The point where the polynomial is evaluated
n The degree of the polynomial
Returns
The value of the nth degree polynomial at y
Definition at line 178 of file RationalSemi.h.
References Heat_plot::x.
Referenced by Luna::RationalSemi< T >::evaluate(), and Luna::RationalSemi< T >::operator()().
     {
         Chebyshev<T> cheby;
         T x( ( y - L ) / ( y + L ) );
         return cheby( x, n );
         /*T t;
         t = 2 * std::atan( std::sqrt( L / y ) );
         return std::cos( n * t );*/
     }
evaluate() [2/2]
template<typename T > Vector< T > Luna::RationalSemi< T >::evaluate (const Vector< T > & y, const int & n) inline
Return the nth Semi-infinite Rational Chebyshev polynomial at a Vector of points.
Parameters
y A Vector of points where the polynomial is evaluated
n The degree of the polynomial
Returns
A Vector of values of the nth degree polynomial
Definition at line 190 of file RationalSemi.h.
References Luna::RationalSemi< T >::evaluate(), and Luna::Vector< T >::size().
     {
         Vector<T> temp( y.size() );
         for ( std::size_t i = 0; i != y.size(); i++) {
             temp[ i ] = evaluate( y[ i ], n );
         }
         return temp;
     }
operator()() [1/4]
template<typename T > T Luna::RationalSemi< T >::operator() (const T & y, const int & n) inline
Evaluation operator for the nth Semi-infinite Rational Chebyshev polynomial at point y.
Parameters
y The point where the polynomial is evaluated
n The degree of the polynomial
Returns
The value of the nth degree polynomial at y
Definition at line 141 of file RationalSemi.h.
References Luna::RationalSemi< T >::evaluate().
     {
         return evaluate( y, n );
     }
operator()() [2/4]
template<typename T > Vector< T > Luna::RationalSemi< T >::operator() (const Vector< T > & y, const int & n) inline
Evaluation operator for the nth Semi-infinite Rational Chebyshev polynomial at a Vector of points.
Parameters
y A Vector of points where the polynomial is evaluated
n The degree of the polynomial
Returns
A Vector of values of the nth degree polynomial
Definition at line 147 of file RationalSemi.h.
References Luna::RationalSemi< T >::evaluate().
     {
         return evaluate( y, n );
     }
operator()() [3/4]
template<typename T > T Luna::RationalSemi< T >::operator() (const T & y, const int & n, const int & d) inline
Evaluation operator for the dth derivative of the nth Semi-infinite Rational Chebyshev polynomial at point y.
Parameters
y The point where the polynomial is evaluated
n The degree of the polynomial
d The derivative to return
Returns
The dth derivative of the nth degree polynomial at the point y
Definition at line 154 of file RationalSemi.h.
References Luna::RationalSemi< T >::derivative().
     {
         return derivative( y, n, d );
     }
operator()() [4/4]
template<typename T > Vector< T > Luna::RationalSemi< T >::operator() (const Vector< T > & y, const int & n, const int & d) inline
Evaluation operator for the dth derivative of the nth Semi-infinite Rational Chebyshev polynomial at a Vector of points.
Parameters
y A Vector of points where the polynomial is evaluated
n The degree of the polynomial
d The derivative to return
Returns
A Vector of the dth derivative of the nth degree polynomial at the Vector of points
Definition at line 160 of file RationalSemi.h.
References Luna::RationalSemi< T >::derivative().
     {
         return derivative( y, n, d );
     }
operator=()
template<typename T > RationalSemi< T > & Luna::RationalSemi< T >::operator= (const RationalSemi< T > & orig) inline
Copy assignment.
Parameters
orig Semi-infinite Rational Chebyshev polynomial to be copied
Returns
The new Semi-infinite Rational Chebyshev polynomial
Definition at line 167 of file RationalSemi.h.
References Luna::Basis< T >::set_identifier().
   {
         if ( this == &orig ){ return *this; }
         this->set_identifier( "RationalSemi" );
     return *this;
   }
The documentation for this class was generated from the following file:
include/Luna/RationalSemi.h