Luna: Luna::SparseMatrix< T > Class Template Reference
Luna::SparseMatrix< T > Class Template Reference
A SparseMatrix class for use with double and std::complex<double>
#include <SparseMatrix.h>
Public Member Functions
SparseMatrix ()
SparseMatrix (const std::size_t &rows, const std::size_t &cols, const std::size_t &n)
SparseMatrix (const std::size_t &rows, const std::size_t &cols, Vector< Triplet< T > > &triplets)
Constructor from Vector of Triplets.
SparseMatrix (const std::size_t &rows, const std::size_t &cols, const Vector< T > &val, const Vector< std::size_t > &row_index, const Vector< std::size_t > &col_start)
Constructor from Vectors.
SparseMatrix (const SparseMatrix< T > &source)
Copy constructor.
~SparseMatrix ()
Destructor.
std::size_t rows () const
Return the number of rows in the SparseMatrix.
std::size_t cols () const
Return the number of columns in the SparseMatrix.
Vector< T > val () const
Return the Vector of nonzero values.
Vector< std::size_t > row_index () const
Return the Vector of row indices.
Vector< std::size_t > col_start () const
Return the Vector of column start pointers.
std::size_t nonzero ()
Return the number of nonzero values.
Vector< std::size_t > col_index () const
The Vector of column indices (triplet form)
Vector< std::size_t > col_start_from_index (const Vector< std::size_t > &col_index)
Calculate column start Vector for a given column index Vector.
void insert (const std::size_t &row, const std::size_t &col, const T &val)
Insert a nonzero element into the SparseMatrix.
void scale (const T &scalar)
Scale the SparseMatrix by a constant factor.
const T & get (const std::size_t &row, const std::size_t &col) const
Get a specific value if it exists.
Vector< T > multiply (const Vector< T > &x)
Multiply the SparseMatrix A by a Vector to the right.
Vector< T > transpose_multiply (const Vector< T > &x)
Multiply the transpose of the SparseMatrix A^T by a Vector to the right.
SparseMatrix< T > transpose () const
Return the transpose of the SparseMatrix.
int solve_BiCG (const Vector< T > &b, Vector< T > &x, int &max_iter, double &tol, int itol=1)
Solve the system of equations Ax=b using the biconjugate gradient method.
void diagonal_preconditioner (const Vector< T > &b, Vector< T > &x)
Diagonal preconditioner for the solve_BiCG method.
void identity_preconditioner (const Vector< T > &b, Vector< T > &x)
Identity preconditioner for the solve_BiCG method.
int solve_BiCGSTAB (const Vector< T > &b, Vector< T > &x, int &max_iter, double &tol)
Solve the system of equations Ax=b using the stabilised biconjugate gradient method BiCGSTAB.
int solve_CG (const Vector< T > &b, Vector< T > &x, int &max_iter, double &tol)
Solve the system of equations Ax=b using the conjugate gradient method.
int solve_QMR (const Vector< T > &b, Vector< T > &x, int &max_iter, double &tol)
Solve the system of equations Ax=b using the Quasi-minimal residual method.
Detailed Description
template<class T>
class Luna::SparseMatrix< T >
A SparseMatrix class for use with double and std::complex<double>
Definition at line 27 of file SparseMatrix.h.
Constructor & Destructor Documentation
SparseMatrix() [1/5]
template<class T> Luna::SparseMatrix< T >::SparseMatrix () inline
Definition at line 40 of file SparseMatrix.h.
Referenced by Luna::SparseMatrix< T >::SparseMatrix().
                    : ROWS( 0 ), COLS( 0 ), N( 0 ),
                   COL_START(), ROW_INDEX(), VAL()
     {}
SparseMatrix() [2/5]
template<class T> Luna::SparseMatrix< T >::SparseMatrix (const std::size_t & rows, const std::size_t & cols, const std::size_t & n) inline
Definition at line 44 of file SparseMatrix.h.
References Luna::SparseMatrix< T >::col_start(), Luna::SparseMatrix< T >::cols(), Luna::SparseMatrix< T >::row_index(), Luna::SparseMatrix< T >::rows(), Luna::SparseMatrix< T >::SparseMatrix(), and Luna::SparseMatrix< T >::val().
                                        : ROWS( rows ), COLS( cols ), N( n ),
                   COL_START( cols + 1, 0 ), ROW_INDEX( n, 0 ), VAL( n, 0.0 )
     {}
SparseMatrix() [3/5]
template<typename T > Luna::SparseMatrix< T >::SparseMatrix (const std::size_t & rows, const std::size_t & cols, Vector< Triplet< T > > & triplets) inline
Constructor from Vector of Triplets.
Parameters
rows The number of rows in the matrix.
cols The number of columns in the matrix.
triplets Vector of Triplets
Definition at line 206 of file SparseMatrix.h.
References Luna::SparseMatrix< T >::col_index(), Luna::SparseMatrix< T >::col_start_from_index(), Luna::SparseMatrix< T >::cols(), Luna::Vector< T >::push_back(), Luna::SparseMatrix< T >::rows(), and Luna::SparseMatrix< T >::val().
   {
     ROWS = rows;
     COLS = cols;
     // Sort the triplets for column major ordering
     std::sort( triplets.begin(), triplets.end() );
     Vector<std::size_t> col_index;
     std::size_t row, col;
     T val;
     N = 0;
     for ( std::size_t i = 0; i < triplets.size(); i++ )
     {
       row = triplets[ i ].get_row();
       col = triplets[ i ].get_col();
       if ( row<0 || ROWS<=row ) {
         throw Error( "SparseMatrix range error: dimension 1 in triplets." );
       }
       if ( col<0 || COLS<=col ) {
         throw Error( "SparseMatrix range error: dimension 2 in triplets." );
       }
       val = triplets[ i ].get_val();
       // Check there are no duplicates (really slows things down)
       /*for ( std::size_t k = 0; k < N; k++ )
       {
         if ( ROW_INDEX[ k ] == row && col_index[ k ] == col )
         {
           throw Error( "SparseMatrix: duplicate entry in triplet list." );
         }
       }*/
       // Push into Vectors
       ROW_INDEX.push_back( row );
       col_index.push_back( col );
       VAL.push_back( val );
       N++;
     }
     // Convert col_index to COL_START
     COL_START = this->col_start_from_index( col_index );
   }
SparseMatrix() [4/5]
template<typename T > Luna::SparseMatrix< T >::SparseMatrix (const std::size_t & rows, const std::size_t & cols, const Vector< T > & val, const Vector< std::size_t > & row_index, const Vector< std::size_t > & col_start) inline
Constructor from Vectors.
Parameters
rows The number of rows in the matrix.
cols The number of columns in the matrix.
val Vector of nonzero values
row_index Vector of row indices
col_start Vector of column start pointers
Definition at line 250 of file SparseMatrix.h.
References Luna::SparseMatrix< T >::col_start(), Luna::SparseMatrix< T >::cols(), Luna::SparseMatrix< T >::row_index(), Luna::SparseMatrix< T >::rows(), Luna::Vector< T >::size(), and Luna::SparseMatrix< T >::val().
   {
     ROWS = rows;
     COLS = cols;
     VAL = val;
     ROW_INDEX = row_index;
     COL_START = col_start;
     N = col_start[ col_start.size() - 1 ];
   }
SparseMatrix() [5/5]
template<typename T > Luna::SparseMatrix< T >::SparseMatrix (const SparseMatrix< T > & source) inline
Copy constructor.
Parameters
source The source SparseMatrix to be copied
Definition at line 264 of file SparseMatrix.h.
   {
     *this = source;
   }
~SparseMatrix()
template<class T> Luna::SparseMatrix< T >::~SparseMatrix () inline
Destructor.
Definition at line 71 of file SparseMatrix.h.
References Luna::SparseMatrix< T >::col_index(), Luna::SparseMatrix< T >::col_start(), Luna::SparseMatrix< T >::col_start_from_index(), Luna::SparseMatrix< T >::cols(), Luna::SparseMatrix< T >::diagonal_preconditioner(), Luna::SparseMatrix< T >::identity_preconditioner(), Luna::SparseMatrix< T >::insert(), Luna::SparseMatrix< T >::multiply(), Luna::SparseMatrix< T >::nonzero(), Luna::SparseMatrix< T >::row_index(), Luna::SparseMatrix< T >::rows(), Luna::SparseMatrix< T >::scale(), Luna::SparseMatrix< T >::solve_BiCG(), Luna::SparseMatrix< T >::solve_BiCGSTAB(), Luna::SparseMatrix< T >::solve_CG(), Luna::SparseMatrix< T >::solve_QMR(), Luna::SparseMatrix< T >::transpose(), Luna::SparseMatrix< T >::transpose_multiply(), Luna::SparseMatrix< T >::val(), and Heat_plot::x.
 {}
Member Function Documentation
col_index()
template<typename T > Vector< std::size_t > Luna::SparseMatrix< T >::col_index () const inline
The Vector of column indices (triplet form)
Returns
A Vector of column indices relating to each value
Definition at line 308 of file SparseMatrix.h.
References Luna::Vector< T >::push_back(), and Luna::Vector< T >::size().
Referenced by Luna::SparseMatrix< T >::diagonal_preconditioner(), Luna::SparseMatrix< T >::get(), Luna::SparseMatrix< T >::insert(), Luna::SparseMatrix< T >::SparseMatrix(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     Vector<std::size_t> temp;
     if ( N == 0 ){ return temp; }
     if ( COL_START.size() < COLS + 1 )
     {
       throw Error( "Some columns have no entries." );
     }
     Vector<std::size_t> gaps( COL_START.size() - 1 );
     for ( std::size_t k = 0; k < gaps.size(); k++ )
     {
       gaps[ k ] = COL_START[ k + 1 ] - COL_START[ k ];
       for ( std::size_t j = 0; j < gaps[ k ]; j ++ )
       {
         temp.push_back( k );
       }
     }
     return temp;
   }
col_start()
template<typename T > Vector< std::size_t > Luna::SparseMatrix< T >::col_start () const inline
Return the Vector of column start pointers.
Returns
The column start Vector
Definition at line 296 of file SparseMatrix.h.
Referenced by Luna::SparseMatrix< T >::col_start_from_index(), main(), Luna::SparseMatrix< T >::SparseMatrix(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     return COL_START;
   }
col_start_from_index()
template<typename T > Vector< std::size_t > Luna::SparseMatrix< T >::col_start_from_index (const Vector< std::size_t > & col_index) inline
Calculate column start Vector for a given column index Vector.
Parameters
col_index A column index Vector
Returns
col_start A column start Vector
Definition at line 329 of file SparseMatrix.h.
References Luna::SparseMatrix< T >::col_start().
Referenced by Luna::SparseMatrix< T >::insert(), Luna::SparseMatrix< T >::SparseMatrix(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     Vector<std::size_t> col_start( COLS + 1, 0 );
     // Computer number of elements in each column
     for ( std::size_t n = 0; n < N; ++n )
     {
       col_start[ col_index[ n ] ]++;
     }
     std::size_t sum( 0 );
     std::size_t k;
     // Cumulative sum
     for ( k = 0; k < COLS; ++k )
     {
       std::size_t ck = col_start[ k ];
       col_start[ k ] = sum;
       sum += ck;
     }
     col_start[ COLS ] = sum;
     return col_start;
   }
cols()
template<typename T > std::size_t Luna::SparseMatrix< T >::cols () const inline
Return the number of columns in the SparseMatrix.
Returns
The number of columns in the SparseMatrix
Definition at line 278 of file SparseMatrix.h.
Referenced by Luna::SparseMatrix< T >::SparseMatrix(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     return COLS;
   }
diagonal_preconditioner()
template<typename T > void Luna::SparseMatrix< T >::diagonal_preconditioner (const Vector< T > & b, Vector< T > & x) inline
Diagonal preconditioner for the solve_BiCG method.
Parameters
b Right hand side Vector
x Solution Vector
Definition at line 613 of file SparseMatrix.h.
References Luna::SparseMatrix< T >::col_index().
Referenced by Luna::SparseMatrix< T >::~SparseMatrix().
   {
     Vector<std::size_t> col_index = this->col_index();
     for ( std::size_t i = 0; i < ROWS; i++ )
     {
       for ( std::size_t k = 0; k < N; k++)
       {
         if ( ROW_INDEX[ k ] == i && col_index[ k ] == i ) {
           x[ i ] = b[ i ] / VAL[ k ];
         }
         else {
           x[ i ] = b[ i ];
         }
       }
     }
   }
get()
template<typename T > const T & Luna::SparseMatrix< T >::get (const std::size_t & row, const std::size_t & col) const inline
Get a specific value if it exists.
Parameters
row The row index
col The column index
Returns
The value stored at that location
Definition at line 410 of file SparseMatrix.h.
References Luna::SparseMatrix< T >::col_index(), and Luna::Vector< T >::size().
   {
     if ( row<0 || ROWS<=row )   {
       throw Error( "SparseMatrix range error in get method: dimension 1." );
     }
     if ( col<0 || COLS<=col )   {
       throw Error( "SparseMatrix range error in get method: dimension 2." );
     }
     if ( COL_START.size() < COLS + 1 )
     {
       std::string problem;
       problem  = "SparseMatrix get error: Some columns have no entries.";
       throw Error( problem );
     }
     Vector<std::size_t> col_index = this->col_index();
     for ( std::size_t k = 0; k < N; k++)
     {
       if ( ROW_INDEX[ k ] == row && col_index[ k ] == col )
       {
         return VAL[ k ];
       }
       else
       {
         throw Error( "SparseMatrix get error: entry does not exist." );
       }
     }
   }
identity_preconditioner()
template<typename T > void Luna::SparseMatrix< T >::identity_preconditioner (const Vector< T > & b, Vector< T > & x) inline
Identity preconditioner for the solve_BiCG method.
Parameters
b Right hand side Vector
x Solution Vector
Definition at line 632 of file SparseMatrix.h.
Referenced by Luna::SparseMatrix< T >::solve_BiCG(), Luna::SparseMatrix< T >::solve_BiCGSTAB(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     for ( std::size_t i = 0; i < ROWS; i++ )
     {
       x[ i ] =  b[ i ];
     }
   }
insert()
template<typename T > void Luna::SparseMatrix< T >::insert (const std::size_t & row, const std::size_t & col, const T & val) inline
Insert a nonzero element into the SparseMatrix.
Parameters
row The row index of the element
col The column index of the element
val The value of the element
Definition at line 352 of file SparseMatrix.h.
References Luna::SparseMatrix< T >::col_index(), Luna::SparseMatrix< T >::col_start_from_index(), Luna::Vector< T >::find(), Luna::Vector< T >::insert(), Luna::Vector< T >::push_back(), Luna::Vector< T >::size(), and Luna::SparseMatrix< T >::val().
Referenced by Luna::SparseMatrix< T >::~SparseMatrix().
   {
     if ( row<0 || ROWS<=row )   {
       throw Error( "SparseMatrix range error: dimension 1." );
     }
     if ( col<0 || COLS<=col )   {
       throw Error( "SparseMatrix range error: dimension 2." );
     }
     if ( COL_START.size() < COLS + 1 )
     {
       std::string problem;
       problem  = "SparseMatrix insert error: Some columns have no entries.\n";
       problem += "Use Vector<Triplet> instead.";
       throw Error( problem );
     }
     // Convert to triplet format
     Vector<std::size_t> col_index = this->col_index();
     // Check if element already exists
     for ( std::size_t k = 0; k < N; k++)
     {
       if ( ROW_INDEX[ k ] == row && col_index[ k ] == col )
       {
         VAL[ k ] = val;
         return;
       }
     }
     if ( N == 0 )
     {
       ROW_INDEX.push_back( row );
       VAL.push_back( val );
       COL_START.push_back( 1 );
       N++;
       return;
     }
     // If not insert new element
     std::size_t find_col = col_index.find( col );
     col_index.insert( find_col, col );
     std::size_t find_row( find_col );
     while ( ROW_INDEX[ find_row ] < row )
     {
       find_row++;
     }
     ROW_INDEX.insert( find_row, row );
     VAL.insert( find_row, val );
     // Convert back to compressed column format
     COL_START = this->col_start_from_index( col_index );
     N++;
     return;
   }
multiply()
template<typename T > Vector< T > Luna::SparseMatrix< T >::multiply (const Vector< T > & x) inline
Multiply the SparseMatrix A by a Vector to the right.
Parameters
x The vector which is to be multiplied
Returns
The result vector A * x
Definition at line 442 of file SparseMatrix.h.
References Luna::Vector< T >::size(), and Spectral_ODE_Rational_plot::y.
Referenced by main(), Luna::SparseMatrix< T >::solve_BiCG(), Luna::SparseMatrix< T >::solve_BiCGSTAB(), Luna::SparseMatrix< T >::solve_CG(), Luna::SparseMatrix< T >::solve_QMR(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     if ( x.size() != COLS )
     {
       throw Error( "SparseMatrix multiply: dimensions do not agree." );
     }
     Vector<T> y( ROWS, 0 );
     std::size_t i, j;
     T xj;
     for ( j = 0; j < COLS; ++j )
     {
       xj = x[ j ];
       for ( i = COL_START[ j ]; i < COL_START[ j + 1 ]; ++i )
       {
         y[ ROW_INDEX[ i ] ] += VAL[ i ] * xj;
       }
     }
     return y;
   }
nonzero()
template<typename T > std::size_t Luna::SparseMatrix< T >::nonzero () inline
Return the number of nonzero values.
Returns
The number of nonzero values
Definition at line 302 of file SparseMatrix.h.
Referenced by main(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     return N;
   }
row_index()
template<typename T > Vector< std::size_t > Luna::SparseMatrix< T >::row_index () const inline
Return the Vector of row indices.
Returns
The Vector of row indices
Definition at line 290 of file SparseMatrix.h.
Referenced by main(), Luna::SparseMatrix< T >::SparseMatrix(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     return ROW_INDEX;
   }
rows()
template<typename T > std::size_t Luna::SparseMatrix< T >::rows () const inline
Return the number of rows in the SparseMatrix.
Returns
The number of rows in the SparseMatrix
Definition at line 272 of file SparseMatrix.h.
Referenced by Luna::SparseMatrix< T >::SparseMatrix(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     return ROWS;
   }
scale()
template<typename T > void Luna::SparseMatrix< T >::scale (const T & scalar) inline
Scale the SparseMatrix by a constant factor.
Parameters
scalar The scalar to multiply the SparseMatrix by
Definition at line 404 of file SparseMatrix.h.
Referenced by Luna::SparseMatrix< T >::~SparseMatrix().
   {
     VAL *= scalar;
   }
solve_BiCG()
template<typename T > int Luna::SparseMatrix< T >::solve_BiCG (const Vector< T > & b, Vector< T > & x, int & max_iter, double & tol, int itol = 1) inline
Solve the system of equations Ax=b using the biconjugate gradient method.
Parameters
b The right-hand side Vector of the system of equations
x Initial guess x_0 the solution is also stored here
max_iter The maximum number of iterations to be performed (the number of iterations actually taken is returned here)
tol Tolerance for convergence (the estimated error is returned here)
itol Convergence test specifier
Returns
Success or failure code (0 = success, 1 = exceeded max_iter)
Definition at line 525 of file SparseMatrix.h.
References Luna::beta(), Luna::SparseMatrix< T >::identity_preconditioner(), Luna::SparseMatrix< T >::multiply(), Luna::Vector< T >::norm_2(), Luna::Vector< T >::size(), and Luna::SparseMatrix< T >::transpose_multiply().
Referenced by main(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     if ( ROWS != b.size() )
     {
       throw Error( "solve_BiCG error: ROWS != b.size() " );
     }
     if ( ROWS != COLS )
     {
       throw Error( "solve_BiCG error: Matrix is not square.");
     }
     if ( b.size() != x.size() )
     {
       throw Error( "solve_BiCG error: b.size() != x.size() " );
     }
     T alpha, beta, rho_1, rho_2 = 1.0;
     double bnrm, znrm, err;
     int j, n = b.size();
     Vector<T> p( n ), pp( n ), r( n ), rr( n ), z( n ), zz( n );
     r = this->multiply( x );
     r = b - r;
     rr = r;
     if ( itol == 1 ) {
       bnrm = b.norm_2();
       //this->diagonal_preconditioner( r, z );           // replaces asolve in NR
       this->identity_preconditioner( r, z );
     }
     else if ( itol == 2 ) {
       //this->diagonal_preconditioner( b, z );
       this->identity_preconditioner( b, z );
       bnrm = z.norm_2();
       //this->diagonal_preconditioner( r, z );
       this->identity_preconditioner( r, z );
     }
     else {
       throw Error( "SparseMatrix solve_BiCG error: illegal itol." );
     }
     // Main loop
     int iter( 0 );
     while ( iter < max_iter )
     {
       ++iter;
       //this->diagonal_preconditioner( rr, zz );
       this->identity_preconditioner( rr, zz );
       rho_1 = z.dot( rr );
       if ( iter == 1 ) {
         p = z;
         pp = zz;
       } else {
         beta = rho_1 / rho_2;
         p = beta * p + z;
         pp = beta * pp + zz;
       }
       z = this->multiply( p );
       alpha = rho_1 / z.dot( pp );
       zz = this->transpose_multiply( pp );
       x += alpha * p;
       r -= alpha * z;
       rr -= alpha * zz;
       //this->diagonal_preconditioner( r, z );
       this->identity_preconditioner( r, z );
       rho_2 = rho_1;
       if ( itol == 1 ) {
         err = r.norm_2() / bnrm;
       } else if ( itol == 2 ) {
         err = z.norm_2() / bnrm;
       }
       if ( err <= tol )
       {
         max_iter = iter;
         tol = err;
         return 0;
       }
     } // end of while loop
     return 1;
   }
solve_BiCGSTAB()
template<typename T > int Luna::SparseMatrix< T >::solve_BiCGSTAB (const Vector< T > & b, Vector< T > & x, int & max_iter, double & tol) inline
Solve the system of equations Ax=b using the stabilised biconjugate gradient method BiCGSTAB.
Parameters
b The right-hand side Vector of the system of equations
x Initial guess x_0 the solution is also stored here
max_iter The maximun number of iterations (the number of iterations performed will also be returned here)
tol Tolerance for convergence (the error residual is also returned here)
Returns
Success or failure code (0 = success, 1 = exceeded max_iter)
Definition at line 642 of file SparseMatrix.h.
References Luna::beta(), Luna::Vector< T >::dot(), Luna::SparseMatrix< T >::identity_preconditioner(), Luna::SparseMatrix< T >::multiply(), Luna::Vector< T >::norm_2(), Luna::Vector< T >::size(), Heat_plot::t, and ODE_BVP_System_plot::v.
Referenced by main(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     // https://math.nist.gov/iml++
     double resid;
     Vector<T> p( x.size(), 0.0 ), phat( x.size(), 0.0 );
     Vector<T> s( x.size(), 0.0 ), shat( x.size(), 0.0 );
     Vector<T> v( x.size(), 0.0 );
     Vector<T> temp, t;
     T rho_1 = 1.0;
     T rho_2 = 1.0;
     T alpha = 1.0;
     T beta;
     T omega = 1.0;
     double normb = b.norm_2();
     Vector<T> r;
     r = this->multiply( x );
     r = b - r;
     Vector<T> rtilde = r;
     if ( normb == 0.0 )
     {
       normb = 1.;
     }
     if ( ( resid = r.norm_2() / normb ) <= tol )
     {
       tol = resid;
       max_iter = 0;
       return 0;
     }
     for ( int i = 1; i <= max_iter; i++ )
     {
       rho_1 = rtilde.dot( r );
       if ( rho_1 == 0.0 ) {
         tol = r.norm_2() / normb;
         return 2;
       }
       if ( i == 1 ) {
         p = r;
       } else {
         beta = ( rho_1 / rho_2 ) * ( alpha / omega );
         temp = p - omega * v;
         p = r + beta * temp;
         //p = r + beta * ( p - omega * v );
       }
       //phat = p; //could have preconditioner here phat = M.solve(p);
       this->identity_preconditioner( p, phat );
       v = this->multiply( phat );
       alpha = rho_1 / rtilde.dot( v );
       s = r - alpha * v;
       if ( ( resid = s.norm_2() / normb ) <= tol ) {
         x += alpha * phat;
         tol = resid;
         max_iter = i;
         return 0;
       }
       //shat = s; //could have preconditioner here shat = M.solve(s);
       this->identity_preconditioner( s, shat );
       t = this->multiply( shat );
       omega = t.dot( s ) / t.dot( t );
       x += alpha * phat;
       x += omega * shat;
       r = s - omega * t;
       rho_2 = rho_1;
       if ( ( resid = r.norm_2() / normb ) < tol ) {
         tol = resid;
         max_iter = i;
         return 0;
       }
       if ( omega == 0.0 ) {
         tol = r.norm_2() / normb;
         return 3;
       }
     }
     tol = resid;
     return 1;
   }
solve_CG()
template<typename T > int Luna::SparseMatrix< T >::solve_CG (const Vector< T > & b, Vector< T > & x, int & max_iter, double & tol) inline
Solve the system of equations Ax=b using the conjugate gradient method.
Parameters
b The right-hand side Vector of the system of equations
x Initial guess x_0 the solution is also stored here
max_iter The maximun number of iterations (the number of iterations performed will also be returned here)
tol Tolerance for convergence (the error residual is also returned here)
Returns
Success or failure code (0 = success, 1 = exceeded max_iter)
Definition at line 727 of file SparseMatrix.h.
References Luna::beta(), Luna::Vector< T >::dot(), Luna::SparseMatrix< T >::multiply(), Luna::Vector< T >::norm_2(), and Luna::Vector< T >::size().
Referenced by Luna::SparseMatrix< T >::~SparseMatrix().
   {
     double resid;
     Vector<T> p( x.size(), 0.0 ), z( x.size(), 0.0 ), q( x.size(), 0.0 );
     Vector<T> temp;
     T rho = 1.0;
     T rho_1 = 1.0;
     T alpha = 1.0;
     T beta;
     double normb = b.norm_2();
     Vector<T> r;
     r = this->multiply( x );
     r = b - r;
     if ( normb == 0.0 )
     {
       normb = 1.;
     }
     if ( ( resid = r.norm_2() / normb ) <= tol )
     {
       tol = resid;
       max_iter = 0;
       return 0;
     }
     for ( int i = 1; i <= max_iter; i++ )
     {
       //this->diagonal_preconditioner( r, z );
       //this->identity_preconditioner( r, z );
       z = r; // Could have preconditioner here?
       rho = r.dot( z );
       if ( i == 1 ) {
         p = z;
       } else {
         beta = rho / rho_1;
         p = z + beta * p;
       }
       q = this->multiply( p );
       alpha = rho / p.dot( q );
       x += alpha * p;
       r -= alpha * q;
       if ( ( resid = r.norm_2() / normb ) <= tol )
       {
         tol = resid;
         max_iter = i;
         return 0;
       }
       rho_1 = rho;
     }
     tol = resid;
     return 1;
   }
solve_QMR()
template<typename T > int Luna::SparseMatrix< T >::solve_QMR (const Vector< T > & b, Vector< T > & x, int & max_iter, double & tol) inline
Solve the system of equations Ax=b using the Quasi-minimal residual method.
Parameters
b The right-hand side Vector of the system of equations
x Initial guess x_0 the solution is also stored here
max_iter The maximun number of iterations (the number of iterations performed will also be returned here)
tol Tolerance for convergence (the error residual is also returned here)
Returns
Success or failure code (0 = success, 1 = exceeded max_iter)
Definition at line 790 of file SparseMatrix.h.
References Luna::beta(), Luna::Vector< T >::dot(), Falkner_3D_alternative_plot::eta, Luna::gamma(), Luna::SparseMatrix< T >::multiply(), Luna::Vector< T >::norm_2(), Luna::SparseMatrix< T >::transpose_multiply(), ODE_BVP_System_plot::v, Spectral_Poisson_plot::xi, and Spectral_ODE_Rational_plot::y.
Referenced by Luna::SparseMatrix< T >::~SparseMatrix().
   {
     double resid;
     T rho( 1.0 ), rho_1( 1.0 ), xi( 1.0 );
     T delta( 1.0 ), ep( 1.0 );
     T beta;
     double gamma, gamma_1, eta, theta, theta_1;
     Vector<T> r, v, y, w, z;
     Vector<T> v_tld, w_tld, y_tld, z_tld;
     Vector<T> p, q, p_tld, d, s;
     double normb = b.norm_2();
     r = this->multiply( x );
     r = b - r;
     if ( normb == 0.0 )
     {
       normb = 1.0;
     }
     if ( ( resid = r.norm_2() / normb ) <= tol )
     {
       tol = resid;
       max_iter = 0;
       return 0;
     }
     v_tld = r;
     y = v_tld; // Could have preconditioner here
     rho = y.norm_2();
     w_tld = r;
     z = w_tld; // Could have preconditioner here
     xi = z.norm_2();
     gamma = 1.0;
     eta = - 1.0;
     theta = 0.0;
     for ( int i = 1; i <= max_iter; i++ )
     {
       if ( rho == 0.0 )
         return 2;                     // Return on breakdown
       if ( xi == 0.0 )
         return 7;                     // Return on breakdown
       v = ( 1. / rho ) * v_tld;
       y = ( 1. / rho ) * y;
       w = ( 1. / xi ) * w_tld;
       z = ( 1. / xi ) * z;
       delta = z.dot( y );
       if ( delta == 0.0 )
         return 5;                     // Return on breakdown
       y_tld = y;
       z_tld = z;  // Could have preconditioners here
       if (i > 1) {
         p = y_tld - ( xi * delta / ep ) * p;
         q = z_tld - ( rho * delta / ep ) * q;
       } else {
         p = y_tld;
         q = z_tld;
       }
       p_tld = this->multiply( p );
       ep = q.dot( p_tld );
       if ( ep == 0.0 )
         return 6;                       // Return on breakdown
       beta = ep / delta;
       if ( beta == 0.0 )
         return 3;                       // Return on breakdown
       v_tld = p_tld - beta * v;
       y = v_tld; // Could have preconditioner here
       rho_1 = rho;
       rho = y.norm_2();
       w_tld = this->transpose_multiply( q );
       w_tld -= beta * w;
       z = w_tld; // Could have preconditioner here
       xi = z.norm_2();
       gamma_1 = gamma;
       theta_1 = theta;
       theta = rho / ( gamma_1 * beta );
       gamma = 1.0 / std::sqrt( 1.0 + theta * theta );
       if ( gamma == 0.0 )
         return 4;                       // Return on breakdown
       eta = - eta * rho_1 * gamma * gamma / ( beta * gamma_1 * gamma_1 );
       if (i > 1) {
         d = eta * p + ( theta_1 * theta_1 * gamma * gamma ) * d;
         s = eta * p_tld + ( theta_1 * theta_1 * gamma * gamma ) * s;
       } else {
         d = eta * p;
         s = eta * p_tld;
       }
       x += d;
       r -= s;
       if ( ( resid = r.norm_2() / normb ) <= tol )
       {
         tol = resid;
         max_iter = i;
         return 0;
       }
     }
     tol = resid;
     return 1;
   }
transpose()
template<typename T > SparseMatrix< T > Luna::SparseMatrix< T >::transpose () const inline
Return the transpose of the SparseMatrix.
Returns
The transpose of the SparseMatrix
Definition at line 488 of file SparseMatrix.h.
References Spectral_ODE_Rational_plot::index.
Referenced by Luna::SparseMatrix< T >::~SparseMatrix().
   {
     std::size_t i, j, k, index, m = ROWS, n = COLS;
     SparseMatrix<T> at( n, m, N );
     Vector<int> count( m, 0 );
     for ( i = 0; i < n; i++ )
     {
       for ( j = COL_START[ i ]; j < COL_START[ i + 1 ]; j++ )
       {
         k = ROW_INDEX[ j ];
         count[ k ]++;
       }
     }
     for ( j = 0; j < m; j++ )
     {
       at.COL_START[ j + 1 ] = at.COL_START[ j ] + count[ j ];
     }
     for ( j = 0; j < m; j++ )
     {
       count[ j ] = 0;
     }
     for ( i = 0; i < n; i++ )
     {
       for ( j = COL_START[ i ]; j < COL_START[ i + 1 ]; j++ )
       {
         k = ROW_INDEX[ j ];
         index = at.COL_START[ k ] + count[ k ];
         at.ROW_INDEX[ index ] = i;
         at.VAL[ index ] = VAL[ j ];
         count[ k ]++;
       }
     }
     return at;
   }
transpose_multiply()
template<typename T > Vector< T > Luna::SparseMatrix< T >::transpose_multiply (const Vector< T > & x) inline
Multiply the transpose of the SparseMatrix A^T by a Vector to the right.
Parameters
x The vector which is to be multiplied
Returns
The result vector A^T * x
Definition at line 465 of file SparseMatrix.h.
References Luna::Vector< T >::size(), and Spectral_ODE_Rational_plot::y.
Referenced by Luna::SparseMatrix< T >::solve_BiCG(), Luna::SparseMatrix< T >::solve_QMR(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     if ( x.size() != ROWS )
     {
       std::string problem;
       problem  = "SparseMatrix transpose_multiply: dimensions do not agree.";
       throw Error( problem );
     }
     Vector<T> y( COLS, 0 );
     std::size_t i, j;
     for ( i = 0; i < COLS; i++ )
     {
       for ( j = COL_START[ i ]; j < COL_START[ i + 1 ]; j++ )
       {
         y[ i ] += VAL[ j ] * x[ ROW_INDEX[ j ] ];
       }
     }
     return y;
   }
val()
template<typename T > Vector< T > Luna::SparseMatrix< T >::val () const inline
Return the Vector of nonzero values.
Returns
The Vector of nonzero values
Definition at line 284 of file SparseMatrix.h.
Referenced by Luna::SparseMatrix< T >::insert(), main(), Luna::SparseMatrix< T >::SparseMatrix(), and Luna::SparseMatrix< T >::~SparseMatrix().
   {
     return VAL;
   }
The documentation for this class was generated from the following file:
include/Luna/SparseMatrix.h