Luna: Luna::Mesh1D< T, X > Class Template Reference
Luna::Mesh1D< T, X > Class Template Reference
A templated class.
#include <Mesh1D.h>
Public Member Functions
Mesh1D ()
Constructor for an empty mesh.
Mesh1D (const Vector< X > &nodes, const std::size_t &nvars)
Constructor (given nodal distribution)
~Mesh1D ()
Destructor.
const T & operator() (const std::size_t node, const std::size_t var) const
Read only access of a variable at a given node.
T & operator() (const std::size_t node, const std::size_t var)
Read and write access of a variable at a given node.
const X & coord (const std::size_t &node) const
Read only access to the nodal value.
X & coord (const std::size_t &node)
Read and write access to the nodal value.
void set_nodes_vars (const std::size_t &node, const Vector< T > &vec)
Set the variables stored at a specific node.
Vector< T > get_nodes_vars (const std::size_t &node) const
Get the variables stored at a specific node.
std::size_t nnodes () const
Return the number of nodal points in the mesh.
std::size_t nvars () const
Return the number of variables stored in the mesh.
const Vector< X > & nodes () const
Return the vector of nodal positions.
Vector< T > get_interpolated_vars (const X &pos) const
Get the variables at an interpolated position (first order scheme)
void output (std::string filename, int precision=15) const
Output data to a file.
void read (std::string filename, int precision=15, bool reset=false)
Read data from a file.
const Vector< T > & vars_as_vector () const
Return a vector of all the variables stored in the mesh.
void set_vars_from_vector (const Vector< T > &vec)
Set the variables of this mesh from a vector.
T integral (std::size_t var=0) const
Integrate a given variable over the domain.
void remesh (const Vector< X > &z)
Linearly interpolate this mesh data into a new nodal mesh.
template<>
Vector< double > get_interpolated_vars (const double &x_pos) const
template<>
Vector< std::complex< double > > get_interpolated_vars (const double &x_pos) const
template<>
Vector< std::complex< double > > get_interpolated_vars (const std::complex< double > &pos) const
template<>
void read (std::string filename, int precision, bool reset)
template<>
void remesh (const Vector< double > &newX)
template<>
void remesh (const Vector< double > &newX)
template<>
void remesh (const Vector< std::complex< double >> &z)
Detailed Description
template<class T, class X = double>
class Luna::Mesh1D< T, X >
A templated class.
Definition at line 25 of file Mesh1D.h.
Constructor & Destructor Documentation
Mesh1D() [1/2]
template<class T, class X = double> Luna::Mesh1D< T, X >::Mesh1D () inline
Constructor for an empty mesh.
Definition at line 35 of file Mesh1D.h.
              : NV( 0 )
     {}
Mesh1D() [2/2]
template<class T, class X = double> Luna::Mesh1D< T, X >::Mesh1D (const Vector< X > & nodes, const std::size_t & nvars) inline
Constructor (given nodal distribution)
Parameters
nodes The Vector of nodal points
nvars The number of variables
Definition at line 41 of file Mesh1D.h.
References Luna::Vector< T >::size().
                                                              :
         NV( nvars ), NODES( nodes )
     {
       // Create the storage Vector and set the contents to zero
       VARS = Vector<T>( NV * NODES.size(), T( 0.0 ) );
     }
~Mesh1D()
template<class T, class X = double> Luna::Mesh1D< T, X >::~Mesh1D () inline
Destructor.
Definition at line 49 of file Mesh1D.h.
 {}
Member Function Documentation
coord() [1/2]
template<typename T , typename X > const X & Luna::Mesh1D< T, X >::coord (const std::size_t & node) const inline
Read only access to the nodal value.
Parameters
node Node index
Returns
The nodal value at the specified index
Definition at line 141 of file Mesh1D.h.
Referenced by main(), and Luna::Mesh1D< T, X >::operator()().
   {
     return NODES[ node ];
   }
coord() [2/2]
template<typename T , typename X > X & Luna::Mesh1D< T, X >::coord (const std::size_t & node) inline
Read and write access to the nodal value.
Parameters
node Node index
Returns
The nodal value at the specified index
Definition at line 147 of file Mesh1D.h.
   {
     return NODES[ node ];
   }
get_interpolated_vars() [1/4]
template<class T, class X = double> Vector<T> Luna::Mesh1D< T, X >::get_interpolated_vars (const X & pos) const
Get the variables at an interpolated position (first order scheme)
Parameters
pos Position within the nodal domain
Returns
The Vector of interpolated variables
Referenced by Luna::Mesh2D< T >::get_interpolated_vars(), main(), and Luna::Mesh1D< T, X >::operator()().
get_interpolated_vars() [2/4]
template<> Vector< double > Luna::Mesh1D< double, double >::get_interpolated_vars (const double & x_pos) const inline
Definition at line 197 of file Mesh1D.h.
References Luna::Mesh1D< T, X >::get_nodes_vars(), and Luna::Vector< T >::size().
   {
     for ( unsigned node = 0; node < NODES.size() - 1; ++node )
     {
       // find bracketing nodes
       if ( ( ( NODES[ node ] < x_pos ) && ( NODES[ node + 1 ] > x_pos ) )
               ||  ( std::abs( NODES[ node ] - x_pos ) < 1.e-7  )
               || ( std::abs( NODES[ node + 1 ] - x_pos ) < 1.e-7 ) )
       {
         // distance from left node
         double delta_x( x_pos - NODES[ node ] );
         // empty data to return
         Vector<double> left;
         Vector<double> right;
         Vector<double> deriv;
         // interpolate data linearly
         left = get_nodes_vars( node );
         right = get_nodes_vars( node + 1 );
         deriv = ( right - left ) / ( NODES[ node + 1 ] - NODES[ node ] );
         // overwrite right
         right = left + deriv * delta_x;
         return right;
       }
     }
     // If the position is not in the range throw an error
     throw Error( "Mesh error: interpolation not in range " );
   }
get_interpolated_vars() [3/4]
template<> Vector< std::complex< double > > Luna::Mesh1D< std::complex< double >, double >::get_interpolated_vars (const double & x_pos) const inline
Definition at line 228 of file Mesh1D.h.
References Luna::Mesh1D< T, X >::get_nodes_vars(), and Luna::Vector< T >::size().
   {
     for ( unsigned node = 0; node < NODES.size() - 1; ++node )
     {
       // find bracketing nodes
       if ( ( NODES[ node ] < x_pos
         || std::abs( NODES[ node ] - x_pos ) < 1.e-7 ) &&
            ( NODES[ node + 1 ] > x_pos
         || std::abs( NODES[ node + 1 ] - x_pos ) < 1.e-7 ) )
       {
         // distance from left node
         double delta_x( x_pos - NODES[ node ] );
         // empty data to return
         Vector<std::complex<double> > left;
         Vector<std::complex<double> > right;
         Vector<std::complex<double> > deriv;
         // interpolate data linearly
         left = get_nodes_vars( node );
         right = get_nodes_vars( node + 1 );
         deriv = ( right - left ) / ( NODES[ node + 1 ] - NODES[ node ] );
         // overwrite right
         right = left + deriv * delta_x;
         return right;
       }
     }
     // If the position is not in the range throw an error
     throw Error( "Mesh error: interpolation not in range " );
   }
get_interpolated_vars() [4/4]
template<> Vector< std::complex< double > > Luna::Mesh1D< std::complex< double >, std::complex< double > >::get_interpolated_vars (const std::complex< double > & pos) const inline
Definition at line 259 of file Mesh1D.h.
References Luna::Mesh1D< T, X >::get_nodes_vars(), Luna::Vector< T >::real(), and Luna::Vector< T >::size().
   {
     double x_pos( pos.real() );
     for ( unsigned node = 0; node < NODES.size() - 1; ++node )
     {
       // find bracketing nodes
       if ( ( NODES[ node ].real() < x_pos
         || std::abs( NODES[ node ].real() - x_pos ) < 1.e-7 ) &&
            ( NODES[ node + 1 ].real() > x_pos
         || std::abs( NODES[ node + 1 ].real() - x_pos ) < 1.e-7 ) )
       {
         // distance from left node -- real coordinate is given. We also need to
         // interpolate between the two complex nodes
         std::complex<double> delta_z = ( NODES[ node + 1 ] - NODES[ node ] )
                                        * ( x_pos - NODES[ node ].real() )
                                        / ( NODES[ node + 1 ].real()
                                          - NODES[ node ].real() );
         // empty data to return
         Vector<std::complex<double> > left;
         Vector<std::complex<double> > right;
         Vector<std::complex<double> > deriv;
         // interpolate data linearly
         left = get_nodes_vars( node );
         right = get_nodes_vars( node + 1 );
         // derivative of the data
         deriv = ( right - left ) / ( NODES[ node + 1 ] - NODES[ node ] );
         // overwrite right
         right = left + deriv * delta_z;
         return right;
       }
     }
     // If the position is not in the range throw an error
     throw Error( "Mesh error: interpolation not in range " );
   }
get_nodes_vars()
template<typename T , typename X > Vector< T > Luna::Mesh1D< T, X >::get_nodes_vars (const std::size_t & node) const inline
Get the variables stored at a specific node.
Parameters
node Node index
Returns
The Vector of variables
Definition at line 164 of file Mesh1D.h.
References Luna::Vector< T >::push_back(), and Luna::Vector< T >::size().
Referenced by Luna::Mesh1D< T, X >::get_interpolated_vars(), and Luna::Mesh1D< T, X >::operator()().
   {
     if ( ( node >= NODES.size() ) || ( node < 0 ) )
     {
       throw Error( "Mesh error: get_nodes_vars range error." );
     }
     Vector<T> nodes_vars;
     for ( std::size_t var = 0; var < NV; ++var )
     {
       nodes_vars.push_back( VARS[ node * NV + var ] );
     }
     return nodes_vars;
   }
integral()
template<typename T , typename X > T Luna::Mesh1D< T, X >::integral (std::size_t var = 0) const inline
Integrate a given variable over the domain.
Parameters
var Variable index
Definition at line 375 of file Mesh1D.h.
References Luna::Vector< T >::size().
Referenced by main(), and Luna::Mesh1D< T, X >::operator()().
   {
     T sum( 0.0 );
     X dx( 0.0 );
     for ( std::size_t node = 0; node < NODES.size() - 1; ++node )
     {
       dx = ( NODES[ node + 1 ] - NODES[ node ] );
       sum += 0.5 * dx * ( VARS[ node * NV + var ]
                         + VARS[ ( node + 1 ) * NV + var ] );
     }
     return sum;
   }
nnodes()
template<typename T , typename X > std::size_t Luna::Mesh1D< T, X >::nnodes () const inline
Return the number of nodal points in the mesh.
Returns
The number of nodal points
Definition at line 179 of file Mesh1D.h.
References Luna::Vector< T >::size().
Referenced by main(), and Luna::Mesh1D< T, X >::operator()().
   {
     return NODES.size();
   }
nodes()
template<typename T , typename X > const Vector< X > & Luna::Mesh1D< T, X >::nodes () const inline
Return the vector of nodal positions.
Returns
The Vector of nodal points
Definition at line 191 of file Mesh1D.h.
Referenced by Luna::Mesh1D< T, X >::operator()().
   {
     return NODES;
   }
nvars()
template<typename T , typename X > std::size_t Luna::Mesh1D< T, X >::nvars () const inline
Return the number of variables stored in the mesh.
Returns
The number of variables
Definition at line 185 of file Mesh1D.h.
Referenced by main(), and Luna::Mesh1D< T, X >::operator()().
   {
     return NV;
   }
operator()() [1/2]
template<class T, class X = double> const T& Luna::Mesh1D< T, X >::operator() (const std::size_t node, const std::size_t var) const inline
Read only access of a variable at a given node.
Parameters
node Node index
var Variable index
Returns
A reference to the variable stored at the given node
Definition at line 57 of file Mesh1D.h.
     {
       return VARS[ node * NV + var ];
     }
operator()() [2/2]
template<class T, class X = double> T& Luna::Mesh1D< T, X >::operator() (const std::size_t node, const std::size_t var) inline
Read and write access of a variable at a given node.
Parameters
node Node index
var Variable index
Returns
A reference to the variable var stored at the index i
Definition at line 66 of file Mesh1D.h.
References Luna::Mesh1D< T, X >::coord(), Luna::Mesh1D< T, X >::get_interpolated_vars(), Luna::Mesh1D< T, X >::get_nodes_vars(), Luna::Mesh1D< T, X >::integral(), Luna::Mesh1D< T, X >::nnodes(), Luna::Mesh1D< T, X >::nodes(), Luna::Mesh1D< T, X >::nvars(), Luna::Mesh1D< T, X >::output(), Luna::Mesh1D< T, X >::read(), Luna::Mesh1D< T, X >::remesh(), Luna::Mesh1D< T, X >::set_nodes_vars(), Luna::Mesh1D< T, X >::set_vars_from_vector(), and Luna::Mesh1D< T, X >::vars_as_vector().
     {
       return VARS[ node * NV + var ];
     }
output()
template<typename T , typename X > void Luna::Mesh1D< T, X >::output (std::string filename, int precision = 15) const inline
Output data to a file.
Parameters
filename Name of the file to write to
precision Decimal precision of the output
Definition at line 296 of file Mesh1D.h.
References Luna::Vector< T >::size().
Referenced by main(), and Luna::Mesh1D< T, X >::operator()().
   {
     std::ofstream out;
     out.open( filename.c_str() );
     out.precision( precision );
     out.setf( std::ios::showpoint );
     out.setf( std::ios::showpos );
     out.setf( std::ios::scientific );
     for ( std::size_t i = 0; i < NODES.size(); ++i )
     {
       out << NODES[ i ] << " ";
       for ( std::size_t var = 0; var < NV; ++var )
       {
         out << VARS[ i * NV + var ] << " ";
       }
       out << "\n";
     }
   }
read() [1/2]
template<class T, class X = double> void Luna::Mesh1D< T, X >::read (std::string filename, int precision = 15, bool reset = false)
Read data from a file.
Parameters
filename Name of the file to read from
precision Decimal precision of the input
reset Reset the nodal positions after reading from file
Referenced by Luna::Mesh1D< T, X >::operator()().
read() [2/2]
template<> void Luna::Mesh1D< double, double >::read (std::string filename, int precision, bool reset) inline
Definition at line 316 of file Mesh1D.h.
References Luna::Vector< T >::size(), ODE_BVP_System_plot::v, and Heat_plot::x.
     {
         std::ifstream inFile;
         inFile.open( filename.c_str() );
         inFile.precision( precision );
         inFile.setf( std::ios::showpoint );
         inFile.setf( std::ios::showpos );
         inFile.setf( std::ios::scientific );
         if (!inFile) {
             throw Error( "Mesh1D unable to open file" );
         }
         double x;
         Vector<double> vals( NV );
         for ( std::size_t i=0; i<NODES.size(); ++i )
         {
             inFile >> x;
             for ( std::size_t v=0; v<vals.size(); ++v )
             {
                 inFile >> vals[ v ];
                 VARS[ i * NV + v ] = vals[ v ];
             }
             // Check the mesh
             if ( !reset )
             {
                 if ( ( std::abs( x - NODES[ i ] ) > 1.e-6 ) )
                 {
                     std::cout << " Read x = " << x
                     << " Expected x = " << NODES[ i ] << std::endl;
                     throw Error( "Mesh1D: file has different nodal points." );
                 }
             }
             else
             {
                 NODES[ i ] = x;
             }
         }
         inFile.close();
     }
remesh() [1/4]
template<class T, class X = double> void Luna::Mesh1D< T, X >::remesh (const Vector< X > & z)
Linearly interpolate this mesh data into a new nodal mesh.
Parameters
z The nodal coordinates to be used in the new mesh.
Referenced by Luna::Mesh1D< T, X >::operator()().
remesh() [2/4]
template<> void Luna::Mesh1D< double, double >::remesh (const Vector< double > & newX) inline
Definition at line 390 of file Mesh1D.h.
References Luna::Vector< T >::back(), and Luna::Vector< T >::size().
   {
     if ( std::abs( NODES[ 0 ] - newX[ 0 ] ) > 1.e-10 ||
          std::abs( NODES.back() - newX.back() ) > 1.e-10 )
     {
       std::string problem;
       problem = " The Mesh1D.remesh method has been called with a passed\n";
       problem += " coordinate vector that has different start and/or \n";
       problem += " end points from the instantiated object. \n";
       throw Error( problem );
     }
     for ( std::size_t i = 0; i < newX.size() - 1; ++i )
     {
       if ( newX[ i ] >= newX[ i + 1 ] )
       {
         std::string problem;
         problem = " The Mesh1D.remesh method has been passed \n";
         problem += " a non-monotonic coordinate vector. \n";
         throw Error( problem );
       }
     }
     Vector<double> copy_of_vars( VARS );
     VARS.resize( newX.size() * NV );
     for ( std::size_t node = 1; node < newX.size() - 1; ++node )
     {
       // loop through the source mesh and find the bracket-nodes
       for ( std::size_t i = 0; i < NODES.size(); ++i )
       {
         if ( ( NODES[ i ] <= newX[ node ] ) &&
              ( newX[ node ] < NODES[ i + 1 ] ) )
         {
           // linearly interpolate each variable in the mesh
           for ( std::size_t var = 0; var < NV; ++var )
           {
             double dX = newX[ node ] - NODES[ i ];
             double dvarsdX = ( copy_of_vars[ ( i+1 )*NV + var ] -
                                copy_of_vars[ i*NV + var ] )
                              / ( NODES[ i + 1 ] - NODES[ i ] );
             VARS[ node * NV + var ] =   copy_of_vars[ i * NV + var ]
                                       + dX * dvarsdX;
           }
         }
       }
     }
     // add the last nodal values to the resized vector
     for ( std::size_t var = 0; var < NV; ++var )
     {
       VARS[ ( newX.size() - 1 ) * NV + var ] = copy_of_vars[ ( NODES.size() - 1 )
                                                             * NV + var ];
     }
     NODES = newX;
   }
remesh() [3/4]
template<> void Luna::Mesh1D< std::complex< double >, double >::remesh (const Vector< double > & newX) inline
Definition at line 444 of file Mesh1D.h.
References Luna::Vector< T >::back(), and Luna::Vector< T >::size().
   {
     if ( std::abs( NODES[ 0 ] - newX[ 0 ] ) > 1.e-10 ||
          std::abs( NODES.back() - newX.back() ) > 1.e-10 )
     {
       std::string problem;
       problem = " The Mesh1D.remesh method has been called with a passed\n";
       problem += " coordinate vector that has different start and/or \n";
       problem += " end points from the instantiated object. \n";
       throw Error( problem );
     }
     for ( std::size_t i = 0; i < newX.size() - 1; ++i )
     {
       if ( newX[ i ] >= newX[ i + 1 ] )
       {
         std::string problem;
         problem = " The Mesh1D.remesh method has been passed \n";
         problem += " a non-monotonic coordinate vector. \n";
         throw Error( problem );
       }
     }
     Vector<std::complex<double> > copy_of_vars( VARS );
     VARS.resize( newX.size() * NV );
     for ( std::size_t node = 1; node < newX.size() - 1; ++node )
     {
       // loop through the source mesh and find the bracket-nodes
       for ( std::size_t i = 0; i < NODES.size(); ++i )
       {
         if ( ( NODES[ i ] <= newX[ node ] ) &&
              ( newX[ node ] < NODES[ i + 1 ] ) )
          {
           // linearly interpolate each variable in the mesh
           for ( std::size_t var = 0; var < NV; ++var )
           {
             double dX = newX[ node ] - NODES[ i ];
             // if the paranoid checks above are satisfied, then the X[ i + 1 ] should still be in bounds
             std::complex<double> dvarsdX = ( copy_of_vars[ ( i+1 )*NV + var ] -
                                              copy_of_vars[ i*NV + var ] )
                                             / ( NODES[ i + 1 ] - NODES[ i ] );
             VARS[ node * NV + var ] =   copy_of_vars[ i * NV + var ]
                                       + dX * dvarsdX;
           }
         }
       }
     }
     // add the last nodal values to the resized vector
     for ( std::size_t var = 0; var < NV; ++var )
     {
       VARS[ ( newX.size() - 1 ) * NV + var ] = copy_of_vars[
                                               ( NODES.size() - 1 ) * NV + var ];
     }
     NODES = newX;
   }
remesh() [4/4]
template<> void Luna::Mesh1D< std::complex< double >, std::complex< double > >::remesh (const Vector< std::complex< double >> & z)
Definition at line 501 of file Mesh1D.h.
   {
     std::string problem;
     problem = " The Mesh1D.remesh method has been called with \n";
     problem += " a complex data set on a complex mesh.\n";
     throw Error( problem );
   }
set_nodes_vars()
template<typename T , typename X > void Luna::Mesh1D< T, X >::set_nodes_vars (const std::size_t & node, const Vector< T > & vec) inline
Set the variables stored at a specific node.
Parameters
node Node index
vec Vector of variables
Definition at line 153 of file Mesh1D.h.
References Luna::Vector< T >::size().
Referenced by Luna::Mesh2D< T >::get_cross_section_xnode(), Luna::Mesh2D< T >::get_cross_section_ynode(), and Luna::Mesh1D< T, X >::operator()().
   {
     if ( vec.size() != NV ) { throw Error( "Mesh error: set_nodes_vars " );}
     for ( std::size_t var = 0; var < vec.size(); ++var )
     {
       VARS[ node * NV + var ] = vec[ var ];
     }
   }
set_vars_from_vector()
template<typename T , typename X > void Luna::Mesh1D< T, X >::set_vars_from_vector (const Vector< T > & vec) inline
Set the variables of this mesh from a vector.
Parameters
A Vector of the variables to be stored in the mesh
Definition at line 367 of file Mesh1D.h.
References Luna::Vector< T >::size().
Referenced by Luna::Mesh1D< T, X >::operator()().
   {
     if ( vec.size() != NV * NODES.size() )
     { throw Error( "Mesh1D: set_vars_from_vector sizes do not agree." ); }
     VARS = vec;
   }
vars_as_vector()
template<typename T , typename X > const Vector< T > & Luna::Mesh1D< T, X >::vars_as_vector () const inline
Return a vector of all the variables stored in the mesh.
Returns
A reference to the Vector of the variables stored in the mesh
Definition at line 361 of file Mesh1D.h.
Referenced by Luna::Mesh1D< T, X >::operator()().
   {
     return VARS;
   }
The documentation for this class was generated from the following file:
include/Luna/Mesh1D.h