Luna: Luna::LinearEigensystem< T > Class Template Reference
Luna::LinearEigensystem< T > Class Template Reference
A LinearEigensystem class for use with double and std::complex<double>
#include <LinearEigensystem.h>
Public Member Functions
LinearEigensystem ()
Constructor for a LinearEigensystem.
~LinearEigensystem ()
Destructor.
void compute_real_symmetric (const Matrix< double > &a, bool compute_evecs=true)
Solve a LinearEigensystem A*v=lambda*v where A is a real symmetric Matrix to give the eigenvalues (and optionally the eigenvectors)
void compute_real_symmetric_tridiagonal (const Vector< double > &diag, const Vector< double > &off_diag, bool compute_evecs=true)
Solve a LinearEigensystem A*v=lambda*v where A is a real symmetric tridiagonal Matrix to give the eigenvalues (and optionally the eigenvectors)
void compute_real (const Matrix< double > &a, bool compute_evecs=true)
Solve a LinearEigensystem A*v=lambda*v where A is a real Matrix to give the eigenvalues (and optionally the eigenvectors)
Vector< std::complex< double > > eigenvalues () const
Return the eigenvalues.
Matrix< T > eigenvector_matrix () const
Return a Matrix containing the eigenvectors.
std::vector< Vector< std::complex< double > > > eigenvectors () const
Return an std::vector of eigenvectors.
template<>
void compute_real_symmetric (const Matrix< double > &a, bool compute_evecs)
template<>
void compute_real_symmetric_tridiagonal (const Vector< double > &diag, const Vector< double > &off_diag, bool compute_evecs)
template<>
void compute_real (const Matrix< double > &a, bool compute_evecs)
Detailed Description
template<class T>
class Luna::LinearEigensystem< T >
A LinearEigensystem class for use with double and std::complex<double>
Definition at line 25 of file LinearEigensystem.h.
Constructor & Destructor Documentation
LinearEigensystem()
template<class T> Luna::LinearEigensystem< T >::LinearEigensystem () inline
Constructor for a LinearEigensystem.
Definition at line 45 of file LinearEigensystem.h.
                         : EIGENVALUES_COMPUTED( false ),
                           EIGENVECTORS_COMPUTED( false )
     {}
~LinearEigensystem()
template<class T> Luna::LinearEigensystem< T >::~LinearEigensystem () inline
Destructor.
Definition at line 50 of file LinearEigensystem.h.
References Luna::LinearEigensystem< T >::compute_real(), Luna::LinearEigensystem< T >::compute_real_symmetric(), Luna::LinearEigensystem< T >::compute_real_symmetric_tridiagonal(), Luna::LinearEigensystem< T >::eigenvalues(), Luna::LinearEigensystem< T >::eigenvector_matrix(), Luna::LinearEigensystem< T >::eigenvectors(), Heat_plot::t, Heat_plot::u, ODE_BVP_System_plot::v, Heat_plot::x, and Spectral_ODE_Rational_plot::y.
 {}
Member Function Documentation
compute_real() [1/2]
template<class T> void Luna::LinearEigensystem< T >::compute_real (const Matrix< double > & a, bool compute_evecs = true)
Solve a LinearEigensystem A*v=lambda*v where A is a real Matrix to give the eigenvalues (and optionally the eigenvectors)
Parameters
a The Matrix A in the eigensystem
compute_evecs True if the eigenvectors are to be computed too
Referenced by main(), and Luna::LinearEigensystem< T >::~LinearEigensystem().
compute_real() [2/2]
template<> void Luna::LinearEigensystem< double >::compute_real (const Matrix< double > & a, bool compute_evecs) inline
Definition at line 334 of file LinearEigensystem.h.
References Luna::Matrix< T >::cols(), and Luna::Matrix< T >::rows().
   {
     if ( a.rows() != a.cols() )
     {
       throw Error( "compute_real error: Matrix is not square.");
     }
     A = a;
     N = a.rows();
     balance();
     elmhes();
     if ( compute_evecs ) {
       EIGENVECTORS.resize( N, N );
       EIGENVECTORS.fill( 1.0 );
       eltran();
       hqr2();
       balbak();
       sortvecs();
       EIGENVALUES_COMPUTED = true;
       EIGENVECTORS_COMPUTED = true;
     } else {
       hqr();
       sort_unsymm();
       EIGENVALUES_COMPUTED = true;
     }
   }
compute_real_symmetric() [1/2]
template<class T> void Luna::LinearEigensystem< T >::compute_real_symmetric (const Matrix< double > & a, bool compute_evecs = true)
Solve a LinearEigensystem A*v=lambda*v where A is a real symmetric Matrix to give the eigenvalues (and optionally the eigenvectors)
Parameters
a The Matrix A in the eigensystem
compute_evecs True if the eigenvectors are to be computed
Referenced by main(), and Luna::LinearEigensystem< T >::~LinearEigensystem().
compute_real_symmetric() [2/2]
template<> void Luna::LinearEigensystem< double >::compute_real_symmetric (const Matrix< double > & a, bool compute_evecs) inline
Definition at line 270 of file LinearEigensystem.h.
References Luna::Matrix< T >::cols(), Luna::Vector< T >::resize(), and Luna::Matrix< T >::rows().
   {
     if ( a.rows() != a.cols() )
     {
       throw Error( "compute_real_symmetric error: Matrix is not square.");
     }
     Matrix<double> z( a );
     Vector<double> diag, off_diag;
     tred2( z, diag, off_diag, compute_evecs );
     tqli( z, diag, off_diag, compute_evecs );
     sort( diag, z, compute_evecs );
     std::size_t n( z.rows() );
     EIGENVALUES.resize( n );
     EIGENVECTORS.resize( n, n );
     for ( std::size_t i = 0; i < n; i++ )
     {
       EIGENVALUES[ i ] = diag[ i ];
     }
     EIGENVALUES_COMPUTED = true;
     if ( compute_evecs )
     {
       EIGENVECTORS = z;
       EIGENVECTORS_COMPUTED = true;
     }
   }
compute_real_symmetric_tridiagonal() [1/2]
template<class T> void Luna::LinearEigensystem< T >::compute_real_symmetric_tridiagonal (const Vector< double > & diag, const Vector< double > & off_diag, bool compute_evecs = true)
Solve a LinearEigensystem A*v=lambda*v where A is a real symmetric tridiagonal Matrix to give the eigenvalues (and optionally the eigenvectors)
Parameters
diag The Vector of main diagonal entries in the A Matrix
off_diag The Vector of off-diagonal entries in the A Matrix
compute_evecs True if the eigenvectors are to be computed
Referenced by main(), and Luna::LinearEigensystem< T >::~LinearEigensystem().
compute_real_symmetric_tridiagonal() [2/2]
template<> void Luna::LinearEigensystem< double >::compute_real_symmetric_tridiagonal (const Vector< double > & diag, const Vector< double > & off_diag, bool compute_evecs) inline
Definition at line 299 of file LinearEigensystem.h.
References Luna::Vector< T >::push_front(), Luna::Vector< T >::resize(), and Luna::Vector< T >::size().
   {
     if ( diag.size() != off_diag.size() + 1 )
     {
       std::string problem;
       problem = "compute_real_symmetric_tridiagonal error: ";
       problem += "size of Vectors are incompatible.";
       throw Error( problem );
     }
     std::size_t n( diag.size() );
     Matrix<double> z( n, n, 0.0 );
     z.eye();
     Vector<double> diag_temp( diag ), off_diag_temp( off_diag );
     off_diag_temp.push_front( 0.0 );
     tqli( z, diag_temp, off_diag_temp, compute_evecs );
     sort( diag_temp, z, compute_evecs );
     EIGENVALUES.resize( n );
     EIGENVECTORS.resize( n, n );
     for ( std::size_t i = 0; i < n; i++ )
     {
       EIGENVALUES[ i ] = diag_temp[ i ];
     }
     EIGENVALUES_COMPUTED = true;
     if ( compute_evecs )
     {
       EIGENVECTORS = z;
       EIGENVECTORS_COMPUTED = true;
     }
   }
eigenvalues()
template<typename T > Vector< std::complex< double > > Luna::LinearEigensystem< T >::eigenvalues () const inline
Return the eigenvalues.
Returns
The eigenvalues as a Vector of std::complex<double>
Definition at line 363 of file LinearEigensystem.h.
Referenced by main(), and Luna::LinearEigensystem< T >::~LinearEigensystem().
   {
     if ( EIGENVALUES_COMPUTED ) { return EIGENVALUES; }
     else { throw Error( "Eigensystem: eigenvalues not computed." ); }
   }
eigenvector_matrix()
template<typename T > Matrix< T > Luna::LinearEigensystem< T >::eigenvector_matrix () const inline
Return a Matrix containing the eigenvectors.
Returns
A Matrix where each column is an eigenvector
Definition at line 370 of file LinearEigensystem.h.
Referenced by main(), and Luna::LinearEigensystem< T >::~LinearEigensystem().
   {
     if ( EIGENVECTORS_COMPUTED ) { return EIGENVECTORS; }
     else { throw Error( "Eigensystem: eigenvectors not computed." ); }
   }
eigenvectors()
template<typename T > std::vector< Vector< cmplx > > Luna::LinearEigensystem< T >::eigenvectors () const inline
Return an std::vector of eigenvectors.
Returns
An std::vector<Vector<std::complex<double>>> where each entry in the std::vector is an eigenvector
Definition at line 378 of file LinearEigensystem.h.
References Luna::Vector< T >::assign(), Spectral_ODE_BVP_plot::c, f, Falkner_3D_alternative_plot::g, Luna::Vector< T >::push_back(), Luna::Vector< T >::resize(), Luna::Matrix< T >::rows(), Luna::Vector< T >::size(), Heat_plot::t, Heat_plot::u, ODE_BVP_System_plot::v, Heat_plot::x, and Spectral_ODE_Rational_plot::y.
Referenced by main(), and Luna::LinearEigensystem< T >::~LinearEigensystem().
   {
     if ( EIGENVECTORS_COMPUTED )
     {
       std::vector< Vector< std::complex<double> > > evecs;
       std::size_t rows = EIGENVECTORS.rows();
       std::size_t cols = EIGENVECTORS.cols();
       for (std::size_t j = 0; j < cols; ++j )
       {
           Vector< std::complex<double> > evec;
           for (std::size_t i=0; i<rows; ++i)
           {
               evec.push_back( EIGENVECTORS( i, j ) );
           }
           evecs.push_back( evec );
       }
       return evecs;
     }
     else { throw Error( "Eigensystem: eigenvectors not computed." ); }
   }
The documentation for this class was generated from the following file:
include/Luna/LinearEigensystem.h