Luna: Luna::Timer Class Reference
Luna::Timer Class Reference
A simple timer class for timing methods.
#include <Timer.h>
Public Member Functions
Timer ()
Constructor.
~Timer ()
Destructor.
bool is_started ()
Check if the timer has started.
bool is_stopped ()
Check if the timer is stopped.
bool is_paused ()
Check if the timer is paused.
bool is_active ()
Check if the timer is active.
void pause ()
Pause the timer.
void resume ()
Resume the timer.
void start ()
Start the timer.
void stop ()
Stop the timer.
void reset ()
Reset the timer.
void print () const
Output the time to the screen.
double get_time () const
Return the time in milliseconds.
clock_t get_ticks ()
Return the number of clock ticks.
Detailed Description
A simple timer class for timing methods.
Definition at line 13 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Luna::Timer::Timer () inline
Constructor.
Definition at line 27 of file Timer.h.
                 : START_TIME( 0 ), PAUSED_TIME( 0 ), STARTED( false ), PAUSED( false )
         {}
~Timer()
Luna::Timer::~Timer () inline
Destructor.
Definition at line 31 of file Timer.h.
References get_ticks(), get_time(), is_active(), is_paused(), is_started(), is_stopped(), pause(), print(), reset(), resume(), start(), and stop().
         {}
Member Function Documentation
get_ticks()
clock_t Luna::Timer::get_ticks () inline
Return the number of clock ticks.
Returns
The number of clock ticks
Definition at line 165 of file Timer.h.
Referenced by get_time(), and ~Timer().
     {
         if( !STARTED )
         {
             return 0;
         }
         if( PAUSED )
         {
             return PAUSED_TIME - START_TIME;
         }
         return clock() - START_TIME;
     }
get_time()
double Luna::Timer::get_time () const inline
Return the time in milliseconds.
Returns
The time in ms
Definition at line 159 of file Timer.h.
References get_ticks().
Referenced by main(), print(), and ~Timer().
     {
         Timer temp( *this );
         return 1.e3 * temp.get_ticks() / CLOCKS_PER_SEC;
     }
is_active()
bool Luna::Timer::is_active () inline
Check if the timer is active.
Returns
true if the timer is still active and false otherwise
Definition at line 97 of file Timer.h.
Referenced by ~Timer().
     {
         return !PAUSED & STARTED;
     }
is_paused()
bool Luna::Timer::is_paused () inline
Check if the timer is paused.
Returns
true if the timer is paused and false otherwise
Definition at line 92 of file Timer.h.
Referenced by ~Timer().
     {
         return PAUSED;
     }
is_started()
bool Luna::Timer::is_started () inline
Check if the timer has started.
Returns
true if the time has been started and false otherwise
Definition at line 82 of file Timer.h.
Referenced by ~Timer().
     {
         return STARTED;
     }
is_stopped()
bool Luna::Timer::is_stopped () inline
Check if the timer is stopped.
Returns
true if the timer is stopped and false otherwise
Definition at line 87 of file Timer.h.
Referenced by ~Timer().
     {
         return !STARTED;
     }
pause()
void Luna::Timer::pause () inline
Pause the timer.
Definition at line 102 of file Timer.h.
Referenced by ~Timer().
     {
         if( PAUSED || !STARTED )
         {
             return;
         }
         PAUSED = true;
         PAUSED_TIME = clock();
     }
print()
void Luna::Timer::print () const inline
Output the time to the screen.
Definition at line 144 of file Timer.h.
References get_time().
Referenced by main(), and ~Timer().
     {
         std::cout.precision(4);
         Timer temp( *this );
         const double elapsed_time_in_ms( temp.get_time() );
         if ( elapsed_time_in_ms > 1000 )
         {
           std::cout << "  * TOTAL CPU time taken = " << elapsed_time_in_ms / 1000. << " s\n";
         }
         else
         {
          std::cout << "  * TOTAL CPU time taken = " << elapsed_time_in_ms << " ms\n";
         }
     }
reset()
void Luna::Timer::reset () inline
Reset the timer.
Definition at line 138 of file Timer.h.
Referenced by ~Timer().
     {
         PAUSED = false;
         START_TIME = clock();
     }
resume()
void Luna::Timer::resume () inline
Resume the timer.
Definition at line 112 of file Timer.h.
Referenced by ~Timer().
     {
         if( !PAUSED )
         {
             return;
         }
         PAUSED = false;
         START_TIME += clock() - PAUSED_TIME;
     }
start()
void Luna::Timer::start () inline
Start the timer.
Definition at line 122 of file Timer.h.
Referenced by main(), and ~Timer().
     {
         if( STARTED )
         {
             return;
         }
         STARTED = true;
         PAUSED = false;
         START_TIME = clock();
     }
stop()
void Luna::Timer::stop () inline
Stop the timer.
Definition at line 133 of file Timer.h.
Referenced by main(), and ~Timer().
     {
         STARTED = false;
     }
The documentation for this class was generated from the following file:
include/Luna/Timer.h