Luna: Luna::Newton< T > Class Template Reference
Luna::Newton< T > Class Template Reference
A templated Newton iteration class.
#include <Newton.h>
Public Member Functions
Newton (Residual< T > *ptr_residual, std::size_t max_iter=20, double tolerance=1.0e-8, double delta_step=1.0e-8)
Constructor.
~Newton ()
Destructor.
void iterate (Vector< T > &x_0)
Newton iterate using intial guess x_0 (stores the solution in x_0)
void solve (Vector< T > &x_0)
Solve the system using Newton iteration (points to iterate)
void arclength_solve (Vector< T > &x)
Arc-length solve the system (init_arc must be called first)
Public Member Functions inherited from Luna::Arclength< T >
Arclength ()
Constructor.
virtual ~Arclength ()
Destructor.
void init_arc (Vector< T > x, T *ptr_param, const double &ds, const double &max_ds)
Initialise the arc-length continuation class.
double & ds ()
A handle to the arc-length step.
double & arcstep_multiplier ()
A handle to the arc step multiplier.
bool & rescale_theta ()
A handle to the RESCALE_THETA flag.
double & theta ()
A handle to the theta parameter.
double & desired_arc_proportion ()
A handle to the desired proportion of the parameter to be used.
Protected Attributes
Residual< T > * ptr_RESIDUAL
std::size_t MAX_ITER
double TOL
double DELTA
std::size_t ORDER
Protected Attributes inherited from Luna::Arclength< T >
T * ptr_PARAM
Vector< T > LAST_X
Vector< T > X_DERIV_S
T LAST_PARAM
T PARAM_DERIV_S
double DS
double MAX_DS
double ARCSTEP_MULTIPLIER
bool INITIALISED
double THETA
Additional Inherited Members
Protected Member Functions inherited from Luna::Arclength< T >
void update (const Vector< T > &x)
Store the current converged state and parameter & compute derivatives.
double arclength_residual (const Vector< T > &x) const
Extra constraint that is to be used to replace the unknown arc-length.
Vector< T > Jac_arclength_residual (Vector< T > &x) const
Return the derivative of the arclength_residual function.
void update_theta (const Vector< T > &x)
Automatically update theta value only if RESCALE_THETA = true.
Detailed Description
template<class T>
class Luna::Newton< T >
A templated Newton iteration class.
Definition at line 24 of file Newton.h.
Constructor & Destructor Documentation
Newton()
template<class T> Luna::Newton< T >::Newton (Residual< T > * ptr_residual, std::size_t max_iter = 20, double tolerance = 1.0e-8, double delta_step = 1.0e-8) inline
Constructor.
Parameters
ptr_residual Pointer to the residual object
max_iter Maximum number of iterations
tolerance Convergence tolerance
delta_step Finite-difference derivative step
Definition at line 39 of file Newton.h.
                                                                       :
       ptr_RESIDUAL( ptr_residual ),
       MAX_ITER( max_iter ),
       TOL( tolerance )
       {
         ptr_RESIDUAL -> delta() = delta_step;
         DELTA = delta_step;
         ORDER = ptr_RESIDUAL -> get_order();
       }
~Newton()
template<class T> Luna::Newton< T >::~Newton () inline
Destructor.
Definition at line 51 of file Newton.h.
References Luna::Newton< T >::iterate().
 {}
Member Function Documentation
arclength_solve()
template<typename T > void Luna::Newton< T >::arclength_solve (Vector< T > & x) inline
Arc-length solve the system (init_arc must be called first)
Parameters
x The current state Vector
Definition at line 107 of file Newton.h.
References Luna::Arclength< T >::arclength_residual(), Luna::Arclength< T >::ARCSTEP_MULTIPLIER, Luna::Newton< T >::DELTA, Luna::Vector< T >::dot(), Luna::Arclength< T >::DS, Luna::Arclength< T >::INITIALISED, Heat_plot::J, Luna::Arclength< T >::Jac_arclength_residual(), Luna::Arclength< T >::LAST_PARAM, Luna::Arclength< T >::LAST_X, Luna::Arclength< T >::MAX_DS, Luna::Newton< T >::MAX_ITER, Luna::Vector< T >::norm_inf(), Luna::Newton< T >::ORDER, Luna::Arclength< T >::PARAM_DERIV_S, Luna::Arclength< T >::ptr_PARAM, Luna::Newton< T >::ptr_RESIDUAL, Luna::Matrix< T >::solve(), Luna::Newton< T >::TOL, Luna::Arclength< T >::update(), Luna::Arclength< T >::X_DERIV_S, and Spectral_ODE_Rational_plot::y.
Referenced by main(), and Luna::Newton< T >::solve().
     {
         if ( !this->INITIALISED ) // Error if init_arc has not been called
         {
             throw Error( "Newton arclength_solve error: not initialised." );
         }
         Vector<T> backup_state( x );
         T backup_parameter( *(this->ptr_PARAM) );
         bool step_succeeded( false );
         std::size_t itn( 0 );
         // Guess the next solution
         *( this->ptr_PARAM ) = this->LAST_PARAM + this->PARAM_DERIV_S * this->DS;
         x = this->LAST_X + this->X_DERIV_S * this->DS;
         Matrix<T> J( ORDER, ORDER, 0.0 );
         Vector<T> R1( ORDER, 0.0 );
         Vector<T> R2( ORDER, 0.0 );
         Vector<T> dR_dp( ORDER, 0.0 );
         Vector<T> y( ORDER, 0.0 );
         Vector<T> z( ORDER, 0.0 );
         Vector<T> JacE;
         do
         {
             this->ptr_RESIDUAL -> update( x );              // Update the residual
             J = this->ptr_RESIDUAL -> jacobian();           // Get the Jacobian
             R1 = this->ptr_RESIDUAL -> residual();          // Get the residual
             double E1 = this -> arclength_residual( x );    // Arclength residual
             // Compute derivatives wrt the parameter
             *(this->ptr_PARAM) += this->DELTA;
             this->ptr_RESIDUAL -> residual_fn( x, R2 );
             double E2 = this -> arclength_residual( x );
             *(this->ptr_PARAM) -= this->DELTA;
             dR_dp = ( R2 - R1 ) / this->DELTA;
             T dE_dp = ( E2 - E1 ) / this->DELTA;
             // Bordering algorithm
             y = J.solve( -R1 );
             z = J.solve( -dR_dp );
             JacE = this->Jac_arclength_residual( x );
             T delta_p = -( E1 + JacE.dot( y ) ) / ( dE_dp + JacE.dot( z ) );
             Vector<T> delta_x = y + z * delta_p;
             double max_correction = std::max( delta_x.norm_inf(),
                                                                                 std::abs( delta_p ) );
             if ( max_correction < this->TOL )
             {
                 step_succeeded = true;
                 break;
             }
             // Add the corrections to the state variables
             x += delta_x;
             *(this->ptr_PARAM) += delta_p;
             ++itn;
             if ( itn > MAX_ITER )
             {
                 step_succeeded = false;
                 break;
             }
         }while( true );
         if ( !step_succeeded )
         {
             x = backup_state;                               // Restore state
             *(this->ptr_PARAM) = backup_parameter;          // Restore the parameter
             this->ptr_RESIDUAL->update( x );                // Restore the residual
             this->DS /= this->ARCSTEP_MULTIPLIER;           // Reduce our step length
         }
         else
         {
             this->update( x );
             if ( itn >= 7 )                                 // Converging to slowly
             {
                 this->DS /= this->ARCSTEP_MULTIPLIER;
             }
             if ( itn <= 2 )                                 // Converging to quickly
             {
                 if ( std::abs( this->DS * this->ARCSTEP_MULTIPLIER ) < this->MAX_DS )
                 {
                     this->DS *= this->ARCSTEP_MULTIPLIER;
                 }
             }
         }
     }
iterate()
template<typename T > void Luna::Newton< T >::iterate (Vector< T > & x_0) inline
Newton iterate using intial guess x_0 (stores the solution in x_0)
Parameters
x_0 The initial guess
Definition at line 73 of file Newton.h.
References Heat_plot::J, Luna::Newton< T >::MAX_ITER, Luna::Vector< T >::norm_inf(), Luna::Newton< T >::ORDER, Luna::Newton< T >::ptr_RESIDUAL, Luna::Vector< T >::size(), Luna::Matrix< T >::solve(), Luna::Newton< T >::TOL, and Luna::Arclength< T >::update().
Referenced by Luna::Newton< T >::solve(), and Luna::Newton< T >::~Newton().
     {
         //TODO determinant monitoring etc
         if ( x_0.size() != ORDER )
         {
             throw Error( "Newton error: size does not agree." );
         }
         Vector<T> F( ORDER, 0.0 );               // Residual function evaluation
         Matrix<T> J( ORDER, ORDER, 0.0 );        // Jacobian matrix
         Vector<T> dx( ORDER, 0.0 );              // Increment vector
         std::size_t iter( 0 );
         double max_residual;
         do
         {
             ++iter;
             ptr_RESIDUAL -> update( x_0 );
             F = ptr_RESIDUAL -> residual();
             max_residual = F.norm_inf();
             J = ptr_RESIDUAL -> jacobian();
             dx = J.solve( -F );
             x_0 += dx;
         }while( iter < MAX_ITER && max_residual > TOL );
         if ( iter == MAX_ITER )
         {
             std::string warning;
             warning = "NEWTON WARNING! MAXIMUM NUMBER OF ITERATIONS REACHED.";
             std::cout << warning << std::endl;
         }
     }
solve()
template<class T> void Luna::Newton< T >::solve (Vector< T > & x_0) inline virtual
Solve the system using Newton iteration (points to iterate)
Parameters
x_0 The initial guess
Implements Luna::Arclength< T >.
Definition at line 61 of file Newton.h.
References Luna::Newton< T >::arclength_solve(), Luna::Newton< T >::iterate(), and Heat_plot::x.
Referenced by main().
       {
         iterate( x_0 );
       }
Member Data Documentation
DELTA
template<class T> double Luna::Newton< T >::DELTA protected
Definition at line 30 of file Newton.h.
Referenced by Luna::Newton< T >::arclength_solve().
MAX_ITER
template<class T> std::size_t Luna::Newton< T >::MAX_ITER protected
Definition at line 28 of file Newton.h.
Referenced by Luna::Newton< T >::arclength_solve(), and Luna::Newton< T >::iterate().
ORDER
template<class T> std::size_t Luna::Newton< T >::ORDER protected
Definition at line 31 of file Newton.h.
Referenced by Luna::Newton< T >::arclength_solve(), and Luna::Newton< T >::iterate().
ptr_RESIDUAL
template<class T> Residual<T>* Luna::Newton< T >::ptr_RESIDUAL protected
Definition at line 27 of file Newton.h.
Referenced by Luna::Newton< T >::arclength_solve(), and Luna::Newton< T >::iterate().
TOL
template<class T> double Luna::Newton< T >::TOL protected
Definition at line 29 of file Newton.h.
Referenced by Luna::Newton< T >::arclength_solve(), and Luna::Newton< T >::iterate().
The documentation for this class was generated from the following file:
include/Luna/Newton.h