Luna: Luna::Basis< T > Class Template Reference
Luna::Basis< T > Class Template Reference
A templated base class to be inherited by spectral basis objects.
#include <Basis.h>
Public Member Functions
Basis ()
Constructor.
virtual ~Basis ()
Destructor (virtual since we have virtual functions)
virtual T operator() (const T &x, const std::size_t &n)
Evaluation operator for the nth basis function at point x.
virtual Vector< T > operator() (const Vector< T > &x, const std::size_t &n)
Evaluation operator for the nth basis function at a Vector of points.
virtual T operator() (const T &x, const std::size_t &n, const std::size_t &d)
Evaluation operator for the dth derivative of the nth basis function at point x.
virtual Vector< T > operator() (const Vector< T > &x, const std::size_t &n, const std::size_t &d)
Evaluation operator for the dth derivative of the nth basis function at a Vector of points.
Basis< T > & operator= (const Basis< T > &original)
Copy assignment.
void set_identifier (std::string identifier)
Set the basis function identification string.
std::string get_identifier ()
Get the basis function identification string.
Detailed Description
template<class T>
class Luna::Basis< T >
A templated base class to be inherited by spectral basis objects.
Definition at line 21 of file Basis.h.
Constructor & Destructor Documentation
Basis()
template<typename T > Luna::Basis< T >::Basis ()
Constructor.
Definition at line 91 of file Basis.h.
     {
         IDENTIFIER = "Unspecified";
     }
~Basis()
template<typename T > Luna::Basis< T >::~Basis () virtual
Destructor (virtual since we have virtual functions)
Definition at line 97 of file Basis.h.
     {}
Member Function Documentation
get_identifier()
template<class T> std::string Luna::Basis< T >::get_identifier () inline
Get the basis function identification string.
Definition at line 83 of file Basis.h.
             {
                 return IDENTIFIER;
             }
operator()() [1/4]
template<typename T > T Luna::Basis< T >::operator() (const T & x, const std::size_t & n) virtual
Evaluation operator for the nth basis function at point x.
Parameters
x The collocation point where the basis function is evaluated
n The degree of the basis function
Returns
The value of the nth degree basis function at the point x
Definition at line 101 of file Basis.h.
     {
         std::string problem;
         problem += " The Basis function operator () has not been overloaded in \n";
         problem += " the derived class. \n";
         throw Error( problem );
     }
operator()() [2/4]
template<typename T > Vector< T > Luna::Basis< T >::operator() (const Vector< T > & x, const std::size_t & n) virtual
Evaluation operator for the nth basis function at a Vector of points.
Parameters
x A Vector of points where the basis function is evaluated
n The degree of the basis function
Returns
A Vector of values of the nth degree basis function
Definition at line 110 of file Basis.h.
     {
         std::string problem;
         problem += " The Basis function Vector operator () has not been\n";
         problem += " overloaded in the derived class. \n";
         throw Error( problem );
     }
operator()() [3/4]
template<typename T > T Luna::Basis< T >::operator() (const T & x, const std::size_t & n, const std::size_t & d) virtual
Evaluation operator for the dth derivative of the nth basis function at point x.
Parameters
x The collocation point where the basis function is evaluated
n The degree of the basis function
d The derivative to return
Returns
The dth derivative of the nth degree basis function at the point x
Definition at line 119 of file Basis.h.
     {
         std::string problem;
         problem += " The Basis function derivative operator () has not been \n";
         problem += " overloaded in the derived class. \n";
         throw Error( problem );
     }
operator()() [4/4]
template<typename T > Vector< T > Luna::Basis< T >::operator() (const Vector< T > & x, const std::size_t & n, const std::size_t & d) virtual
Evaluation operator for the dth derivative of the nth basis function at a Vector of points.
Parameters
x A Vector of points where the basis function is evaluated
n The degree of the basis function
d The derivative to return
Returns
A Vector of the dth derivative of the nth degree basis function at the Vector of points
Definition at line 129 of file Basis.h.
     {
         std::string problem;
         problem += " The Basis function Vector derivative operator () has not \n";
         problem += " been overloaded in the derived class. \n";
         throw Error( problem );
     }
operator=()
template<typename T > Basis< T > & Luna::Basis< T >::operator= (const Basis< T > & original)
Copy assignment.
Parameters
original Basis function to be copied
Returns
The new Basis function
Definition at line 139 of file Basis.h.
     {
         if ( this == &original ){ return *this; }
     IDENTIFIER = original.IDENTIFIER;
     return *this;
     }
set_identifier()
template<class T> void Luna::Basis< T >::set_identifier (std::string identifier) inline
Set the basis function identification string.
Parameters
identifier The identifier string specifying a type of basis
Definition at line 77 of file Basis.h.
Referenced by Luna::Chebyshev< T >::Chebyshev(), Luna::Chebyshev< T >::operator=(), Luna::RationalSemi< T >::operator=(), and Luna::RationalSemi< T >::RationalSemi().
             {
                 IDENTIFIER = identifier;
             }
The documentation for this class was generated from the following file:
include/Luna/Basis.h