Luna: Luna::Matrix< T > Class Template Reference
Luna::Matrix< T > Class Template Reference
A Matrix class for use with double and std::complex<double>
#include <Matrix.h>
Public Member Functions
Matrix ()
Constructor for an empty Matrix of unspecified size.
Matrix (const std::size_t &rows, const std::size_t &cols, const T &elem)
Constructor for a matrix with specfied initial elements.
Matrix (const Matrix< T > &source)
Copy constructor.
~Matrix ()
Destructor.
const T & operator() (const std::size_t &i, const std::size_t &j) const
Indexing operator (read only)
T & operator() (const std::size_t &i, const std::size_t &j)
Indexing operator (read / write)
Matrix< T > & operator= (const Matrix< T > &original)
Copy assignment.
Matrix< T > operator+ () const
Unary +.
Matrix< T > operator- () const
Unary -.
Matrix< T > operator+ (const Matrix< T > &m_plus) const
Binary +.
Matrix< T > operator- (const Matrix< T > &m_minus) const
Binary -.
Matrix< T > operator* (const T &scalar) const
Scalar multiplication.
Matrix< T > operator/ (const T &divisor) const
Scalar division.
Matrix< T > & operator+= (const Matrix< T > &m_plus)
Addition assignment.
Matrix< T > & operator-= (const Matrix< T > &m_minus)
Subtraction assignment.
Matrix< T > & operator*= (const T &scalar)
Scalar multiplication assignment.
Matrix< T > & operator/= (const T &divisor)
Scalar division assigment.
Matrix< T > & operator+= (const T &add)
Constant addition assignment.
Matrix< T > & operator-= (const T &minus)
Constant subtraction assignment.
const Vector< T > & operator[] (const std::size_t &i) const
Operator overloading for row access (read only)
Vector< T > & operator[] (const std::size_t &i)
Operator overloading for row access (read / write)
Matrix< T > operator* (Matrix< T > &B)
Matrix multiplication.
Vector< T > operator* (Vector< T > &x)
Matrix Vector multiplication.
Matrix< T > multiply (Matrix< T > &B)
Matrix Vector multiplication.
Vector< T > multiply (const Vector< T > &x)
Matrix Vector multiplication.
std::size_t rows () const
Return the number of rows in the Matrix.
std::size_t cols () const
Return the number of columns in the Matrix.
std::size_t numel () const
Return the number of elements in the Matrix.
void set_row (const std::size_t &row, Vector< T > &vec)
Set a row of the Matrix using a Vector.
void set_col (const std::size_t &col, const Vector< T > &vec)
Set a column of the Matrix using a Vector.
Vector< T > get_row (const std::size_t &row)
Get a row of the Matrix as a Vector (wrap [] operator)
Vector< T > get_col (const std::size_t &col)
Get a column of the Matrix as a Vector.
Matrix< T > transpose () const
Return the transpose of the Matrix.
void transpose_in_place ()
Replace the current Matrix with its transpose.
Matrix< T > conjugate () const
Take the complex conjugate of each element of the Matrix.
Matrix< T > conjugate_transpose () const
Transpose of the Matrix along with the complex conjugate of each entry.
void resize (const std::size_t &rows, const std::size_t &cols)
Resize the Matrix while (empty entries are appended if necessary)
void swap_rows (const std::size_t &i, const std::size_t &j)
Swap two rows of the Matrix.
void swap_elem (const std::size_t &i_1, const std::size_t &j_1, const std::size_t &i_2, const std::size_t &j_2)
Swap two elements of the Matrix.
void fill (const T &elem)
Fill the Matrix with specified elements.
void fill_diag (const T &elem)
Fill the leading diagonal of the Matrix with specified elements.
void fill_band (const std::size_t &offset, const T &elem)
Fill a diagonal band of the Matrix.
void fill_tridiag (const T &lower, const T &diag, const T &upper)
Fill the main three diagonals of the Matrix.
void random ()
Fill the Matrix with random elements (between -1 and 1)
void eye ()
Set the Matrix to be the identity Matrix.
Matrix< double > real () const
Real part of the elements of the Matrix.
Matrix< double > imag () const
Imaginary part of the elements of the Matrix.
double norm_1 () const
The Matrix one-norm.
double norm_inf () const
The Matrix infinity-norm.
double norm_p (const double &p) const
The Matrix p-norm (p=2 is Frobenius, p=inf is max norm)
double norm_frob () const
The Matrix Frobenius norm.
double norm_max () const
The Matrix max-norm.
Vector< T > solve_basic (const Vector< T > &b)
Solve the system of equations Ax=b where x and b are Vectors.
Matrix< T > solve_basic (const Matrix< T > &B)
Solve the system of equations AX=B where X and B are Matrices.
void LU_decomp (Matrix< T > &L, Matrix< T > &U, Matrix< T > &P)
LU decomposition of the Matrix (with partial pivotting)
Vector< T > solve_LU (const Vector< T > &b)
Solve the system of equations Ax=b where x and b are Vectors using LU decomposition.
Matrix< T > solve_LU (const Matrix< T > &B)
Solve the system of equations AX=B where X and B are Matrices using LU decomposition.
Vector< T > solve (const Vector< T > &b)
Solve the system of equations Ax=b where x and b are Vectors.
Matrix< T > solve (const Matrix< T > &B)
Solve the system of equations AX=B where X and B are Matrices.
void QR_decomp (Matrix< T > &QT, Matrix< T > &R)
QR decomposition of the Matrix A = QR.
Vector< T > solve_QR (const Vector< T > &b)
Solve the system of equations Ax=b where x and b are Vectors using QR decomposition.
T det ()
Calculate the determinant of the Matrix (via LU decomposition)
Matrix< T > inverse ()
Calculate the inverse of the Matrix (via LU decomposition)
template<>
void random ()
template<>
void random ()
Friends
template<class Type >
std::ostream & operator<< (std::ostream &os, const Matrix< Type > &m)
Output operator <<.
Matrix< T > operator* (const T &scalar, Matrix< T > &mat)
Detailed Description
template<class T>
class Luna::Matrix< T >
A Matrix class for use with double and std::complex<double>
Definition at line 25 of file Matrix.h.
Constructor & Destructor Documentation
Matrix() [1/3]
template<class T> Luna::Matrix< T >::Matrix () inline
Constructor for an empty Matrix of unspecified size.
Definition at line 115 of file Matrix.h.
Referenced by Luna::Matrix< double >::Matrix().
 : ROWS( 0 ), COLS( 0 ) {}
Matrix() [2/3]
template<typename T> Luna::Matrix< T >::Matrix (const std::size_t & rows, const std::size_t & cols, const T & elem) inline
Constructor for a matrix with specfied initial elements.
Parameters
rows The number of rows in the matrix.
cols The number of columns in the matrix.
elem The entry to be placed in all elements.
Definition at line 441 of file Matrix.h.
                                             : ROWS( rows ), COLS( cols )
   {
     const Vector<T> row( cols, elem );
     MATRIX.reserve( rows );
     for ( std::size_t i = 0; i < rows; ++i )
     {
       MATRIX.push_back( row );
     }
   }
Matrix() [3/3]
template<typename T> Luna::Matrix< T >::Matrix (const Matrix< T > & source) inline
Copy constructor.
Parameters
source The source Matrix to be copied
Definition at line 453 of file Matrix.h.
   {
     *this = source;
   }
~Matrix()
template<class T> Luna::Matrix< T >::~Matrix () inline
Destructor.
Definition at line 128 of file Matrix.h.
 {}
Member Function Documentation
cols()
template<typename T > std::size_t Luna::Matrix< T >::cols () const inline
Return the number of columns in the Matrix.
Returns
The number of columns in the Matrix
Definition at line 696 of file Matrix.h.
Referenced by Luna::BandedMatrix< T >::BandedMatrix(), Luna::LinearEigensystem< T >::compute_real(), Luna::LinearEigensystem< T >::compute_real_symmetric(), Luna::Matrix< double >::Matrix(), Luna::Matrix< double >::multiply(), Luna::Matrix< double >::operator+(), Luna::Matrix< double >::operator+=(), Luna::Matrix< double >::operator-(), Luna::Matrix< double >::operator-=(), Luna::BandedMatrix< T >::solve(), and Luna::Tridiagonal< T >::solve().
   {
     return COLS;
   }
conjugate()
template<typename T > Matrix< T > Luna::Matrix< T >::conjugate () const inline
Take the complex conjugate of each element of the Matrix.
Returns
The complex conjugate Matrix
Definition at line 794 of file Matrix.h.
Referenced by Luna::Matrix< double >::conjugate_transpose().
   {
      Matrix<T> temp( *this );
      for ( std::size_t i = 0; i < ROWS; ++i )
      {
        temp.MATRIX[ i ] = temp.MATRIX[ i ].conjugate();
      }
      return temp;
   }
conjugate_transpose()
template<typename T > Matrix< T > Luna::Matrix< T >::conjugate_transpose () const inline
Transpose of the Matrix along with the complex conjugate of each entry.
Returns
The conjugate transpose Matrix
Definition at line 805 of file Matrix.h.
   {
     Matrix<T> temp( *this );
     temp.transpose_in_place();
     return temp.conjugate();
   }
det()
template<typename T > T Luna::Matrix< T >::det () inline
Calculate the determinant of the Matrix (via LU decomposition)
Returns
The determinant of the Matrix
Definition at line 1297 of file Matrix.h.
Referenced by main(), and Luna::Matrix< double >::solve().
   {
     T det( 1 );
     Matrix<T> temp( *this );
     Matrix<T> P;
     std::size_t pivots;
     pivots = temp.LU_decomp_in_place( P );
     for ( std::size_t i = 0; i < ROWS; i++ )
     {
       det *= temp.MATRIX[ i ][ i ];
     }
     if ( pivots % 2 == 0 )
     {
       return det;
     }
     else
     {
       return - det;
     }
   }
eye()
template<typename T > void Luna::Matrix< T >::eye () inline
Set the Matrix to be the identity Matrix.
Definition at line 951 of file Matrix.h.
Referenced by Luna::Example::test_equation::matrix0(), and Luna::Matrix< double >::QR_decomp().
   {
     this->fill( 0.0 );
     this->fill_diag( 1.0 );
   }
fill()
template<typename T> void Luna::Matrix< T >::fill (const T & elem) inline
Fill the Matrix with specified elements.
Parameters
elem The element to fill the Matrix with
Definition at line 864 of file Matrix.h.
Referenced by Luna::Matrix< double >::inverse(), and Luna::Matrix< double >::LU_decomp().
   {
     for ( std::size_t i = 0; i < ROWS; ++i )
     {
       for ( std::size_t j = 0; j < COLS; ++j )
       {
         MATRIX[ i ][ j ] = elem;
       }
     }
   }
fill_band()
template<typename T> void Luna::Matrix< T >::fill_band (const std::size_t & offset, const T & elem) inline
Fill a diagonal band of the Matrix.
Parameters
offset The offset from the leading diagonal (+ above, - below)
elem The element to fill the diagonal band with
Definition at line 887 of file Matrix.h.
Referenced by main().
   {
     for ( std::size_t row = 0; row < ROWS; ++row )
     {
         if ( ( row + offset < COLS ) && ( row + offset >= 0 ) )
         {
             MATRIX[ row ][ row + offset ] = elem;
         }
     }
   }
fill_diag()
template<typename T> void Luna::Matrix< T >::fill_diag (const T & elem) inline
Fill the leading diagonal of the Matrix with specified elements.
Parameters
elem The element to fill the leading diagonal with
Definition at line 876 of file Matrix.h.
Referenced by Luna::Matrix< double >::inverse().
   {
     std::size_t N( ROWS );
     if ( COLS < ROWS ) { N = COLS; }
     for ( std::size_t i = 0; i < N ; ++i )
     {
       MATRIX[ i ][ i ] = elem;
     }
   }
fill_tridiag()
template<typename T> void Luna::Matrix< T >::fill_tridiag (const T & lower, const T & diag, const T & upper) inline
Fill the main three diagonals of the Matrix.
Parameters
lower The element to fill the lower band
diag The element to fill the main diagonal
upper The element to fill the upper band
Definition at line 899 of file Matrix.h.
   {
     fill_band( -1, lower );
     fill_diag( diag );
     fill_band( 1, upper );
   }
get_col()
template<typename T > Vector< T > Luna::Matrix< T >::get_col (const std::size_t & col) inline
Get a column of the Matrix as a Vector.
Parameters
col The column index
Returns
A Vector of the column of the Matrix
Definition at line 740 of file Matrix.h.
Referenced by Luna::Matrix< double >::multiply(), Luna::BandedMatrix< T >::solve(), Luna::Tridiagonal< T >::solve(), and Luna::Matrix< double >::solve_basic().
   {
     if ( col < 0 || COLS <= col ){
       throw Error( "Range error in get_col method." );
     }
     Vector<T> temp( ROWS, 0.0 );
     for ( std::size_t row = 0; row < ROWS; ++row )
     {
       temp[ row ] = MATRIX[ row ][ col ];
     }
     return temp;
   }
get_row()
template<typename T > Vector< T > Luna::Matrix< T >::get_row (const std::size_t & row) inline
Get a row of the Matrix as a Vector (wrap [] operator)
Parameters
row The row index
Returns
A Vector of the row of the Matrix
Definition at line 729 of file Matrix.h.
   {
     if ( row < 0 || ROWS <= row ){
       throw Error( "Range error in get_row method." );
     }
     Vector<T> temp;
     temp = MATRIX[ row ];
     return temp;
   }
imag()
template<typename T > Matrix< double > Luna::Matrix< T >::imag () const inline
Imaginary part of the elements of the Matrix.
Returns
Matrix of imaginary parts of the elements
Definition at line 970 of file Matrix.h.
   {
     Matrix<double> imag_part( ROWS, COLS, 0.0 );
     for (size_t i = 0; i < ROWS; ++i )
     {
       for (size_t j = 0; j < COLS; ++j )
       imag_part( i, j ) = std::imag( MATRIX[ i ][ j ] ) ;
     }
     return imag_part;
   }
inverse()
template<typename T > Matrix< T > Luna::Matrix< T >::inverse () inline
Calculate the inverse of the Matrix (via LU decomposition)
Returns
The inverse Matrix
Definition at line 1321 of file Matrix.h.
Referenced by main(), and Luna::Matrix< double >::solve().
   {
     if ( ROWS != COLS )
     {
       throw Error( "Matrix inverse error: Matrix is not square.");
     }
     Matrix<T> inv;
     Matrix<T> LU( *this );
     std::size_t pivots;
     pivots = LU.LU_decomp_in_place( inv );
     for ( int j = 0; j < ROWS; j++ )
     {
         for ( int i = 0; i < ROWS; i++ )
         {
             for ( int k = 0; k < i; k++ )
             {
                 inv.MATRIX[ i ][ j ] -= LU.MATRIX[ i ][ k ]
                                       * inv.MATRIX[ k ][ j ];
             }
         }
         for (int i = ROWS - 1; i >= 0; i--)
         {
             for (int k = i + 1; k < ROWS; k++)
             {
                 inv.MATRIX[ i ][ j ] -= LU.MATRIX[ i ][ k ]
                                       * inv.MATRIX[ k ][ j ];
             }
             inv.MATRIX[ i ][ j ] = inv.MATRIX[ i ][ j ] / LU.MATRIX[ i ][ i ];
         }
     }
     return inv;
   }
LU_decomp()
template<typename T> void Luna::Matrix< T >::LU_decomp (Matrix< T > & L, Matrix< T > & U, Matrix< T > & P) inline
LU decomposition of the Matrix (with partial pivotting)
Parameters
L The lower triangular Matrix
U The upper triangular Matrix
P The permutation Matrix
Definition at line 1096 of file Matrix.h.
Referenced by main().
   {
     if ( ROWS != COLS )
     {
       throw Error( "LU_decomp error: Matrix is not square.");
     }
     Matrix<T> temp( *this );
     std::size_t pivots;
     pivots = temp.LU_decomp_in_place( P );
     L.resize( ROWS, ROWS );
     L.fill( 0 );
     U.resize( ROWS, ROWS );
     U.fill( 0 );
     for ( std::size_t i = 0; i < ROWS; i++ )
     {
       for ( std::size_t j = 0; j < ROWS; j++ )
       {
         if ( i < j )
         {
           U( i, j ) = temp( i, j );
         }
         else if ( i == j )
         {
           L( i, j ) = 1;
           U( i, j ) = temp( i, j );
         }
         else
         {
           L( i, j ) = temp( i, j );
         }
       }
     }
   }
multiply() [1/2]
template<typename T> Matrix< T > Luna::Matrix< T >::multiply (Matrix< T > & B) inline
Matrix Vector multiplication.
Parameters
x The Vector which is to be multiplied
Returns
The result vector A * x Matrix multiplication
Parameters
B The Matrix which is to be multiplied
Returns
The result Matrix A * B
Definition at line 659 of file Matrix.h.
Referenced by Luna::Matrix< double >::solve_QR().
   {
     if ( B.rows() != COLS )
     {
       throw Error( "Matrix dimensions do not agree in multiply method." );
     }
     Matrix<T> temp( ROWS, B.cols(), 0.0 );
     for ( std::size_t col = 0; col < B.cols(); ++col )
     {
       temp.set_col( col, multiply( B.get_col( col ) ) );
     }
     return temp;
   }
multiply() [2/2]
template<typename T> Vector< T > Luna::Matrix< T >::multiply (const Vector< T > & x) inline
Matrix Vector multiplication.
Parameters
x The vector which is to be multiplied
Returns
The result vector A * x
Definition at line 674 of file Matrix.h.
   {
     if ( x.size() != COLS )
     {
       throw Error( "Dimensions do not agree in Matrix multiply method." );
     }
     Vector<T> temp;
     temp.reserve( ROWS );
     for ( std::size_t row = 0; row < ROWS; ++row )
     {
       temp.push_back( MATRIX[ row ].dot( x ) );
     }
     return temp;
   }
norm_1()
template<typename T > double Luna::Matrix< T >::norm_1 () const inline
The Matrix one-norm.
Returns
The maximum absolute column sum of the Matrix
Definition at line 984 of file Matrix.h.
   {
     double max( 0.0 );
     for ( std::size_t j = 0; j < COLS; ++j )
     {
         double sum( 0.0 );
         for ( std::size_t i = 0; i < ROWS; ++i )
         {
             sum += std::abs( MATRIX[ i ][ j ] );
         }
         max = std::max( max, sum );
     }
     return max;
   }
norm_frob()
template<typename T > double Luna::Matrix< T >::norm_frob () const inline
The Matrix Frobenius norm.
Returns
The Frobenius norm of the Matrix
Definition at line 1030 of file Matrix.h.
   {
     return this->norm_p( 2.0 );
   }
norm_inf()
template<typename T > double Luna::Matrix< T >::norm_inf () const inline
The Matrix infinity-norm.
Returns
The maximum absolute row sum of the Matrix
Definition at line 1000 of file Matrix.h.
   {
     double max( 0.0 );
     for ( std::size_t i = 0; i < ROWS; ++i )
     {
         double sum( 0.0 );
         for ( std::size_t j = 0; j < COLS; ++j )
         {
             sum += std::abs( MATRIX[ i ][ j ] );
         }
         max = std::max( max, sum );
     }
     return max;
   }
norm_max()
template<typename T > double Luna::Matrix< T >::norm_max () const inline
The Matrix max-norm.
Returns
The entrywise max-norm of the Matrix
Definition at line 1036 of file Matrix.h.
   {
     double max( 0.0 );
     for ( std::size_t i = 0; i < ROWS; ++i )
     {
         for ( std::size_t j = 0; j < COLS; ++j )
         {
             max = std::max( max, std::abs( MATRIX[ i ][ j ] ) );
         }
     }
     return max;
   }
norm_p()
template<typename T > double Luna::Matrix< T >::norm_p (const double & p) const inline
The Matrix p-norm (p=2 is Frobenius, p=inf is max norm)
Parameters
p The exponent for the p-norm
Returns
The entrywise p-norm of the Matrix
Definition at line 1016 of file Matrix.h.
   {
     double sum( 0.0 );
     for ( std::size_t i = 0; i < ROWS; ++i )
     {
         for ( std::size_t j = 0; j < COLS; ++j )
         {
             sum += std::pow( std::abs( MATRIX[ i ][ j ] ), p );
         }
     }
     return std::pow( sum , 1.0/p );
   }
numel()
template<typename T > std::size_t Luna::Matrix< T >::numel () const inline
Return the number of elements in the Matrix.
Returns
The number of elements in the Matrix
Definition at line 702 of file Matrix.h.
   {
     return ROWS * COLS;
   }
operator()() [1/2]
template<typename T > const T & Luna::Matrix< T >::operator() (const std::size_t & i, const std::size_t & j) const inline
Indexing operator (read only)
Parameters
i Row index
j Column index
Definition at line 475 of file Matrix.h.
Referenced by Luna::Matrix< double >::~Matrix().
   {
     if ( i<0 || ROWS<=i )   { throw Error( "Matrix range error: dimension 1." );}
     if ( j<0 || COLS<=j )   { throw Error( "Matrix range error: dimension 2." );}
     return MATRIX[ i ][ j ];
   }
operator()() [2/2]
template<typename T > T & Luna::Matrix< T >::operator() (const std::size_t & i, const std::size_t & j) inline
Indexing operator (read / write)
Parameters
i Row index
j Column index
Definition at line 484 of file Matrix.h.
   {
     if ( i<0 || ROWS<=i )   { throw Error( "Matrix range error: dimension 1." );}
     if ( j<0 || COLS<=j )   { throw Error( "Matrix range error: dimension 2." );}
     return MATRIX[ i ][ j ];
   }
operator*() [1/3]
template<typename T> Matrix< T > Luna::Matrix< T >::operator* (const T & scalar) const inline
Scalar multiplication.
Parameters
scalar The scalar to multiply the Matrix by
Returns
The Matrix multiplied by the scalar
Definition at line 548 of file Matrix.h.
Referenced by Luna::Matrix< double >::~Matrix().
   {
     Matrix<T> temp( *this );
     std::transform ( temp.MATRIX.begin(), temp.MATRIX.end(),
                      temp.MATRIX.begin(), scale_vector<T>( scalar ) );
     return temp;
   }
operator*() [2/3]
template<typename T> Matrix< T > Luna::Matrix< T >::operator* (Matrix< T > & B) inline
Matrix multiplication.
Parameters
B The Matrix which is to be multiplied
Returns
The result Matrix A * B
Definition at line 645 of file Matrix.h.
   {
     return multiply( B );
   }
operator*() [3/3]
template<typename T> Vector< T > Luna::Matrix< T >::operator* (Vector< T > & x) inline
Matrix Vector multiplication.
Parameters
x The Vector which is to be multiplied
Returns
The result vector A * x
Definition at line 651 of file Matrix.h.
   {
     return multiply( x );
   }
operator*=()
template<typename T> Matrix< T > & Luna::Matrix< T >::operator*= (const T & scalar) inline
Scalar multiplication assignment.
Parameters
scalar The scalar to multiply the Matrix by
Returns
A reference to the Matrix after multiplication by a scalar
Definition at line 593 of file Matrix.h.
   {
     std::transform ( MATRIX.begin(), MATRIX.end(), MATRIX.begin(),
                      scale_vector<T>( scalar ) );
     return *this;
   }
operator+() [1/2]
template<typename T > Matrix< T > Luna::Matrix< T >::operator+ () const inline
Unary +.
Returns
The Matrix
Definition at line 505 of file Matrix.h.
Referenced by Luna::Matrix< double >::~Matrix().
   {
     return *this;
   }
operator+() [2/2]
template<typename T> Matrix< T > Luna::Matrix< T >::operator+ (const Matrix< T > & m_plus) const inline
Binary +.
Parameters
m_plus The Matrix to be added
Returns
The sum of this Matrix and m_plus
Definition at line 520 of file Matrix.h.
   {
     Matrix<T> temp( *this );
     if ( m_plus.rows() != ROWS || m_plus.cols() != COLS )
     {
       throw Error( "Matrix dimension error in + operator." );
     }
     std::transform ( temp.MATRIX.cbegin(), temp.MATRIX.cend(),
                      m_plus.MATRIX.begin(), temp.MATRIX.begin(),
                      std::plus< Vector<T> >() );
     return temp;
   }
operator+=() [1/2]
template<typename T> Matrix< T > & Luna::Matrix< T >::operator+= (const Matrix< T > & m_plus) inline
Addition assignment.
Parameters
m_plus The Matrix to be added
Returns
A reference to the Matrix after addition by m_plus
Definition at line 567 of file Matrix.h.
   {
     if ( m_plus.rows() != ROWS || m_plus.cols() != COLS )
     {
       throw Error( "Matrix dimension error in += operator." );
     }
     std::transform ( MATRIX.begin(), MATRIX.end(),
                      m_plus.MATRIX.begin(), MATRIX.begin(),
                      std::plus< Vector<T> >() );
     return *this;
   }
operator+=() [2/2]
template<typename T> Matrix< T > & Luna::Matrix< T >::operator+= (const T & add) inline
Constant addition assignment.
Parameters
add The constant to be added to each element
Returns
A reference to the Matrix after addition by a constant
Definition at line 609 of file Matrix.h.
   {
     std::transform ( MATRIX.begin(), MATRIX.end(),  MATRIX.begin(),
                      add_vector<T>( add ) );
     return *this;
   }
operator-() [1/2]
template<typename T > Matrix< T > Luna::Matrix< T >::operator- () const inline
Unary -.
Returns
The negation of the Matrix
Definition at line 511 of file Matrix.h.
Referenced by Luna::Matrix< double >::~Matrix().
   {
     Matrix<T> temp( *this );
     std::transform ( temp.MATRIX.cbegin(), temp.MATRIX.cend(),
                      temp.MATRIX.begin(), std::negate< Vector<T> >() );
     return temp;
   }
operator-() [2/2]
template<typename T> Matrix< T > Luna::Matrix< T >::operator- (const Matrix< T > & m_minus) const inline
Binary -.
Parameters
m_minus The Matrix to be subtracted
Returns
The subtraction of m_minus from this Matrix
Definition at line 534 of file Matrix.h.
   {
     Matrix<T> temp( *this );
     if ( m_minus.rows() != ROWS || m_minus.cols() != COLS )
     {
       throw Error( "Matrix dimension error in - operator." );
     }
     std::transform ( temp.MATRIX.cbegin(), temp.MATRIX.cend(),
                      m_minus.MATRIX.begin(), temp.MATRIX.begin(),
                      std::minus< Vector<T> >() );
     return temp;
   }
operator-=() [1/2]
template<typename T> Matrix< T > & Luna::Matrix< T >::operator-= (const Matrix< T > & m_minus) inline
Subtraction assignment.
Parameters
m_minus The Matrix to be subtracted
Returns
A reference to the Matrix after subtraction by m_minus
Definition at line 580 of file Matrix.h.
   {
     if ( m_minus.rows() != ROWS || m_minus.cols() != COLS )
     {
       throw Error( "Matrix dimension error in -= operator." );
     }
     std::transform ( MATRIX.begin(), MATRIX.end(),
                      m_minus.MATRIX.begin(), MATRIX.begin(),
                      std::minus< Vector<T> >() );
     return *this;
   }
operator-=() [2/2]
template<typename T> Matrix< T > & Luna::Matrix< T >::operator-= (const T & minus) inline
Constant subtraction assignment.
Parameters
minus The constant to be subtracted from each element
Returns
A reference to the Matrix after subtraction by a constant
Definition at line 617 of file Matrix.h.
   {
     std::transform ( MATRIX.begin(), MATRIX.end(),  MATRIX.begin(),
                      minus_vector<T>( minus ) );
     return *this;
   }
operator/()
template<typename T> Matrix< T > Luna::Matrix< T >::operator/ (const T & divisor) const inline
Scalar division.
Parameters
divisor The divisor to divide the Matrix by
Returns
The Matrix divided by the divisor
Definition at line 557 of file Matrix.h.
   {
     Matrix<T> temp( *this );
     std::transform ( temp.MATRIX.begin(), temp.MATRIX.end(),
                      temp.MATRIX.begin(), div_vector<T>( divisor ) );
     return temp;
   }
operator/=()
template<typename T> Matrix< T > & Luna::Matrix< T >::operator/= (const T & divisor) inline
Scalar division assigment.
Parameters
divisor The divisor to divide the Matrix by
Returns
A reference to the Matrix after division by a scalar
Definition at line 601 of file Matrix.h.
   {
     std::transform ( MATRIX.begin(), MATRIX.end(), MATRIX.begin(),
                      div_vector<T>( divisor ) );
     return *this;
   }
operator=()
template<typename T> Matrix< T > & Luna::Matrix< T >::operator= (const Matrix< T > & original) inline
Copy assignment.
Parameters
original Matrix to be copied
Returns
The new Matrix to which the original matrix is assigned
Definition at line 492 of file Matrix.h.
Referenced by Luna::Matrix< double >::~Matrix().
   {
     if ( this == &original )
     {
       return * this;
     }
     MATRIX = original.MATRIX;
     ROWS = original.ROWS;
     COLS = original.COLS;
     return *this;
   }
operator[]() [1/2]
template<typename T > const Vector< T > & Luna::Matrix< T >::operator[] (const std::size_t & i) const inline
Operator overloading for row access (read only)
Parameters
i The row index
Returns
A constant reference to the Vector located at the given row
Definition at line 625 of file Matrix.h.
   {
     if ( i < 0 || ROWS <= i )
     {
       throw Error( "Matrix operator [] range error" );
     }
     return MATRIX[ i ];
   }
operator[]() [2/2]
template<typename T > Vector< T > & Luna::Matrix< T >::operator[] (const std::size_t & i) inline
Operator overloading for row access (read / write)
Parameters
i The row index
Returns
A reference to the Vector located at the given row
Definition at line 635 of file Matrix.h.
   {
     if ( i < 0 || ROWS <= i )
     {
       throw Error( "Matrix operator [] range error" );
     }
     return MATRIX[ i ];
   }
QR_decomp()
template<typename T> void Luna::Matrix< T >::QR_decomp (Matrix< T > & QT, Matrix< T > & R) inline
QR decomposition of the Matrix A = QR.
Parameters
QT The transpose of the orthogonal Matrix Q (Q^T Q = I)
R The upper triangular Matrix R
Definition at line 1190 of file Matrix.h.
Referenced by Luna::Matrix< double >::solve().
   {
     if ( ROWS != COLS )
     {
       throw Error( "QR_decomp error: Matrix is not square.");
     }
     R.MATRIX = MATRIX;
     R.ROWS = ROWS;
     R.COLS = COLS;
     QT.resize( ROWS, ROWS );
     bool singular( false );
     int i, j, k;
     Vector<T> c( ROWS ), d( ROWS );
     T sigma, sum, tau;
     double scale;
     for ( k = 0; k < ROWS - 1; k++ ) {
       scale = 0.0;
       for ( i = k; i < ROWS; i++ ) {
         scale = std::max( scale, std::abs( R.MATRIX[ i ][ k ] ) );
       }
       if ( scale == 0.0 ) {
         singular = true;
         c[k] = d[k] = 0.0;
       } else {
         for ( i = k; i < ROWS; i++ ){
           R.MATRIX[ i ][ k ] /= scale;
         }
         for ( sum = 0.0, i = k; i < ROWS; i++ ){
           sum += R.MATRIX[ i ][ k ] * R.MATRIX[ i ][ k ];
         }
         T a = std::sqrt( sum ); //TODO check this is okay
         T b = R.MATRIX[ k ][ k ];
         sigma = std::real(b) >= 0 ? ( std::real(a) >= 0 ? a : -a) :
                                     ( std::real(a) >= 0 ? -a : a); // sign(a,b)
         R.MATRIX[ k ][ k ] += sigma;
         c[k] = sigma * R.MATRIX[ k ][ k ];
         d[k] = - scale * sigma;
         for ( j = k + 1; j < ROWS; j++ ) {
           for ( sum = 0.0 , i = k; i < ROWS; i++ ){
             sum += R.MATRIX[ i ][ k ] * R.MATRIX[ i ][ j ];
           }
           tau = sum / c[ k ];
           for (i = k; i < ROWS; i++ ){
             R.MATRIX[ i ][ j ] -= tau * R.MATRIX[ i ][ k ];
           }
         }
       }
     }
     d[ ROWS - 1 ] = R.MATRIX[ ROWS - 1 ][ ROWS - 1 ];
     if ( d[ ROWS - 1 ] == 0.0) singular=true;
     QT.eye();
     for ( k = 0; k < ROWS - 1; k++ ) {
       if ( c[ k ] != 0.0 ) {
         for ( j = 0; j < ROWS; j++ ) {
           sum = 0.0;
           for ( i = k; i < ROWS; i++ ) {
             sum += R.MATRIX[ i ][ k ] * QT.MATRIX[ i ][ j ];
           }
           sum /= c[ k ];
           for ( i = k; i < ROWS; i++ ) {
             QT.MATRIX[ i ][ j ] -= sum * R.MATRIX[ i ][ k ];
           }
         }
       }
     }
     for ( i = 0; i < ROWS; i++ ) {
       R.MATRIX[ i ][ i ] = d[ i ];
       for ( j = 0; j < i; j++ ){
         R.MATRIX[ i ][ j ] = 0.0;
       }
     }
     if ( singular ) {
       std::cout << " *** WARNING! Matrix is singular in QR decomposition."
                 << std::endl;
     }
   }
random() [1/3]
template<class T> void Luna::Matrix< T >::random ()
Fill the Matrix with random elements (between -1 and 1)
Referenced by main().
random() [2/3]
template<> void Luna::Matrix< double >::random () inline
Definition at line 908 of file Matrix.h.
   {
     std::mt19937_64 rng;
     // initialize the random number generator with time-dependent seed
     auto start = std::chrono::high_resolution_clock::now();
     uint64_t timeSeed = start.time_since_epoch().count();
     std::seed_seq ss{uint32_t(timeSeed & 0xffffffff), uint32_t(timeSeed>>32)};
     rng.seed(ss);
     // initialize a uniform distribution between -1 and 1
     std::uniform_real_distribution<double> unif(-1, 1);
     for ( std::size_t i = 0; i < ROWS; ++i )
     {
       for ( std::size_t j = 0; j < COLS; ++j )
       {
         double num( unif(rng) );
         MATRIX[ i ][ j ] = num;
       }
     }
   }
random() [3/3]
template<> void Luna::Matrix< std::complex< double > >::random () inline
Definition at line 929 of file Matrix.h.
   {
     std::mt19937_64 rng;
     // initialize the random number generator with time-dependent seed
     auto start = std::chrono::high_resolution_clock::now();
     uint64_t timeSeed = start.time_since_epoch().count();
     std::seed_seq ss{uint32_t(timeSeed & 0xffffffff), uint32_t(timeSeed>>32)};
     rng.seed(ss);
     // initialize a uniform distribution between -1 and 1
     std::uniform_real_distribution<double> unif(-1, 1);
     for ( std::size_t i = 0; i < ROWS; ++i )
     {
       for ( std::size_t j = 0; j < COLS; ++j )
       {
         double real( unif(rng) );
         double imag( unif(rng) );
         MATRIX[ i ][ j ] = std::complex<double> ( real, imag );
       }
     }
   }
real()
template<typename T > Matrix< double > Luna::Matrix< T >::real () const inline
Real part of the elements of the Matrix.
Returns
Matrix of real parts of the elements
Definition at line 958 of file Matrix.h.
   {
     Matrix<double> real_part( ROWS, COLS, 0.0 );
     for (size_t i = 0; i < ROWS; ++i )
     {
       for (size_t j = 0; j < COLS; ++j )
       real_part( i, j ) = std::real( MATRIX[ i ][ j ] ) ;
     }
     return real_part;
   }
resize()
template<typename T > void Luna::Matrix< T >::resize (const std::size_t & rows, const std::size_t & cols) inline
Resize the Matrix while (empty entries are appended if necessary)
Parameters
rows The number of rows in the Matrix
cols The number of columns in the Matrix
Definition at line 813 of file Matrix.h.
Referenced by Luna::BandedMatrix< T >::det(), Luna::Matrix< double >::inverse(), Luna::Matrix< double >::LU_decomp(), main(), Luna::Matrix< double >::QR_decomp(), and Luna::BandedMatrix< T >::solve().
   {
     Matrix<T> temp( *this );
     MATRIX.clear();
     // Create an empty Matrix
     const Vector<T> row( cols, 0 );
     MATRIX.reserve( rows );
     for ( std::size_t i = 0; i < rows; ++i )
     {
       MATRIX.push_back( row );
     }
     // Refill the Matrix using old values
     for ( std::size_t i = 0; i < rows; ++i )
     {
       for ( std::size_t j = 0; j < cols; ++j )
       {
         if ( i<ROWS && j<COLS )
         {
           MATRIX[ i ][ j ] = temp.MATRIX[ i ][ j ];
         }
       }
     }
     ROWS = rows;
     COLS = cols;
   }
rows()
template<typename T > std::size_t Luna::Matrix< T >::rows () const inline
Return the number of rows in the Matrix.
Returns
The number of rows in the Matrix
Definition at line 690 of file Matrix.h.
Referenced by Luna::BandedMatrix< T >::BandedMatrix(), Luna::LinearEigensystem< T >::compute_real(), Luna::LinearEigensystem< T >::compute_real_symmetric(), Luna::LinearEigensystem< T >::eigenvectors(), Luna::Matrix< double >::Matrix(), Luna::Matrix< double >::multiply(), Luna::Matrix< double >::operator+(), Luna::Matrix< double >::operator+=(), Luna::Matrix< double >::operator-(), Luna::Matrix< double >::operator-=(), Luna::BandedMatrix< T >::solve(), Luna::Tridiagonal< T >::solve(), Luna::Matrix< double >::solve_basic(), and Luna::Matrix< double >::solve_LU().
   {
     return ROWS;
   }
set_col()
template<typename T> void Luna::Matrix< T >::set_col (const std::size_t & col, const Vector< T > & vec) inline
Set a column of the Matrix using a Vector.
Parameters
col The column index
vec The Vector used to replace the specified column
Definition at line 720 of file Matrix.h.
Referenced by Luna::Residual< double >::jacobian(), Luna::Matrix< double >::multiply(), Luna::BandedMatrix< T >::solve(), Luna::Tridiagonal< T >::solve(), and Luna::Matrix< double >::solve_basic().
   {
     for ( std::size_t row = 0; row < ROWS; ++row )
     {
       MATRIX[ row ][ col ] = vec[ row ];
     }
   }
set_row()
template<typename T> void Luna::Matrix< T >::set_row (const std::size_t & row, Vector< T > & vec) inline
Set a row of the Matrix using a Vector.
Parameters
row The row index
vec The Vector used to replace the specified row
Definition at line 708 of file Matrix.h.
   {
     if ( vec.size() != COLS ){
       throw Error( "Size error in set_row method." );
     }
     if ( row < 0 || ROWS <= row ){
       throw Error( "Range error in set_row method." );
     }
     MATRIX[ row ] = vec;
   }
solve() [1/2]
template<class T> Vector<T> Luna::Matrix< T >::solve (const Vector< T > & b) inline
Solve the system of equations Ax=b where x and b are Vectors.
Parameters
b The right-hand side Vector of the system of equations
Returns
The solution Vector
Definition at line 404 of file Matrix.h.
Referenced by Luna::Newton< T >::arclength_solve(), Luna::Newton< T >::iterate(), and main().
 { return solve_LU( b ); }
solve() [2/2]
template<class T> Matrix<T> Luna::Matrix< T >::solve (const Matrix< T > & B) inline
Solve the system of equations AX=B where X and B are Matrices.
Parameters
B The right-hand side Matrix of the system of equations
Returns
The solution Matrix (each column is a solution Vector)
Definition at line 409 of file Matrix.h.
 { return solve_LU( B ); }
solve_basic() [1/2]
template<typename T> Vector< T > Luna::Matrix< T >::solve_basic (const Vector< T > & b) inline
Solve the system of equations Ax=b where x and b are Vectors.
Parameters
b The right-hand side Vector of the system of equations
Returns
The solution Vector
Definition at line 1052 of file Matrix.h.
Referenced by main().
   {
     if ( ROWS != b.size() )
     {
       throw Error( "solve_basic error: ROWS != b.size() " );
     }
     if ( ROWS != COLS )
     {
       throw Error( "solve_basic error: Matrix is not square.");
     }
     Matrix<T> A( *this );
     Vector<T> x( b );
     A.Gauss_with_pivot( x );
     A.backsolve( x );
     return x;
   }
solve_basic() [2/2]
template<typename T> Matrix< T > Luna::Matrix< T >::solve_basic (const Matrix< T > & B) inline
Solve the system of equations AX=B where X and B are Matrices.
Parameters
B The right-hand side Matrix of the system of equations
Returns
The solution Matrix (each column is a solution Vector)
Definition at line 1070 of file Matrix.h.
   {
     if ( ROWS != B.rows() )
     {
       throw Error( "solve_basic error: ROWS != B.rows() " );
     }
     if ( ROWS != COLS )
     {
       throw Error( "solve_basic error: Matrix is not square.");
     }
     Matrix<T> A( *this );
     Matrix<T> X( B );
     A.Gauss_with_pivot( X );
     Vector<T> x( ROWS );
     for ( std::size_t j = 0; j < B.COLS; ++j )
     {
       x = X.get_col( j );
       A.backsolve( x );
       X.set_col( j, x );
     }
     return X;
   }
solve_LU() [1/2]
template<typename T> Vector< T > Luna::Matrix< T >::solve_LU (const Vector< T > & b) inline
Solve the system of equations Ax=b where x and b are Vectors using LU decomposition.
Parameters
b The right-hand side Vector of the system of equations
Returns
The solution Vector
Definition at line 1133 of file Matrix.h.
Referenced by Luna::Matrix< double >::solve().
   {
     if ( ROWS != b.size() )
     {
       throw Error( "solve_LU error: ROWS != b.size() " );
     }
     if ( ROWS != COLS )
     {
       throw Error( "solve_LU error: Matrix is not square.");
     }
     Matrix<T> LU( *this );
     Matrix<T> P;
     std::size_t pivots;
     pivots = LU.LU_decomp_in_place( P );
     Vector<T> x( b );
     x = P * x;
     for ( std::size_t i = 0; i < ROWS; i++ ) {
         for ( std::size_t k = 0; k < i; k++ )
             x[ i ] -= LU.MATRIX[ i ][ k ] * x[ k ];
     }
     LU.backsolve( x );
     return x;
   }
solve_LU() [2/2]
template<typename T> Matrix< T > Luna::Matrix< T >::solve_LU (const Matrix< T > & B) inline
Solve the system of equations AX=B where X and B are Matrices using LU decomposition.
Parameters
B The right-hand side Matrix of the system of equations
Returns
The solution Matrix (each column is a solution Vector)
Definition at line 1159 of file Matrix.h.
   {
     if ( ROWS != B.rows() )
     {
       throw Error( "solve_basic error: ROWS != B.rows() " );
     }
     if ( ROWS != COLS )
     {
       throw Error( "solve_basic error: Matrix is not square.");
     }
     Matrix<T> LU( *this );
     Matrix<T> P;
     std::size_t pivots;
     pivots = LU.LU_decomp_in_place( P );
     Matrix<T> X( B );
     X = P * X;
     Vector<T> x( ROWS );
     for ( std::size_t j = 0; j < B.COLS; ++j )
     {
       x = X.get_col( j );
       for ( std::size_t i = 0; i < ROWS; i++ ) {
           for ( std::size_t k = 0; k < i; k++ )
               x[ i ] -= LU.MATRIX[ i ][ k ] * x[ k ];
       }
       LU.backsolve( x );
       X.set_col( j, x );
     }
     return X;
   }
solve_QR()
template<typename T> Vector< T > Luna::Matrix< T >::solve_QR (const Vector< T > & b) inline
Solve the system of equations Ax=b where x and b are Vectors using QR decomposition.
Parameters
b The right-hand side Vector of the system of equations
Returns
The solution Vector
Definition at line 1276 of file Matrix.h.
Referenced by Luna::Matrix< double >::solve().
   {
     if ( ROWS != b.size() )
     {
       throw Error( "solve_QR error: ROWS != b.size() " );
     }
     if ( ROWS != COLS )
     {
       throw Error( "solve_QR error: Matrix is not square.");
     }
     Matrix<T> QT, R;
     this->QR_decomp( QT, R );
     Vector<T> x( ROWS, 0.0 );
     x = QT.multiply( b );
     this->rsolve( x, x, R );            // Solve R * x = Q^T * b
     return x;
   }
swap_elem()
template<typename T > void Luna::Matrix< T >::swap_elem (const std::size_t & i_1, const std::size_t & j_1, const std::size_t & i_2, const std::size_t & j_2) inline
Swap two elements of the Matrix.
Parameters
i_1 The row index of the first element
j_1 The column index of the first element
i_2 The row index of the second element
j_2 The column index of the second element
Definition at line 855 of file Matrix.h.
   {
     std::swap( MATRIX[ i_1 ][ j_1 ], MATRIX[ i_2 ][ j_2 ] );
   }
swap_rows()
template<typename T > void Luna::Matrix< T >::swap_rows (const std::size_t & i, const std::size_t & j) inline
Swap two rows of the Matrix.
Parameters
i The index of the first row
j The index of the second row
Definition at line 841 of file Matrix.h.
Referenced by Luna::Matrix< double >::inverse().
   {
     if ( i < 0 || ROWS <= i )
     {
       throw Error( "Matrix swap row range error in first index" );
     }
     if ( j < 0 || ROWS <= j )
     {
       throw Error( "Matrix swap row range error in second index" );
     }
     std::swap< Vector<T> > ( MATRIX[ i ], MATRIX[ j ] );
   }
transpose()
template<typename T > Matrix< T > Luna::Matrix< T >::transpose () const inline
Return the transpose of the Matrix.
Returns
The transpose of the Matrix
Definition at line 754 of file Matrix.h.
   {
     Matrix<T> temp( *this );
     temp.transpose_in_place();
     return temp;
   }
transpose_in_place()
template<typename T > void Luna::Matrix< T >::transpose_in_place () inline
Replace the current Matrix with its transpose.
Definition at line 762 of file Matrix.h.
Referenced by Luna::Matrix< double >::conjugate_transpose(), and Luna::Matrix< double >::transpose().
   {
     if( ROWS == COLS ) // Square matrix
     {
       for ( std::size_t i = 0; i < ROWS; ++i )
       {
         for ( std::size_t j = i + 1; j < COLS; ++j )
         {
           std::swap( MATRIX[ i ][ j ], MATRIX[ j ][ i ] );
         }
       }
     } else // Non-square matrix
     {
       std::vector< Vector<T> > temp;
       temp.resize( COLS );
       for ( std::size_t row = 0; row < COLS; ++row )
        {
          temp[ row ].resize( ROWS );
        }
        for ( std::size_t i = 0; i < ROWS; ++i )
        {
          for ( std::size_t j = 0; j < COLS; ++j )
          {
            temp[ j ][ i ] = MATRIX[ i ][ j ];
          }
        }
        MATRIX = temp;
        std::swap( ROWS, COLS );
     }
   }
Friends And Related Function Documentation
operator*
template<class T> Matrix<T> operator* (const T & scalar, Matrix< T > & mat) friend
Definition at line 173 of file Matrix.h.
     {
       return mat * scalar;
     }
operator<<
template<class T> template<class Type > std::ostream& operator<< (std::ostream & os, const Matrix< Type > & m) friend
Output operator <<.
Definition at line 461 of file Matrix.h.
   {
     os << std::endl;
     for (std::size_t j = 0; j < m.ROWS; ++j )
     {
       if ( m.MATRIX[ j ].size() != m.COLS ){
         throw Error( "Matrix dimension error: wrong sized row in Matrix." );
       }
       os << "\t" << m.MATRIX[ j ] << std::endl;
     }
     return os;
   }
The documentation for this class was generated from the following file:
include/Luna/Matrix.h