Luna: Luna::Mesh2D< T > Class Template Reference
Luna::Mesh2D< T > Class Template Reference
#include <Mesh2D.h>
Public Member Functions
Mesh2D ()
Constructor for an empty mesh.
Mesh2D (const Vector< double > &x_nodes, const Vector< double > &y_nodes, const std::size_t &nvars)
Constructor (given nodal distribution)
~Mesh2D ()
Destructor.
T & operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var)
Access operator for a nodal point/variable in the mesh.
const T & operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var) const
Const access operator for a nodal point/variable in the mesh.
Mesh2D< T > & operator= (const Mesh2D< T > &original)
Copy assignment.
std::pair< double, double > coord (const std::size_t nodex, const std::size_t nodey) const
Return the spatial position of a given given node as a pair.
void set_nodes_vars (const std::size_t nodex, const std::size_t nodey, const Vector< T > &vec)
Set the variables stored at a specified node.
Vector< T > get_nodes_vars (const std::size_t nodex, const std::size_t nodey) const
Get the variables stored at a specified node.
Mesh1D< T > get_cross_section_xnode (const std::size_t nodex) const
Get a cross section of the 2D mesh at a specified (constant) x node.
Mesh1D< T > get_cross_section_ynode (const std::size_t nodey) const
Get a cross section of the 2D mesh at a specified (constant) y node.
void assign (const T elt)
Assign an element to all entries in the mesh.
std::pair< std::size_t, std::size_t > get_nnodes () const
Get the number of nodes in the two directions of the 2D mesh.
std::size_t get_nvars () const
Get the number of variables that are stored at each node.
const Vector< double > & xnodes () const
Return A vector of the x-nodal positions for this mesh.
const Vector< double > & ynodes () const
Return A vector of the y-nodal positions for this mesh.
Matrix< T > get_var_as_matrix (std::size_t var) const
Return a Matrix corresponding to each nodal point in the mesh.
void remesh (const Vector< double > &newX, const Vector< double > &newY)
Interpolate the mesh data (bilinearly) into a new mesh.
void output () const
Output mesh data to std::cout.
void output (std::string filename) const
Output mesh data to a file.
void output_var (std::string filename, const std::size_t var) const
Output a single variable to a file with no nodal information.
void read (std::string filename, const bool reset=false)
A simple method for reading data from a file.
void output_gnu (std::string filename) const
Output data to a file for gnuplot surface plotting.
Vector< T > get_interpolated_vars (const double &x, const double &y)
Get a bilinearly interpolated value at a specified point.
T integral2D (std::size_t var=0) const
Numerically integrate a given variable over the domain.
T square_integral2D (std::size_t var=0) const
Numerically integrate the square of the absolute value over the domain.
Vector< T > get_vars ()
Return the Vector of variables.
template<>
void read (std::string filename, const bool reset)
template<>
void output_gnu (std::string filename) const
template<>
void output_gnu (std::string filename) const
Detailed Description
template<class T>
class Luna::Mesh2D< T >
Definition at line 26 of file Mesh2D.h.
Constructor & Destructor Documentation
Mesh2D() [1/2]
template<class T> Luna::Mesh2D< T >::Mesh2D () inline
Constructor for an empty mesh.
Definition at line 37 of file Mesh2D.h.
              : NX( 0 ), NY( 0 ), NV( 0 )
     {}
Mesh2D() [2/2]
template<class T> Luna::Mesh2D< T >::Mesh2D (const Vector< double > & x_nodes, const Vector< double > & y_nodes, const std::size_t & nvars) inline
Constructor (given nodal distribution)
Parameters
x_nodes Vector of nodal positions along the x-axis
y_nodes Vector of nodal positions along the y-axis
nvars The number of variables
Definition at line 44 of file Mesh2D.h.
                                      : NX( x_nodes.size() ),
             NY( y_nodes.size() ), NV( nvars ), X_NODES( x_nodes ),
             Y_NODES( y_nodes )
     {
       // Create the storage Vector and set the contents to zero
       VARS = Vector<T>( NV * NX * NY, T( 0.0 ) );
     }
~Mesh2D()
template<class T> Luna::Mesh2D< T >::~Mesh2D () inline
Destructor.
Definition at line 54 of file Mesh2D.h.
References Luna::Mesh2D< T >::assign(), Luna::Mesh2D< T >::coord(), Luna::Mesh2D< T >::get_cross_section_xnode(), Luna::Mesh2D< T >::get_cross_section_ynode(), Luna::Mesh2D< T >::get_interpolated_vars(), Luna::Mesh2D< T >::get_nnodes(), Luna::Mesh2D< T >::get_nodes_vars(), Luna::Mesh2D< T >::get_nvars(), Luna::Mesh2D< T >::get_var_as_matrix(), Luna::Mesh2D< T >::get_vars(), Luna::Mesh2D< T >::integral2D(), Luna::Mesh2D< T >::operator()(), Luna::Mesh2D< T >::operator=(), Luna::Mesh2D< T >::output(), Luna::Mesh2D< T >::output_gnu(), Luna::Mesh2D< T >::output_var(), Luna::Mesh2D< T >::read(), Luna::Mesh2D< T >::remesh(), Luna::Mesh2D< T >::set_nodes_vars(), Luna::Mesh2D< T >::square_integral2D(), Heat_plot::x, Luna::Mesh2D< T >::xnodes(), Spectral_ODE_Rational_plot::y, and Luna::Mesh2D< T >::ynodes().
 {}
Member Function Documentation
assign()
template<typename T > void Luna::Mesh2D< T >::assign (const T elt)
Assign an element to all entries in the mesh.
Parameters
elt Element to assign to all entries in the mesh
Definition at line 329 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     VARS.assign( NX * NY * NV, elt );
   }
coord()
template<typename T > std::pair< double, double > Luna::Mesh2D< T >::coord (const std::size_t nodex, const std::size_t nodey) const inline
Return the spatial position of a given given node as a pair.
Parameters
nodex Node index (x-axis)
nodey Node index (y-axis)
Returns
The nodal value pair at the specified index
Definition at line 243 of file Mesh2D.h.
Referenced by main(), Luna::Mesh2D< T >::remesh(), and Luna::Mesh2D< T >::~Mesh2D().
   {
     if ( nodex > NX - 1 || nodey > NY - 1 || nodex < 0 || nodey < 0 )
     {
       std::string problem;
       problem = " The Mesh2D.coord method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw Error( problem );
     }
     std::pair< double, double > pos;
     pos.first = X_NODES[ nodex ];
     pos.second = Y_NODES[ nodey ];
     return pos;
   }
get_cross_section_xnode()
template<typename T > Mesh1D< T > Luna::Mesh2D< T >::get_cross_section_xnode (const std::size_t nodex) const
Get a cross section of the 2D mesh at a specified (constant) x node.
Parameters
nodex Node index (x-axis)
Returns
A 1D mesh cross section of the 2D mesh
Definition at line 307 of file Mesh2D.h.
References Luna::Mesh2D< T >::get_nodes_vars(), and Luna::Mesh1D< T, X >::set_nodes_vars().
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     Mesh1D<T> section( Y_NODES, NV );
     for ( std::size_t nodey = 0; nodey < NY; ++nodey )
     {
       section.set_nodes_vars( nodey, this -> get_nodes_vars( nodex, nodey ) );
     }
     return section;
   }
get_cross_section_ynode()
template<typename T > Mesh1D< T > Luna::Mesh2D< T >::get_cross_section_ynode (const std::size_t nodey) const
Get a cross section of the 2D mesh at a specified (constant) y node.
Parameters
nodey Node index (y-axis)
Returns
A 1D mesh cross section of the 2D mesh
Definition at line 318 of file Mesh2D.h.
References Luna::Mesh2D< T >::get_nodes_vars(), and Luna::Mesh1D< T, X >::set_nodes_vars().
Referenced by Luna::Mesh2D< T >::get_interpolated_vars(), and Luna::Mesh2D< T >::~Mesh2D().
   {
     Mesh1D<T> section( X_NODES, NV );
     for ( std::size_t nodex = 0; nodex < NX; ++nodex )
     {
       section.set_nodes_vars( nodex, this -> get_nodes_vars( nodex, nodey ) );
     }
     return section;
   }
get_interpolated_vars()
template<typename T > Vector< T > Luna::Mesh2D< T >::get_interpolated_vars (const double & x, const double & y)
Get a bilinearly interpolated value at a specified point.
Parameters
x The x-coordinate
y The y-coordinate
Returns
The interpolated Vector of variables at a specified point
Definition at line 831 of file Mesh2D.h.
References Luna::Mesh2D< T >::get_cross_section_ynode(), Luna::Mesh1D< T, X >::get_interpolated_vars(), and Spectral_ODE_Rational_plot::y.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     if ( ( x < X_NODES[ 0 ] ) || ( x > X_NODES[ NX - 1 ] ) )
     {
       std::string problem;
       problem = "The Mesh2D.get_interpolated_vars method has been called \n";
       problem += "with an x coordinate that lies outside the mesh. \n";
       throw Error( problem );
     }
     if ( ( y < Y_NODES[ 0 ] ) || ( y > Y_NODES[ NY - 1 ] ) )
     {
       std::string problem;
       problem = "The Mesh2D.get_interpolated_vars method has been called \n";
       problem += "with a y coordinate that lies outside the mesh. \n";
       throw Error( problem );
     }
     int bottom_j( -2 );
     for ( unsigned j = 0; j < NY - 1; ++j )
     {
       if ( ( y > Y_NODES[ j ] ) && ( y < Y_NODES[ j + 1 ] ) )
       {
         bottom_j = j;
       }
       if ( ( abs( y - Y_NODES[ j ] ) < 1.e-10 ) ||
            ( abs( y - Y_NODES[ j + 1 ] ) < 1.e-10 ) )
       {
         bottom_j = j;
       }
     }
     if ( bottom_j == -1 )
     {
       std::string problem;
       problem = " The Mesh2D.get_interpolated_vars method is broken.\n";
       throw Error( problem );
     }
     //std::cout << y << " " << Y_NODES[bottom_j] << " "
     //          << Y_NODES[bottom_j+1] << "\n";
     Mesh1D<T> bottom_row = get_cross_section_ynode( bottom_j );
     Mesh1D<T> top_row = get_cross_section_ynode( bottom_j + 1 );
     const double y1 = Y_NODES[ bottom_j ];
     const double y2 = Y_NODES[ bottom_j + 1 ];
     Vector<T> result = top_row.get_interpolated_vars( x )*( y2-y )/( y2-y1 )
       + bottom_row.get_interpolated_vars(x)*( y-y1 )/( y2-y1 );
     //std::cout << "x,y,interp: " << x << " " << y << " " << result[0] << "\n";
     return result;
   }
get_nnodes()
template<typename T > std::pair< std::size_t, std::size_t > Luna::Mesh2D< T >::get_nnodes () const
Get the number of nodes in the two directions of the 2D mesh.
Returns
A std::pair containing the number of nodes in each direction
Definition at line 335 of file Mesh2D.h.
Referenced by main(), and Luna::Mesh2D< T >::~Mesh2D().
   {
     std::pair< std::size_t, std::size_t > nodes;
     nodes.first = NX;
     nodes.second = NY;
     return nodes;
   }
get_nodes_vars()
template<typename T > Vector< T > Luna::Mesh2D< T >::get_nodes_vars (const std::size_t nodex, const std::size_t nodey) const
Get the variables stored at a specified node.
Parameters
nodex Node index (x-axis)
nodey Node index (y-axis)
Returns
The Vector of variables
Definition at line 287 of file Mesh2D.h.
References Luna::Vector< T >::push_back().
Referenced by Luna::Mesh2D< T >::get_cross_section_xnode(), Luna::Mesh2D< T >::get_cross_section_ynode(), Luna::Mesh2D< T >::remesh(), and Luna::Mesh2D< T >::~Mesh2D().
   {
     if ( nodex > NX - 1 || nodey > NY - 1 )
     {
       std::string problem;
       problem = " The Mesh2D.get_nodes_vars method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw Error( problem );
     }
     //Construct a vector with NV elements
     Vector<T> nodes_vars;
     for ( std::size_t var = 0; var < NV; ++var )
     {
       nodes_vars.push_back( VARS[ ( nodex * NY + nodey ) * NV + var ] );
     }
     return nodes_vars;
   }
get_nvars()
template<typename T > std::size_t Luna::Mesh2D< T >::get_nvars () const
Get the number of variables that are stored at each node.
Returns
The number of variables stored in the mesh
Definition at line 344 of file Mesh2D.h.
Referenced by main(), and Luna::Mesh2D< T >::~Mesh2D().
   {
     return NV;
   }
get_var_as_matrix()
template<typename T > Matrix< T > Luna::Mesh2D< T >::get_var_as_matrix (std::size_t var) const
Return a Matrix corresponding to each nodal point in the mesh.
Parameters
var Variable index
Returns
A Matrix for a specified variable at each nodal point
Definition at line 362 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     if ( var > NV - 1 )
     {
       std::string problem;
       problem = " The Mesh2D.get_var_as_matrix method is trying to use an \n";
       problem += " index bigger than the number of variables in the mesh. \n";
       throw Error( problem );
     }
     Matrix<T> temp( NX, NY, 0.0 );
     for ( std::size_t i = 0; i < NX; ++i )
     {
       for  ( std::size_t j = 0; j < NY; ++j )
       {
         temp( i, j ) = VARS[ ( i * NY + j ) * NV + var ];
       }
     }
     return temp;
   }
get_vars()
template<typename T > Vector< T > Luna::Mesh2D< T >::get_vars ()
Return the Vector of variables.
Returns
A copy of the Vector of variables
Definition at line 927 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     Vector<T> temp;
     temp = VARS;
     return temp;
   }
integral2D()
template<typename T > T Luna::Mesh2D< T >::integral2D (std::size_t var = 0) const
Numerically integrate a given variable over the domain.
Parameters
var Variable index
Returns
The integral over the domain
Definition at line 881 of file Mesh2D.h.
Referenced by main(), and Luna::Mesh2D< T >::~Mesh2D().
   {
     T sum( 0.0 );
     double dx( 0.0 );
     double dy( 0.0 );
     // Sum over the elements
     for ( std::size_t i=0; i < NX - 1; ++i )
     {
       dx = X_NODES[ i + 1 ] - X_NODES[ i ];
       for ( std::size_t j=0; j < NY - 1; ++j )
       {
         dy = Y_NODES[ j + 1 ] - Y_NODES[ j ];
         sum += 0.25 * dx * dy * ( VARS[ ( i * NY + j ) * NV + var ]
             + VARS[ ( ( i + 1 ) * NY + j ) * NV + var ]
             + VARS[ ( i * NY + j + 1 ) * NV + var ]
             + VARS[ ( ( i + 1 ) * NY + j + 1 ) * NV + var ] );
       }
     }
     return sum;
   }
operator()() [1/2]
template<typename T > T & Luna::Mesh2D< T >::operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var) inline
Access operator for a nodal point/variable in the mesh.
Parameters
nodex Node index (x-axis)
nodey Node index (y-axis)
var Variable index
Returns
A reference to the variable stored at the given node
Definition at line 186 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     if ( nodex > NX - 1 || nodey > NY - 1 )
     {
       std::string problem;
       problem = " The Mesh2D.operator() method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw Error( problem );
     }
     if ( var > NV - 1 )
     {
       std::string problem;
       problem = " The Mesh2D.operator() method is trying to \n";
       problem += " access a variable index that is not in the mesh. \n";
       throw Error( problem );
     }
     return VARS[ ( nodex * NY + nodey ) * NV + var ];
   }
operator()() [2/2]
template<typename T > const T & Luna::Mesh2D< T >::operator() (const std::size_t nodex, const std::size_t nodey, const std::size_t var) const inline
Const access operator for a nodal point/variable in the mesh.
Parameters
nodex Node index (x-axis)
nodey Node index (y-axis)
var Variable index
Returns
A constant reference to the variable stored at the given node
Definition at line 209 of file Mesh2D.h.
   {
     if ( nodex > NX - 1 || nodey > NY - 1 )
     {
       std::string problem;
       problem = " The Mesh2D.operator() method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw Error( problem );
     }
     if ( var > NV - 1 )
     {
       std::string problem;
       problem = " The Mesh2D.operator() method is trying to \n";
       problem += " access a variable index that is not in the mesh. \n";
       throw Error( problem );
     }
     return VARS[ ( nodex * NY + nodey ) * NV + var ];
   }
operator=()
template<typename T > Mesh2D< T > & Luna::Mesh2D< T >::operator= (const Mesh2D< T > & original) inline
Copy assignment.
Parameters
original 2D mesh to be copied
Returns
The new 2D mesh
Definition at line 231 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     NX = original.NX;
     NY = original.NY;
     NV = original.NV;
     X_NODES = original.X_NODES;
     Y_NODES =  original.Y_NODES;
     VARS = original.VARS;
     return *this;
   }
output() [1/2]
template<typename T > void Luna::Mesh2D< T >::output () const
Output mesh data to std::cout.
Definition at line 655 of file Mesh2D.h.
Referenced by main(), and Luna::Mesh2D< T >::~Mesh2D().
   {
     for ( std::size_t var = 0; var < NV; ++var )
     {
       std::cout << "Variable : " << var << "\n";
       std::cout << " x = ";
       for ( std::size_t i = 0; i < NX; ++i )
       {
         std::cout << X_NODES[ i ] << ", ";
       }
       std::cout << "\n";
       for ( std::size_t j = 0; j < NY; ++j )
       {
         std::cout << " y = " << Y_NODES[ j ] << "\n";
         for ( std::size_t i = 0; i < NX; ++i )
         {
           std::cout << VARS[ ( i * NY + j ) * NV + var ] << ", ";
         }
         std::cout << "\n";
       }
     }
   }
output() [2/2]
template<typename T > void Luna::Mesh2D< T >::output (std::string filename) const
Output mesh data to a file.
Parameters
filename Name of the file to output the mesh data to
Definition at line 679 of file Mesh2D.h.
   {
     std::ofstream out;
     out.open( filename.c_str() );
     out.precision( 12 );
     out.setf( std::ios::showpoint );
     out.setf( std::ios::showpos );
     out.setf( std::ios::scientific );
     out.precision( 12 );
     for ( std::size_t j = 0; j < NY; ++j )
     {
       for ( std::size_t i = 0; i < NX; ++i )
       {
         out << X_NODES[ i ] << " " << Y_NODES[ j ] << " ";
         for ( std::size_t var = 0; var < NV; ++var )
         {
           out << VARS[ ( i * NY + j ) * NV + var ] << " ";
         }
         out << "\n";
       }
       out << "\n";
     }
   }
output_gnu() [1/3]
template<class T> void Luna::Mesh2D< T >::output_gnu (std::string filename) const
Output data to a file for gnuplot surface plotting.
Parameters
filename Name of the file to output the mesh data to
Referenced by Luna::Mesh2D< T >::~Mesh2D().
output_gnu() [2/3]
template<> void Luna::Mesh2D< double >::output_gnu (std::string filename) const
Definition at line 778 of file Mesh2D.h.
   {
     std::ofstream out;
     out.open( filename.c_str() );
     out.precision( 12 );
     out.setf( std::ios::showpoint );
     out.setf( std::ios::showpos );
     out.setf( std::ios::scientific );
     for ( std::size_t i = 0; i < NX; ++i )
     {
       for ( std::size_t j = 0; j < NY; ++j )
       {
         out << X_NODES[ i ] << " " << Y_NODES[ j ] << " ";
         for ( std::size_t var = 0; var < NV; ++var )
         {
           out << VARS[ ( i * NY + j ) * NV + var ] << " ";
         }
         out << "\n";
       }
       out << "\n";
     }
     out.close();
   }
output_gnu() [3/3]
template<> void Luna::Mesh2D< std::complex< double > >::output_gnu (std::string filename) const
Definition at line 804 of file Mesh2D.h.
   {
     std::ofstream out;
     out.open( filename.c_str() );
     out.precision( 12 );
     out.setf( std::ios::showpoint );
     out.setf( std::ios::showpos );
     out.setf( std::ios::scientific );
     //
     for ( std::size_t i = 0; i < NX; ++i )
     {
       for ( std::size_t j = 0; j < NY; ++j )
       {
         out << X_NODES[ i ] << " " << Y_NODES[ j ] << " ";
         for ( std::size_t var = 0; var < NV; ++var )
         {
           out << real(VARS[ ( i * NY + j ) * NV + var ]) << " ";
           out << imag(VARS[ ( i * NY + j ) * NV + var ]) << " ";
         }
         out << "\n";
       }
       out << "\n";
     }
     out.close();
   }
output_var()
template<typename T > void Luna::Mesh2D< T >::output_var (std::string filename, const std::size_t var) const
Output a single variable to a file with no nodal information.
Parameters
filename Name of the file to output the data to
var Variable index
Definition at line 704 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     std::ofstream out;
     out.open( filename.c_str() );
     out.precision( 12 );
     out.setf( std::ios::showpoint );
     out.setf( std::ios::showpos );
     out.setf( std::ios::scientific );
     out.precision( 12 );
     for ( std::size_t j = 0; j < NY; ++j )
     {
       for ( std::size_t i = 0; i < NX; ++i )
       {
         out << VARS[ ( i * NY + j ) * NV + var ] << "\n";
       }
     }
   }
read() [1/2]
template<class T> void Luna::Mesh2D< T >::read (std::string filename, const bool reset = false)
A simple method for reading data from a file.
Parameters
filename Name of the file to read the data from
reset Reset the mesh nodes using data from file
Referenced by Luna::Mesh2D< T >::~Mesh2D().
read() [2/2]
template<> void Luna::Mesh2D< double >::read (std::string filename, const bool reset)
Definition at line 724 of file Mesh2D.h.
References ODE_BVP_System_plot::v, Heat_plot::x, and Spectral_ODE_Rational_plot::y.
   {
     std::ifstream inFile;
     inFile.open( filename.c_str() );
     inFile.precision( 12 );
     inFile.setf( std::ios::showpoint );
     inFile.setf( std::ios::showpos );
     inFile.setf( std::ios::scientific );
     if (!inFile) {
       throw Error( "Mesh2D unable to open file" );
     }
     double x, y;
     Vector<double> vals( NV );
     for ( std::size_t i = 0; i < NX; ++i )
     {
       for ( std::size_t j = 0; j < NY; ++j )
       {
         inFile >> x;
         inFile >> y;
         std::size_t offset( ( i * NY + j ) * NV );
         for ( std::size_t v = 0; v < NV; ++v )
         {
           inFile >> vals[ v ];
           VARS[ offset++ ] = vals[ v ];
         }
         // Check the mesh
         if ( !reset )
             {
                 if ( ( std::abs( x - X_NODES[ i ] ) > 1.e-6 ) ||
                ( std::abs( y - Y_NODES[ j ] ) > 1.e-6 ) )
                 {
                     std::cout << " Read x = " << x << " Expected x = "
                       << X_NODES[ i ] << std::endl;
             std::cout << " Read y = " << y << " Expected y = "
                       << Y_NODES[ i ] << std::endl;
             std::string problem;
             problem  = " Mesh2D trying to read from file with different nodal";
             problem += " points.";
                     throw Error( problem );
                 }
             }
             else
             {
                 X_NODES[ i ] = x;
           Y_NODES[ j ] = y;
             }
       }
     }
     inFile.close();
   }
remesh()
template<class T > void Luna::Mesh2D< T >::remesh (const Vector< double > & newX, const Vector< double > & newY)
Interpolate the mesh data (bilinearly) into a new mesh.
Parameters
newX New x nodal points Vector
newY New y nodal points Vector
Definition at line 383 of file Mesh2D.h.
References Luna::Mesh2D< T >::coord(), Luna::Mesh2D< T >::get_nodes_vars(), and Luna::Vector< T >::size().
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     // check start & end
     if ( std::abs( X_NODES[ 0 ] - newX[ 0 ] ) > 1.e-10 ||
          std::abs( X_NODES[ X_NODES.size() - 1 ] - newX[ newX.size() - 1 ] )
          > 1.e-10 )
     {
       std::string problem;
       problem = " The Mesh2D.remesh1 method has been called with a passed \n";
       problem += " X coordinate vector that has different start and/or \n";
       problem += " end points from the instantiated object. \n";
       throw Error( problem );
     }
     // check monotonic node positions
     for ( std::size_t i = 0; i < newX.size() - 1; ++i )
     {
       if ( newX[ i ] >= newX[ i + 1 ] )
       {
         std::string problem;
         problem = " The Mesh2D.remesh1 method has been passed \n";
         problem += " a non-monotonic X coordinate vector. \n";
         throw Error( problem );
       }
     }
     // check start and end
     if ( std::abs( Y_NODES[ 0 ] - newY[ 0 ] ) > 1.e-10 ||
          std::abs( Y_NODES[ Y_NODES.size() - 1 ] - newY[ newY.size() - 1 ] )
          > 1.e-10 )
     {
       std::string problem;
       problem = " The Mesh2D.remesh1 method has been called with a passed \n";
       problem += " Y coordinate vector that has different start and/or \n";
       problem += " end points from the instantiated object. \n";
       throw Error( problem );
     }
     // check monotonic node positions
     for ( std::size_t i = 0; i < newY.size() - 1; ++i )
     {
       if ( newY[ i ] >= newY[ i + 1 ] )
       {
         std::string problem;
         problem = " The Mesh2D.remesh1 method has been passed \n";
         problem += " a non-monotonic Y coordinate vector. \n";
         throw Error( problem );
       }
     }
     // new variables storage
     Vector<T> newvars( newX.size() * newY.size() * NV, 0.0 );
     // left boundary
     {
       std::size_t xnode( 0 );
       // bottom left corner copy
       for ( unsigned var = 0; var < NV; ++var )
       {
         newvars[ ( xnode * newY.size() + 0 ) * NV + var ] =
                                                   get_nodes_vars( 0, 0 )[ var ];
       }
       for ( std::size_t ynode = 1; ynode < newY.size() - 1; ++ynode )
       {
         std::size_t left_i( 0 );  // bracketing index
         std::size_t below_j( 0 ); // bracketing index
         double deltaY( 0.0 );
         // loop through the source mesh and find the bracket-nodes
         for ( std::size_t j = 0; j < Y_NODES.size() - 1; ++j )
         {
           if ( ( Y_NODES[ j ] <= newY[ ynode ] ) &&
                ( newY[ ynode ] < Y_NODES[ j + 1 ] ) )
           {
             below_j = j;
             deltaY = newY[ ynode ] - Y_NODES[ j ];
           }
         }
         Vector<T> dvarsdY = ( get_nodes_vars( left_i, below_j + 1 )
                               - get_nodes_vars( left_i, below_j ) )
                            / ( coord( left_i, below_j + 1 ).second
                               - coord( left_i, below_j ).second );
         Vector<T> interpolated_vars =   get_nodes_vars( left_i, below_j )
                                       + dvarsdY * deltaY;
         for ( std::size_t var = 0; var < NV; ++var )
         {
           newvars[ ( xnode * newY.size() + ynode ) * NV + var ] =
                                                        interpolated_vars[ var ];
         }
       }
       // top left corner copy
       for ( std::size_t var = 0; var < NV; ++var )
       {
         newvars[ ( xnode * newY.size() + newY.size() - 1 ) * NV + var ] =
         get_nodes_vars( 0, NY - 1 )[ var ];
       }
     }
     // right boundary
     {
       std::size_t xnode( newX.size() - 1 );
       // bottom right corner copy
       for ( std::size_t var = 0; var < NV; ++var )
       {
         newvars[ ( xnode * newY.size() + 0 ) * NV + var ] =
         get_nodes_vars( NX - 1, 0 )[ var ];
       }
       for ( std::size_t ynode = 1; ynode < newY.size() - 1; ++ynode )
       {
         std::size_t left_i( X_NODES.size() - 1 );  // bracketing index
         std::size_t below_j( 0 ); // bracketing index
         double deltaY( 0.0 );
         // loop through the source mesh and find the bracket-nodes
         for ( std::size_t j = 0; j < Y_NODES.size() - 1; ++j )
         {
           if ( ( Y_NODES[ j ] <= newY[ ynode ] ) &&
                ( newY[ ynode ] < Y_NODES[ j + 1 ] ) )
           {
             below_j = j;
             deltaY = newY[ ynode ] - Y_NODES[ j ];
           }
         }
         Vector<T> dvarsdY = ( get_nodes_vars( left_i, below_j + 1 )
                               - get_nodes_vars( left_i, below_j ) )
                            / ( coord( left_i, below_j + 1 ).second
                               - coord( left_i, below_j ).second );
         Vector<T> interpolated_vars =   get_nodes_vars( left_i, below_j )
                                       + dvarsdY * deltaY;
         for ( std::size_t var = 0; var < NV; ++var )
         {
           newvars[ ( xnode * newY.size() + ynode ) * NV + var ] =
                                                        interpolated_vars[ var ];
         }
       }
       // bottom right corner copy
       for ( std::size_t var = 0; var < NV; ++var )
       {
         newvars[ ( xnode * newY.size() + newY.size() - 1 ) * NV + var ] =
         get_nodes_vars( NX - 1, NY - 1 )[ var ];
       }
     }
     // bottom boundary
     {
       std::size_t ynode( 0 );
       for ( std::size_t xnode = 1; xnode < newX.size() - 1; ++xnode )
       {
         std::size_t left_i( 0 );  // bracketing index
         std::size_t below_j( 0 ); // bracketing index
         double deltaX( 0.0 );
         // loop through the source mesh and find the bracket-nodes
         for ( std::size_t i = 0; i < X_NODES.size() - 1; ++i )
         {
           if ( ( X_NODES[ i ] <= newX[ xnode ] ) &&
                ( newX[ xnode ] < X_NODES[ i + 1 ] ) )
           {
             left_i = i;
             deltaX = newX[ xnode ] - X_NODES[ i ];
           }
         }
         Vector<T> dvarsdX = ( get_nodes_vars( left_i + 1, below_j )
                               - get_nodes_vars( left_i, below_j ) )
                            / ( coord( left_i + 1, below_j ).first
                               - coord( left_i, below_j ).first );
         Vector<T> interpolated_vars =   get_nodes_vars( left_i, below_j )
                                       + dvarsdX * deltaX;
         for ( std::size_t var = 0; var < NV; ++var )
         {
           newvars[ ( xnode * newY.size() + ynode ) * NV + var ] =
                                                        interpolated_vars[ var ];
         }
       }
     }
     // top boundary
     {
       std::size_t ynode( newY.size() - 1 );
       for ( std::size_t xnode = 1; xnode < newX.size() - 1; ++xnode )
       {
         std::size_t left_i( 0 );  // bracketing index
         std::size_t below_j( Y_NODES.size() - 1 ); // bracketing index
         double deltaX( 0.0 );
         // loop through the source mesh and find the bracket-nodes
         for ( std::size_t i = 0; i < X_NODES.size() - 1; ++i )
         {
           if ( ( X_NODES[ i ] <= newX[ xnode ] ) &&
                ( newX[ xnode ] < X_NODES[ i + 1 ] ) )
           {
             left_i = i;
             deltaX = newX[ xnode ] - X_NODES[ i ];
           }
         }
         Vector<T> dvarsdX = ( get_nodes_vars( left_i + 1, below_j )
                               - get_nodes_vars( left_i, below_j ) )
                            / ( coord( left_i + 1, below_j ).first
                               - coord( left_i, below_j ).first );
         Vector<T> interpolated_vars =   get_nodes_vars( left_i, below_j )
                                       + dvarsdX * deltaX;
         for ( std::size_t var = 0; var < NV; ++var )
         {
           newvars[ ( xnode * newY.size() + ynode ) * NV + var ] =
                                                        interpolated_vars[ var ];
         }
       }
     }
     // loop thru interior nodes of the destination mesh one node at a time
     for ( std::size_t xnode = 1; xnode < newX.size() - 1; ++xnode )
     {
       for ( std::size_t ynode = 1; ynode < newY.size() - 1; ++ynode )
       {
         std::size_t left_i( 0 );  // bracketing index
         std::size_t below_j( 0 ); // bracketing index
         // loop through the source mesh and find the bracket-nodes
         for ( std::size_t i = 0; i < X_NODES.size() - 1; ++i )
         {
           if ( ( X_NODES[ i ] <= newX[ xnode ] ) &&
                ( newX[ xnode ] < X_NODES[ i + 1 ] ) )
           {
             left_i = i;
           }
         }
         // loop through the source mesh and find the bracket-nodes
         for ( std::size_t j = 0; j < Y_NODES.size() - 1; ++j )
         {
           if ( ( Y_NODES[ j ] <= newY[ ynode ] ) &&
                ( newY[ ynode ] < Y_NODES[ j + 1 ] ) )
           {
             below_j = j;
           }
         }
         Vector<T> dvarsdX = ( get_nodes_vars( left_i + 1, below_j )
                               - get_nodes_vars( left_i, below_j ) )
                            / ( coord( left_i + 1, below_j ).first
                               - coord( left_i, below_j ).first );
         Vector<T> dvarsdY = ( get_nodes_vars( left_i, below_j + 1 )
                               - get_nodes_vars( left_i, below_j ) )
                            / ( coord( left_i, below_j + 1 ).second
                               - coord( left_i, below_j ).second );
         Vector<T> interpolated_vars_bottom =
                     ( get_nodes_vars( left_i, below_j ) *
                       ( coord( left_i + 1, below_j ).first - newX[ xnode ] )
                       + get_nodes_vars( left_i + 1, below_j )
                       * ( newX[ xnode ] - coord( left_i, below_j ).first ) )
                     / ( coord( left_i + 1, below_j ).first
                       - coord( left_i, below_j ).first );
         Vector<T> interpolated_vars_top =
           ( get_nodes_vars( left_i, below_j + 1 )
           * ( coord( left_i + 1, below_j + 1 ).first - newX[ xnode ] )
           + get_nodes_vars( left_i + 1, below_j + 1 )
           * ( newX[ xnode ] - coord( left_i, below_j + 1 ).first ) ) /
           ( coord( left_i + 1, below_j + 1 ).first
           - coord( left_i, below_j + 1 ).first );
         Vector<T> interpolated_vars =
           (  interpolated_vars_bottom * ( coord( left_i, below_j + 1 ).second
           - newY[ ynode ] ) +  interpolated_vars_top
           * ( newY[ ynode ] - coord( left_i, below_j ).second ) ) /
           ( coord( left_i, below_j + 1 ).second
           - coord( left_i, below_j ).second );
         for ( std::size_t var = 0; var < NV; ++var )
         {
           newvars[ ( xnode * newY.size() + ynode ) * NV + var ] =
                                                        interpolated_vars[ var ];
         }
       }
     }
     // finally replace the old nodes with the new ones
     X_NODES = newX;
     Y_NODES = newY;
     NX = newX.size();
     NY = newY.size();
     VARS = newvars;
   }
set_nodes_vars()
template<typename T > void Luna::Mesh2D< T >::set_nodes_vars (const std::size_t nodex, const std::size_t nodey, const Vector< T > & vec) inline
Set the variables stored at a specified node.
Parameters
nodex Node index (x-axis)
nodey Node index (y-axis)
vec Vector of variables
Definition at line 260 of file Mesh2D.h.
References Luna::Vector< T >::size().
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     if ( nodex > NX - 1 || nodey > NY - 1 || nodex < 0 || nodey < 0 )
     {
       std::string problem;
       problem = " The Mesh2D.set_nodes_vars method is trying to \n";
       problem += " access a nodal point that is not in the mesh. \n";
       throw Error( problem );
     }
     if ( vec.size() > NV )
     {
       std::string problem;
       problem = " The Mesh2D.set_nodes_vars method is using a vector that \n";
       problem += " has more entries than variables stored in the mesh. \n";
       throw Error( problem );
     }
     // assign contents of vec to the member data
     std::size_t offset( ( nodex * NY + nodey ) * NV );
     for ( std::size_t var = 0; var < NV; ++var )
     {
       VARS[ offset++ ] = vec[ var ];
     }
   }
square_integral2D()
template<typename T > T Luna::Mesh2D< T >::square_integral2D (std::size_t var = 0) const
Numerically integrate the square of the absolute value over the domain.
Parameters
var Variable index
Returns
The integral of the square of the absolute value over the domain
Definition at line 903 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     T sum( 0.0 );
     double dx( 0.0 );
     double dy( 0.0 );
     // Sum over the elements
     for ( std::size_t i=0; i < NX - 1; ++i )
     {
       dx = X_NODES[ i + 1 ] - X_NODES[ i ];
       for ( std::size_t j=0; j < NY - 1; ++j )
       {
         dy = Y_NODES[ j + 1 ] - Y_NODES[ j ];
         sum += 0.25 * dx * dy * (
             std::pow( std::abs( VARS[ ( i * NY + j ) * NV + var ] ), 2 )
           + std::pow( std::abs( VARS[ ( ( i + 1 ) * NY + j ) * NV + var ] ), 2 )
           + std::pow( std::abs( VARS[ ( i * NY + j + 1 ) * NV + var ] ), 2 )
           + std::pow( std::abs( VARS[ ( ( i + 1 ) * NY + j + 1 ) * NV + var ] )
                                                                         , 2 ) );
       }
     }
     return sum;
   }
xnodes()
template<typename T > const Vector< double > & Luna::Mesh2D< T >::xnodes () const
Return A vector of the x-nodal positions for this mesh.
Returns
A the mesh x nodes Vector
Definition at line 350 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     return X_NODES;
   }
ynodes()
template<typename T > const Vector< double > & Luna::Mesh2D< T >::ynodes () const
Return A vector of the y-nodal positions for this mesh.
Returns
A the mesh y nodes Vector
Definition at line 356 of file Mesh2D.h.
Referenced by Luna::Mesh2D< T >::~Mesh2D().
   {
     return Y_NODES;
   }
The documentation for this class was generated from the following file:
include/Luna/Mesh2D.h