Luna: Luna::Arclength< T > Class Template Reference
Luna::Arclength< T > Class Template Reference abstract
A templated arc length solver class.
#include <Arclength.h>
Public Member Functions
Arclength ()
Constructor.
virtual ~Arclength ()
Destructor.
void init_arc (Vector< T > x, T *ptr_param, const double &ds, const double &max_ds)
Initialise the arc-length continuation class.
virtual void solve (Vector< T > &x)=0
Solve the system for a given initial guess.
double & ds ()
A handle to the arc-length step.
double & arcstep_multiplier ()
A handle to the arc step multiplier.
bool & rescale_theta ()
A handle to the RESCALE_THETA flag.
double & theta ()
A handle to the theta parameter.
double & desired_arc_proportion ()
A handle to the desired proportion of the parameter to be used.
Protected Member Functions
void update (const Vector< T > &x)
Store the current converged state and parameter & compute derivatives.
double arclength_residual (const Vector< T > &x) const
Extra constraint that is to be used to replace the unknown arc-length.
Vector< T > Jac_arclength_residual (Vector< T > &x) const
Return the derivative of the arclength_residual function.
void update_theta (const Vector< T > &x)
Automatically update theta value only if RESCALE_THETA = true.
Protected Attributes
T * ptr_PARAM
Vector< T > LAST_X
Vector< T > X_DERIV_S
T LAST_PARAM
T PARAM_DERIV_S
double DS
double MAX_DS
double ARCSTEP_MULTIPLIER
bool INITIALISED
double THETA
Detailed Description
template<class T>
class Luna::Arclength< T >
A templated arc length solver class.
Definition at line 17 of file Arclength.h.
Constructor & Destructor Documentation
Arclength()
template<class T > Luna::Arclength< T >::Arclength () inline
Constructor.
Definition at line 58 of file Arclength.h.
                   : ARCSTEP_MULTIPLIER( 2.0 ),
                     INITIALISED( false ),
                     THETA( 0.5 ),
                     DESIRED_ARC_PROPORTION( 0.5 ),
                     RESCALE_THETA( false )
       {}
~Arclength()
template<class T > virtual Luna::Arclength< T >::~Arclength () inline virtual
Destructor.
Definition at line 66 of file Arclength.h.
References Luna::Arclength< T >::ds(), Luna::Arclength< T >::init_arc(), Luna::Arclength< T >::solve(), and Heat_plot::x.
 {}
Member Function Documentation
arclength_residual()
template<typename T > double Luna::Arclength< T >::arclength_residual (const Vector< T > & x) const protected
Extra constraint that is to be used to replace the unknown arc-length.
Parameters
x The current state Vector
Definition at line 115 of file Arclength.h.
References Luna::Arclength< T >::DS, Luna::Arclength< T >::LAST_PARAM, Luna::Arclength< T >::LAST_X, Luna::Arclength< T >::ptr_PARAM, Luna::Vector< T >::size(), and Luna::Arclength< T >::THETA.
Referenced by Luna::Newton< T >::arclength_solve(), and Luna::ODE_BVP< T, X >::arclength_solve().
   {
     return THETA * ( x - LAST_X ).norm_2() / x.size() + ( 1.0 - THETA )
                * std::pow( std::abs( *ptr_PARAM - LAST_PARAM ), 2 ) - DS * DS;
   }
arcstep_multiplier()
template<class T > double& Luna::Arclength< T >::arcstep_multiplier () inline
A handle to the arc step multiplier.
Returns
The arc-length step multiplier
Definition at line 88 of file Arclength.h.
References Luna::Arclength< T >::ARCSTEP_MULTIPLIER.
 { return ARCSTEP_MULTIPLIER; }
desired_arc_proportion()
template<class T > double& Luna::Arclength< T >::desired_arc_proportion () inline
A handle to the desired proportion of the parameter to be used.
Returns
The desired proportion of the arc-length
Definition at line 100 of file Arclength.h.
 { return DESIRED_ARC_PROPORTION; }
ds()
template<class T > double& Luna::Arclength< T >::ds () inline
A handle to the arc-length step.
Returns
The arc-length step
Definition at line 84 of file Arclength.h.
References Luna::Arclength< T >::DS.
Referenced by Luna::ODE_BVP< T, X >::arclength_solve(), Luna::Arclength< T >::init_arc(), and Luna::Arclength< T >::~Arclength().
 { return DS; }
init_arc()
template<class T > void Luna::Arclength< T >::init_arc (Vector< T > x, T * ptr_param, const double & ds, const double & max_ds)
Initialise the arc-length continuation class.
Parameters
x The current state Vector
ptr_param Pointer to the arc-length parameter
ds The size of the arc-length step
max_ds The maximum arc-length step to be taken
Definition at line 143 of file Arclength.h.
References Luna::Arclength< T >::DS, Luna::Arclength< T >::ds(), Luna::Arclength< T >::INITIALISED, Luna::Arclength< T >::LAST_PARAM, Luna::Arclength< T >::LAST_X, Luna::Arclength< T >::MAX_DS, Luna::Arclength< T >::ptr_PARAM, Luna::Arclength< T >::solve(), Luna::Arclength< T >::update(), and Heat_plot::x.
Referenced by Luna::ODE_BVP< T, X >::init_arc(), main(), and Luna::Arclength< T >::~Arclength().
   {
     ptr_PARAM = ptr_param;
     solve( x );
     LAST_X = x;
     LAST_PARAM = *ptr_PARAM;
     // We now have one solution which we can use to arc-length continue
     DS = ds;
     *ptr_PARAM += DS;
     // Recompute the state at this new parameter value
     solve( x );
     update( x );
     INITIALISED = true;
     MAX_DS = max_ds;
   }
Jac_arclength_residual()
template<typename T > Vector< T > Luna::Arclength< T >::Jac_arclength_residual (Vector< T > & x) const protected
Return the derivative of the arclength_residual function.
with respect to each state variable
Parameters
x The current state Vector
Returns
The derivative of the arclength_residual function
Definition at line 122 of file Arclength.h.
References Luna::Arclength< T >::LAST_X, Luna::Vector< T >::size(), and Luna::Arclength< T >::THETA.
Referenced by Luna::Newton< T >::arclength_solve(), and Luna::ODE_BVP< T, X >::arclength_solve().
     {
         Vector<T> Jx( x - LAST_X );
         Jx = Jx * ( THETA / ( x.size() * ( x - LAST_X ).norm_2() ) );
         return Jx;
     }
rescale_theta()
template<class T > bool& Luna::Arclength< T >::rescale_theta () inline
A handle to the RESCALE_THETA flag.
Returns
The theta rescale flag
Definition at line 92 of file Arclength.h.
 { return RESCALE_THETA; }
solve()
template<class T > void Luna::Arclength< T >::solve (Vector< T > & x) pure virtual
Solve the system for a given initial guess.
Parameters
x The current state Vector
Implemented in Luna::Newton< T >.
Definition at line 161 of file Arclength.h.
Referenced by Luna::Arclength< T >::init_arc(), and Luna::Arclength< T >::~Arclength().
 {}
theta()
template<class T > double& Luna::Arclength< T >::theta () inline
A handle to the theta parameter.
Returns
The Theta weighting parameter
Definition at line 96 of file Arclength.h.
References Luna::Arclength< T >::THETA.
 { return THETA; }
update()
template<typename T > void Luna::Arclength< T >::update (const Vector< T > & x) protected
Store the current converged state and parameter & compute derivatives.
Parameters
x The current state Vector
Definition at line 105 of file Arclength.h.
References Luna::Arclength< T >::DS, Luna::Arclength< T >::LAST_PARAM, Luna::Arclength< T >::LAST_X, Luna::Arclength< T >::PARAM_DERIV_S, Luna::Arclength< T >::ptr_PARAM, Luna::Arclength< T >::update_theta(), Heat_plot::x, and Luna::Arclength< T >::X_DERIV_S.
Referenced by Luna::ODE_BVP< T, X >::adapt(), Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), Luna::Arclength< T >::init_arc(), and Luna::Newton< T >::iterate().
   {
     if ( RESCALE_THETA ) { update_theta( x ); }
     X_DERIV_S = ( x - LAST_X ) / DS;
     PARAM_DERIV_S = ( *ptr_PARAM - LAST_PARAM ) / DS;
     LAST_X = x;
     LAST_PARAM = *ptr_PARAM;
   }
update_theta()
template<class T > void Luna::Arclength< T >::update_theta (const Vector< T > & x) protected
Automatically update theta value only if RESCALE_THETA = true.
Parameters
x The current state Vector
Definition at line 130 of file Arclength.h.
References Luna::Arclength< T >::LAST_PARAM, Luna::Arclength< T >::LAST_X, Luna::Arclength< T >::ptr_PARAM, Luna::Vector< T >::size(), and Luna::Arclength< T >::THETA.
Referenced by Luna::Arclength< T >::update().
   {
     if ( RESCALE_THETA )
     {
       double Delta_p2 = std::pow( std::abs( *ptr_PARAM - LAST_PARAM ), 2);
       double Delta_x2 = ( x - LAST_X ).norm_2() / x.size();
       THETA = Delta_p2 * ( DESIRED_ARC_PROPORTION - 1.0 ) /
              ( Delta_p2 * ( DESIRED_ARC_PROPORTION - 1.0 )
               - DESIRED_ARC_PROPORTION * Delta_x2 );
     }
   }
Member Data Documentation
ARCSTEP_MULTIPLIER
template<class T > double Luna::Arclength< T >::ARCSTEP_MULTIPLIER protected
Definition at line 27 of file Arclength.h.
Referenced by Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), and Luna::Arclength< T >::arcstep_multiplier().
DS
template<class T > double Luna::Arclength< T >::DS protected
Definition at line 25 of file Arclength.h.
Referenced by Luna::Arclength< T >::arclength_residual(), Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), Luna::Arclength< T >::ds(), Luna::Arclength< T >::init_arc(), and Luna::Arclength< T >::update().
INITIALISED
template<class T > bool Luna::Arclength< T >::INITIALISED protected
Definition at line 28 of file Arclength.h.
Referenced by Luna::Newton< T >::arclength_solve(), and Luna::Arclength< T >::init_arc().
LAST_PARAM
template<class T > T Luna::Arclength< T >::LAST_PARAM protected
Definition at line 23 of file Arclength.h.
Referenced by Luna::Arclength< T >::arclength_residual(), Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), Luna::Arclength< T >::init_arc(), Luna::Arclength< T >::update(), and Luna::Arclength< T >::update_theta().
LAST_X
template<class T > Vector<T> Luna::Arclength< T >::LAST_X protected
Definition at line 21 of file Arclength.h.
Referenced by Luna::Arclength< T >::arclength_residual(), Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), Luna::Arclength< T >::init_arc(), Luna::Arclength< T >::Jac_arclength_residual(), Luna::Arclength< T >::update(), and Luna::Arclength< T >::update_theta().
MAX_DS
template<class T > double Luna::Arclength< T >::MAX_DS protected
Definition at line 26 of file Arclength.h.
Referenced by Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), and Luna::Arclength< T >::init_arc().
PARAM_DERIV_S
template<class T > T Luna::Arclength< T >::PARAM_DERIV_S protected
Definition at line 24 of file Arclength.h.
Referenced by Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), and Luna::Arclength< T >::update().
ptr_PARAM
template<class T > T* Luna::Arclength< T >::ptr_PARAM protected
Definition at line 20 of file Arclength.h.
Referenced by Luna::Arclength< T >::arclength_residual(), Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), Luna::Arclength< T >::init_arc(), Luna::Arclength< T >::update(), and Luna::Arclength< T >::update_theta().
THETA
template<class T > double Luna::Arclength< T >::THETA protected
Definition at line 29 of file Arclength.h.
Referenced by Luna::Arclength< T >::arclength_residual(), Luna::Arclength< T >::Jac_arclength_residual(), Luna::Arclength< T >::theta(), and Luna::Arclength< T >::update_theta().
X_DERIV_S
template<class T > Vector<T> Luna::Arclength< T >::X_DERIV_S protected
Definition at line 22 of file Arclength.h.
Referenced by Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), and Luna::Arclength< T >::update().
The documentation for this class was generated from the following file:
include/Luna/Arclength.h