Luna: Luna::BandedMatrix< T > Class Template Reference
Luna::BandedMatrix< T > Class Template Reference
A banded matrix class for use with double and std::complex<double>
#include <BandedMatrix.h>
Public Member Functions
BandedMatrix (const std::size_t &n, const std::size_t &m1, const std::size_t &m2)
Constructor for a BandedMatrix of specfied size and number of bands.
BandedMatrix (const Matrix< T > &mat, const std::size_t &m1, const std::size_t &m2)
Constructor for a BandedMatrix from a dense Matrix.
~BandedMatrix ()
Destructor.
const T & operator() (const int &i, const int &j) const
Indexing operator (read only)
T & operator() (const int &i, const int &j)
Indexing operator (read / write)
BandedMatrix< T > & operator= (const BandedMatrix< T > &original)
Copy assignment.
BandedMatrix< T > operator+ () const
Unary +.
BandedMatrix< T > operator- () const
Unary -.
BandedMatrix< T > operator+ (const BandedMatrix< T > &m_plus) const
Binary +.
BandedMatrix< T > operator- (const BandedMatrix< T > &m_minus) const
Binary -.
BandedMatrix< T > operator* (const T &scalar) const
Scalar multiplication.
BandedMatrix< T > operator/ (const T &divisor) const
Scalar division.
BandedMatrix< T > & operator+= (const BandedMatrix< T > &m_plus)
Addition assignment.
BandedMatrix< T > & operator-= (const BandedMatrix< T > &m_minus)
Subtraction assignment.
BandedMatrix< T > & operator*= (const T &scalar)
Scalar multiplication assignment.
BandedMatrix< T > & operator/= (const T &divisor)
Scalar division assigment.
BandedMatrix< T > & operator+= (const T &add)
Constant addition assignment.
BandedMatrix< T > & operator-= (const T &minus)
Constant subtraction assignment.
Vector< T > operator* (Vector< T > &x)
BandedMatrix Vector multiplication (B * x)
Matrix< T > compact ()
Return the BandedMatrix stored in compact form.
std::size_t size ()
Return the size of the BandedMatrix.
std::size_t size_below ()
Return the number of bands below the main diagonal.
std::size_t size_above ()
Return the number of bands above the main diagonal.
void fill (const T &elem)
Fill the Matrix with specified elements.
Vector< T > solve (const Vector< T > &b)
Solve the banded system of equations Ax=b where x and b are Vectors.
Matrix< T > solve (const Matrix< T > &B)
Solve the banded system of equations AX=B where X and B are Matrices.
T det ()
Calculate the determinant of the matrix.
Friends
template<class Type >
std::ostream & operator<< (std::ostream &os, const BandedMatrix< Type > &m)
Output operator <<.
BandedMatrix< T > operator* (const T &scalar, BandedMatrix< T > &mat)
Detailed Description
template<class T>
class Luna::BandedMatrix< T >
A banded matrix class for use with double and std::complex<double>
Definition at line 24 of file BandedMatrix.h.
Constructor & Destructor Documentation
BandedMatrix() [1/2]
template<typename T > Luna::BandedMatrix< T >::BandedMatrix (const std::size_t & n, const std::size_t & m1, const std::size_t & m2) inline
Constructor for a BandedMatrix of specfied size and number of bands.
Parameters
n The size of the matrix (n x n)
m1 The number of bands below the main diagonal
m2 The number of bands above the main diagonal
Definition at line 190 of file BandedMatrix.h.
                                                : N( n ), M1( m1 ), M2( m2 )
   {
     COMPACT.resize( n, m1 + m2 + 1 );
   }
BandedMatrix() [2/2]
template<typename T > Luna::BandedMatrix< T >::BandedMatrix (const Matrix< T > & mat, const std::size_t & m1, const std::size_t & m2) inline
Constructor for a BandedMatrix from a dense Matrix.
Parameters
mat The dense Matrix used to create the BandedMatrix
m1 The number of bands below the main diagonal
m2 The number of bands above the main diagonal
Definition at line 197 of file BandedMatrix.h.
References Luna::Matrix< T >::cols(), and Luna::Matrix< T >::rows().
                                                : M1( m1 ), M2( m2 )
   {
     N = mat.rows();
     if ( N != mat.cols() )
     {
       throw Error( "BandedMatrix constructor error: Matrix is not square.");
     }
     COMPACT.resize( N, m1 + m2 + 1 );
     for ( std::size_t i = 0; i < N; i++ ) // Fill the BandedMatrix
     {
       for ( std::size_t j = 0; j < N; j++ )
       {
         if ( i <= j + M1 && j <= i + M2 )
         {
           COMPACT( i, j - i + M1 ) = mat( i, j );
         }
       }
     }
   }
~BandedMatrix()
template<class T> Luna::BandedMatrix< T >::~BandedMatrix () inline
Destructor.
Definition at line 53 of file BandedMatrix.h.
References Luna::BandedMatrix< T >::operator()(), Luna::BandedMatrix< T >::operator*(), Luna::BandedMatrix< T >::operator+(), Luna::BandedMatrix< T >::operator-(), Luna::BandedMatrix< T >::operator<<, and Luna::BandedMatrix< T >::operator=().
 {}
Member Function Documentation
compact()
template<typename T > Matrix< T > Luna::BandedMatrix< T >::compact () inline
Return the BandedMatrix stored in compact form.
Returns
A Matrix containing the compact form of the BandedMatrix
Definition at line 416 of file BandedMatrix.h.
   {
     return COMPACT;
   }
det()
template<typename T > T Luna::BandedMatrix< T >::det () inline
Calculate the determinant of the matrix.
Returns
The determinant of the BandedMatrix
Definition at line 541 of file BandedMatrix.h.
References Spectral_ODE_Rational_plot::index, Luna::Vector< T >::resize(), and Luna::Matrix< T >::resize().
Referenced by main(), and Luna::ODE_BVP< T, X >::solve_bvp().
   {
     Matrix<T> au, al;
     Vector<int> index;
     double d;
     au = COMPACT;
     al.resize( N, M1 );
     index.resize( N );
     decompose( au, al, index, d );
     T dd = d;
     for ( int i = 0; i < N; i++ ) {
       dd *= au( i, 0 );
     }
     return dd;
   }
fill()
template<typename T > void Luna::BandedMatrix< T >::fill (const T & elem) inline
Fill the Matrix with specified elements.
Parameters
elem The element to fill the Matrix with
Definition at line 440 of file BandedMatrix.h.
Referenced by Luna::ODE_BVP< T, X >::arclength_solve().
   {
     COMPACT.fill( elem );
   }
operator()() [1/2]
template<typename T > const T & Luna::BandedMatrix< T >::operator() (const int & i, const int & j) const inline
Indexing operator (read only)
Parameters
i Row index
j Column index
Definition at line 246 of file BandedMatrix.h.
Referenced by Luna::BandedMatrix< T >::~BandedMatrix().
   {
     if ( i < 0 )    { throw Error( "BandedMatrix range error: row < 0." ); }
     if ( j < 0 )    { throw Error( "BandedMatrix range error: column < 0." ); }
     if ( j > i + M2 || i > j + M1 )
     {
       throw Error( "BandedMatrix range error: index not in a band." );
     }
     return COMPACT( i, j - i + M1 );
   }
operator()() [2/2]
template<typename T > T & Luna::BandedMatrix< T >::operator() (const int & i, const int & j) inline
Indexing operator (read / write)
Parameters
i Row index
j Column index
Definition at line 259 of file BandedMatrix.h.
   {
     if ( i < 0 )    { throw Error( "BandedMatrix range error: row < 0." ); }
     if ( j < 0 )    { throw Error( "BandedMatrix range error: column < 0." ); }
     if ( j > i + M2 || i > j + M1 )
     {
       throw Error( "BandedMatrix range error: index not in a band." );
     }
     return COMPACT( i, j - i + M1 );
   }
operator*() [1/2]
template<typename T > BandedMatrix< T > Luna::BandedMatrix< T >::operator* (const T & scalar) const inline
Scalar multiplication.
Parameters
scalar The scalar to multiply the BandedMatrix by
Returns
The BandedMatrix multiplied by the scalar
Definition at line 326 of file BandedMatrix.h.
Referenced by Luna::BandedMatrix< T >::~BandedMatrix().
   {
     BandedMatrix<T> temp( *this );
     temp.COMPACT = COMPACT * scalar;
     return temp;
   }
operator*() [2/2]
template<typename T > Vector< T > Luna::BandedMatrix< T >::operator* (Vector< T > & x) inline
BandedMatrix Vector multiplication (B * x)
Parameters
x The Vector which is to be multiplied
Returns
The result vector B * x
Definition at line 394 of file BandedMatrix.h.
References Luna::Vector< T >::size().
   {
     if ( N != x.size() )
     {
       throw Error( "BandedMatrix: dimensions do not agree in multiply method.");
     }
     Vector<T> result( N );
     int i, j, k, tmploop;
     for ( i = 0; i < N; i++ ) {
         k = i - M1;
         tmploop = std::min( M1 + M2 + 1, N - k );
         result[ i ] = 0.0;
         for ( j = std::max( 0, - k ); j < tmploop; j++ ){
         result[ i ] += COMPACT( i, j ) * x[ j + k ];
       }
     }
     return result;
   }
operator*=()
template<typename T > BandedMatrix< T > & Luna::BandedMatrix< T >::operator*= (const T & scalar) inline
Scalar multiplication assignment.
Parameters
scalar The scalar to multiply the BandedMatrix by
Returns
A reference to the BandedMatrix after multiplication by a scalar
Definition at line 366 of file BandedMatrix.h.
   {
     COMPACT *= scalar;
     return *this;
   }
operator+() [1/2]
template<typename T > BandedMatrix< T > Luna::BandedMatrix< T >::operator+ () const inline
Unary +.
Returns
The BandedMatrix
Definition at line 286 of file BandedMatrix.h.
Referenced by Luna::BandedMatrix< T >::~BandedMatrix().
   {
     return *this;
   }
operator+() [2/2]
template<typename T > BandedMatrix< T > Luna::BandedMatrix< T >::operator+ (const BandedMatrix< T > & m_plus) const inline
Binary +.
Parameters
m_plus The BandedMatrix to be added
Returns
The sum of this BandedMatrix and m_plus
Definition at line 300 of file BandedMatrix.h.
   {
     BandedMatrix<T> temp( *this );
     if ( m_plus.N != N || m_plus.M1 != M1 || m_plus.M2 != M2  )
     {
       throw Error( "BandedMatrix dimension error in + operator." );
     }
     temp.COMPACT = COMPACT + m_plus.COMPACT;
     return temp;
   }
operator+=() [1/2]
template<typename T > BandedMatrix< T > & Luna::BandedMatrix< T >::operator+= (const BandedMatrix< T > & m_plus) inline
Addition assignment.
Parameters
m_plus The BandedMatrix to be added
Returns
A reference to the BandedMatrix after addition by m_plus
Definition at line 342 of file BandedMatrix.h.
   {
     if ( m_plus.N != N || m_plus.M1 != M1 || m_plus.M2 != M2 )
     {
       throw Error( "BandedMatrix dimension error in += operator." );
     }
     COMPACT = COMPACT + m_plus.COMPACT;
     return *this;
   }
operator+=() [2/2]
template<typename T > BandedMatrix< T > & Luna::BandedMatrix< T >::operator+= (const T & add) inline
Constant addition assignment.
Parameters
add The constant to be added to each element
Returns
A reference to the BandedMatrix after addition by a constant
Definition at line 380 of file BandedMatrix.h.
   {
     COMPACT += add;
     return *this;
   }
operator-() [1/2]
template<typename T > BandedMatrix< T > Luna::BandedMatrix< T >::operator- () const inline
Unary -.
Returns
The negation of the BandedMatrix
Definition at line 292 of file BandedMatrix.h.
Referenced by Luna::BandedMatrix< T >::~BandedMatrix().
   {
     BandedMatrix<T> temp( *this );
     temp.COMPACT = - COMPACT;
     return temp;
   }
operator-() [2/2]
template<typename T > BandedMatrix< T > Luna::BandedMatrix< T >::operator- (const BandedMatrix< T > & m_minus) const inline
Binary -.
Parameters
m_minus The BandedMatrix to be subtracted
Returns
The subtraction of m_minus from this BandedMatrix
Definition at line 313 of file BandedMatrix.h.
   {
     BandedMatrix<T> temp( *this );
     if ( m_minus.N != N || m_minus.M1 != M1 || m_minus.M2 != M2 )
     {
       throw Error( "BandedMatrix dimension error in - operator." );
     }
     temp.COMPACT = COMPACT - m_minus.COMPACT;
     return temp;
   }
operator-=() [1/2]
template<typename T > BandedMatrix< T > & Luna::BandedMatrix< T >::operator-= (const BandedMatrix< T > & m_minus) inline
Subtraction assignment.
Parameters
m_minus The BandedMatrix to be subtracted
Returns
A reference to the BandedMatrix after subtraction by m_minus
Definition at line 354 of file BandedMatrix.h.
   {
     if ( m_minus.N != N || m_minus.M1 != M1 || m_minus.M2 != M2 )
     {
       throw Error( "BandedMatrix dimension error in -= operator." );
     }
     COMPACT = COMPACT - m_minus.COMPACT;
     return *this;
   }
operator-=() [2/2]
template<typename T > BandedMatrix< T > & Luna::BandedMatrix< T >::operator-= (const T & minus) inline
Constant subtraction assignment.
Parameters
minus The constant to be subtracted from each element
Returns
A reference to the BandedMatrix after subtraction by a constant
Definition at line 387 of file BandedMatrix.h.
   {
     COMPACT -= minus;
     return *this;
   }
operator/()
template<typename T > BandedMatrix< T > Luna::BandedMatrix< T >::operator/ (const T & divisor) const inline
Scalar division.
Parameters
divisor The divisor to divide the BandedMatrix by
Returns
The BandedMatrix divided by the divisor
Definition at line 334 of file BandedMatrix.h.
   {
     BandedMatrix<T> temp( *this );
     temp.COMPACT = COMPACT / divisor;
     return temp;
   }
operator/=()
template<typename T > BandedMatrix< T > & Luna::BandedMatrix< T >::operator/= (const T & divisor) inline
Scalar division assigment.
Parameters
divisor The divisor to divide the BandedMatrix by
Returns
A reference to the BandedMatrix after division by a scalar
Definition at line 373 of file BandedMatrix.h.
   {
     COMPACT /= divisor;
     return *this;
   }
operator=()
template<typename T > BandedMatrix< T > & Luna::BandedMatrix< T >::operator= (const BandedMatrix< T > & original) inline
Copy assignment.
Parameters
original BandedMatrix to be copied
Returns
The BandedMatrix to which the original matrix is assigned
Definition at line 271 of file BandedMatrix.h.
Referenced by Luna::BandedMatrix< T >::~BandedMatrix().
   {
     if ( this == &original )
     {
       return *this;
     }
     N = original.N;
     M1 = original.M1;
     M2 = original.M2;
     COMPACT = original.COMPACT;
     return *this;
   }
size()
template<typename T > std::size_t Luna::BandedMatrix< T >::size () inline
Return the size of the BandedMatrix.
Returns
The size of the BandedMatrix
Definition at line 422 of file BandedMatrix.h.
Referenced by main().
   {
     return N;
   }
size_above()
template<typename T > std::size_t Luna::BandedMatrix< T >::size_above () inline
Return the number of bands above the main diagonal.
Returns
The number of bands above the main diagonal
Definition at line 434 of file BandedMatrix.h.
Referenced by main().
   {
     return M2;
   }
size_below()
template<typename T > std::size_t Luna::BandedMatrix< T >::size_below () inline
Return the number of bands below the main diagonal.
Returns
The number of bands below the main diagonal
Definition at line 428 of file BandedMatrix.h.
Referenced by main().
   {
     return M1;
   }
solve() [1/2]
template<typename T > Vector< T > Luna::BandedMatrix< T >::solve (const Vector< T > & b) inline
Solve the banded system of equations Ax=b where x and b are Vectors.
Parameters
b The right-side Vector of the system of equations
Returns
The solution Vector x
Definition at line 448 of file BandedMatrix.h.
References Spectral_ODE_Rational_plot::index, Luna::Vector< T >::resize(), Luna::Matrix< T >::resize(), Luna::Vector< T >::size(), and Heat_plot::x.
Referenced by Luna::ODE_BVP< T, X >::arclength_solve(), main(), and Luna::ODE_BVP< T, X >::solve_bvp().
   {
     if ( b.size() != N ) {
       throw Error( "BandedMatrix solve error: Vector incorrect size." );
     }
     // LU decomposition
     Matrix<T> au, al;
     Vector<int> index;
     double d;
     au = COMPACT;
     al.resize( N, M1 );
     index.resize( N );
     decompose( au, al, index, d );
     // Solve the system
     Vector<T> x( b );
     int i, j, k, l, mm;
     T dum;
     mm = M1 + M2 + 1;
     l = M1;
     for ( k = 0; k < N; k++ ) {
       j = index[ k ] - 1;
       if ( j != k ) std::swap( x[ k ], x[ j ] );
       if ( l < N ) l++;
       for ( j = k + 1; j < l; j++ ){
         x[ j ] -= al( k, j - k - 1 ) * x[ k ];
       }
     }
     l = 1;
     for ( i = N - 1; i >= 0; i-- ) {
       dum = x[ i ];
       for ( k = 1; k < l; k++ ) {
         dum -= au( i, k ) * x[ k + i ];
       }
       x[ i ] = dum / au( i, 0 );
       if ( l < mm ) l++;
     }
     return x;
   }
solve() [2/2]
template<typename T > Matrix< T > Luna::BandedMatrix< T >::solve (const Matrix< T > & B) inline
Solve the banded system of equations AX=B where X and B are Matrices.
Parameters
B The right-hand side Matrix of the system of equations
Returns
The solution Matrix (each column is a solution Vector)
Definition at line 490 of file BandedMatrix.h.
References Luna::Matrix< T >::cols(), Luna::Matrix< T >::get_col(), Spectral_ODE_Rational_plot::index, Luna::Vector< T >::resize(), Luna::Matrix< T >::resize(), Luna::Matrix< T >::rows(), Luna::Matrix< T >::set_col(), and Heat_plot::x.
   {
     if ( B.rows() != N ) {
       throw Error( "BandedMatrix solve error: Matrix rows incorrect size." );
     }
     Matrix<T> X( B );
     // LU decomposition
     Matrix<T> au, al;
     Vector<int> index;
     double d;
     au = COMPACT;
     al.resize( N, M1 );
     index.resize( N );
     decompose( au, al, index, d );
     Vector<T> x( N );
     int i, j, k, l, mm;
     T dum;
     mm = M1 + M2 + 1;
     for ( std::size_t col = 0; col < B.cols(); ++col )
     {
       // Solve the system for each column
       x = X.get_col( col );
       l = M1;
       for ( k = 0; k < N; k++ ) {
         j = index[ k ] - 1;
         if ( j != k ) std::swap( x[ k ], x[ j ] );
         if ( l < N ) l++;
         for ( j = k + 1; j < l; j++ ){
           x[ j ] -= al( k, j - k - 1 ) * x[ k ];
         }
       }
       l = 1;
       for ( i = N - 1; i >= 0; i-- ) {
         dum = x[ i ];
         for ( k = 1; k < l; k++ ) {
           dum -= au( i, k ) * x[ k + i ];
         }
         x[ i ] = dum / au( i, 0 );
         if ( l < mm ) l++;
       }
       X.set_col( col, x );
     }
     return X;
   }
Friends And Related Function Documentation
operator*
template<class T> BandedMatrix<T> operator* (const T & scalar, BandedMatrix< T > & mat) friend
Definition at line 99 of file BandedMatrix.h.
     {
       return mat * scalar;
     }
operator<<
template<class T> template<class Type > std::ostream& operator<< (std::ostream & os, const BandedMatrix< Type > & m) friend
Output operator <<.
Definition at line 221 of file BandedMatrix.h.
Referenced by Luna::BandedMatrix< T >::~BandedMatrix().
   {
     os << std::endl;
     if ( m.N == 0 ) { return os; }
     if ( m.N > 0 )
     {
       for ( std::size_t i = 0; i < m.N; ++i )
       {
         for ( std::size_t j = 0; j < m.N; ++j )
         {
           if ( j > i + m.M2 || i > j + m.M1 )
           {
             os << "\t";
           } else {
             os << "\t" << m.COMPACT( i, j - i + m.M1 );
           }
         }
         os << std::endl;
       }
     }
     return os;
   }
The documentation for this class was generated from the following file:
include/Luna/BandedMatrix.h