Luna: Luna::Spectral< T > Class Template Reference
Luna::Spectral< T > Class Template Reference
A templated class for spectral solutions.
#include <Spectral.h>
Public Member Functions
Spectral ()
Constructor (default = no coefficients and Chebyshev basis)
Spectral (const Vector< T > &coefficients, const std::string &basis)
Constructor with specified basis and coefficients.
Spectral (const Vector< T > &coefficients, const std::string &basis, const double &param)
Constructor with specified basis, coefficients and extra parameter.
~Spectral ()
Destructor.
T operator() (const T &x)
Evaluation operator at a point x.
Vector< T > operator() (const Vector< T > &x)
Evaluation operator at a Vector of points.
T operator() (const T &x, const int &d)
Evaluation operator for the dth derivative of the spectral function at point x.
Vector< T > operator() (const Vector< T > &x, const int &d)
Evaluation operator for the dth derivative of the spectral function at a Vector of points.
const T & operator[] (const std::size_t &i) const
Indexing operator (read only)
T & operator[] (const std::size_t &i)
Indexing operator (read / write)
std::string get_basis ()
Return the basis specifier string.
void set_basis (const std::string &basis)
Set the basis specifier string.
Vector< T > get_coefficients ()
Return the spectral coefficients.
void set_coefficients (const Vector< T > &coeffs)
Set the spectral coefficients.
void update_coefficients (const Vector< T > &update)
Update the spectral coefficients (add a Vector to the Vector of coefficients)
void push_back (const T &new_elem)
Add a new coefficient to the back of the Vector of coefficients.
void push_front (const T &new_elem)
Add a new coefficient to the front of the Vector of coefficients.
double & parameter ()
Return a pointer to the extra parameter.
Detailed Description
template<class T>
class Luna::Spectral< T >
A templated class for spectral solutions.
Definition at line 25 of file Spectral.h.
Constructor & Destructor Documentation
Spectral() [1/3]
template<typename T > Luna::Spectral< T >::Spectral ()
Constructor (default = no coefficients and Chebyshev basis)
Definition at line 130 of file Spectral.h.
     {
         BASIS = "Chebyshev";
     }
Spectral() [2/3]
template<typename T > Luna::Spectral< T >::Spectral (const Vector< T > & coefficients, const std::string & basis)
Constructor with specified basis and coefficients.
Parameters
coefficients The Vector of coefficients
basis The basis specifier string (i.e. Chebyshev)
Definition at line 136 of file Spectral.h.
     {
         if ( basis != "Chebyshev" && basis != "EvenChebyshev"
           && basis != "OddChebyshev" && basis != "RationalSemi" )
             //&& basis != "Fourier" )
         {
             std::string problem;
             problem += "Spectral set_basis error: The basis function " + basis + "\n";
             problem += "is not supported.";
             throw Error( problem );
         }
         COEFFICIENTS = coefficients;
         BASIS = basis;
         PARAM = 1.0;
     }
Spectral() [3/3]
template<typename T > Luna::Spectral< T >::Spectral (const Vector< T > & coefficients, const std::string & basis, const double & param)
Constructor with specified basis, coefficients and extra parameter.
Parameters
coefficients The Vector of coefficients
basis The basis specifier string (i.e. Chebyshev)
param An extra parameter for use with rational Chebyshev basis
Definition at line 154 of file Spectral.h.
     {
         if ( basis != "Chebyshev" && basis != "EvenChebyshev"
           && basis != "OddChebyshev" && basis != "RationalSemi" )
             //&& basis != "Fourier" )
         {
             std::string problem;
             problem += "Spectral set_basis error: The basis function " + basis + "\n";
             problem += "is not supported.";
             throw Error( problem );
         }
         COEFFICIENTS = coefficients;
         BASIS = basis;
         PARAM = param;
     }
~Spectral()
template<class T> Luna::Spectral< T >::~Spectral () inline
Destructor.
Definition at line 50 of file Spectral.h.
References Luna::Spectral< T >::get_basis(), Luna::Spectral< T >::get_coefficients(), Luna::Spectral< T >::operator()(), Luna::Spectral< T >::operator[](), Luna::Spectral< T >::parameter(), Luna::Spectral< T >::push_back(), Luna::Spectral< T >::push_front(), Luna::Spectral< T >::set_basis(), Luna::Spectral< T >::set_coefficients(), Luna::Spectral< T >::update_coefficients(), and Heat_plot::x.
 {}
Member Function Documentation
get_basis()
template<typename T > std::string Luna::Spectral< T >::get_basis ()
Return the basis specifier string.
Returns
The string containing the basis specifier
Definition at line 376 of file Spectral.h.
Referenced by Luna::Spectral< T >::~Spectral().
     {
         return BASIS;
     }
get_coefficients()
template<typename T > Vector< T > Luna::Spectral< T >::get_coefficients ()
Return the spectral coefficients.
Returns
The Vector of spectral coefficients
Definition at line 397 of file Spectral.h.
Referenced by main(), and Luna::Spectral< T >::~Spectral().
     {
         return COEFFICIENTS;
     }
operator()() [1/4]
template<typename T > T Luna::Spectral< T >::operator() (const T & x) inline
Evaluation operator at a point x.
Parameters
x The point where the spectral function is evaluated
Returns
The value of the spectral function at x
Definition at line 174 of file Spectral.h.
References Heat_plot::N.
Referenced by Luna::Spectral< T >::~Spectral().
     {
         T temp( 0 );
         std::size_t N( COEFFICIENTS.size() );
         if ( BASIS == "Chebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, n ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "EvenChebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, 2 * n ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "OddChebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, 2 * n + 1 ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "RationalSemi" )
         {
             RationalSemi<T> basis( PARAM );
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, n ) * COEFFICIENTS[ n ];
             }
         }
         return temp;
     }
operator()() [2/4]
template<typename T > Vector< T > Luna::Spectral< T >::operator() (const Vector< T > & x) inline
Evaluation operator at a Vector of points.
Parameters
x A Vector of points where the spectral function is evaluated
Returns
A Vector of values of the spectral function
Definition at line 219 of file Spectral.h.
References Heat_plot::N, and Luna::Vector< T >::size().
     {
         Vector<T> temp( x.size() );
         std::size_t N( COEFFICIENTS.size() );
         if ( BASIS == "Chebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, n ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "EvenChebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, 2 * n ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "OddChebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, 2 * n + 1 ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "RationalSemi" )
         {
             RationalSemi<T> basis( PARAM );
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, n ) * COEFFICIENTS[ n ];
             }
         }
         return temp;
     }
operator()() [3/4]
template<typename T > T Luna::Spectral< T >::operator() (const T & x, const int & d) inline
Evaluation operator for the dth derivative of the spectral function at point x.
Parameters
x The point where the spectral function is evaluated
d The derivative to return
Returns
The dth derivative of the spectral function at the point x
Definition at line 264 of file Spectral.h.
References Heat_plot::N.
     {
         T temp( 0.0 );
         std::size_t N( COEFFICIENTS.size() );
         if ( BASIS == "Chebyshev" )
         {
             Chebyshev<T> basis;
             for ( int n = 0; n < N; ++n )
             {
                 temp += basis( x, n, d ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "EvenChebyshev" )
         {
             Chebyshev<T> basis;
             for ( int n = 0; n < N; ++n )
             {
                 temp += basis( x, 2 * n, d ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "OddChebyshev" )
         {
             Chebyshev<T> basis;
             for ( int n = 0; n < N; ++n )
             {
                 temp += basis( x, 2 * n + 1, d ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "RationalSemi" )
         {
             RationalSemi<T> basis( PARAM );
             for ( int n = 0; n < N; ++n )
             {
                 temp += basis( x, n, d ) * COEFFICIENTS[ n ];
             }
         }
         return temp;
     }
operator()() [4/4]
template<typename T > Vector< T > Luna::Spectral< T >::operator() (const Vector< T > & x, const int & d) inline
Evaluation operator for the dth derivative of the spectral function at a Vector of points.
Parameters
x A Vector of points where the spectral function is evaluated
d The derivative to return
Returns
A Vector of the dth derivative of the spectral function at the Vector of points
Definition at line 309 of file Spectral.h.
References Heat_plot::N, and Luna::Vector< T >::size().
     {
         Vector<T> temp( x.size() );
         std::size_t N( COEFFICIENTS.size() );
         if ( BASIS == "Chebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, n, d ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "EvenChebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, 2 * n, d ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "OddChebyshev" )
         {
             Chebyshev<T> basis;
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, 2 * n + 1, d ) * COEFFICIENTS[ n ];
             }
         }
         if ( BASIS == "RationalSemi" )
         {
             RationalSemi<T> basis( PARAM );
             for ( std::size_t n = 0; n < N; ++n )
             {
                 temp += basis( x, n, d ) * COEFFICIENTS[ n ];
             }
         }
         return temp;
     }
operator[]() [1/2]
template<typename T > const T & Luna::Spectral< T >::operator[] (const std::size_t & i) const inline
Indexing operator (read only)
Parameters
i Index
Returns
A constant reference to the coefficient located at the given index
Definition at line 354 of file Spectral.h.
Referenced by Luna::Spectral< T >::~Spectral().
   {
     if ( i < 0 || COEFFICIENTS.size() <= i )
     {
       throw Error( "Spectral operator [] range error" );
     }
     return COEFFICIENTS[ i ];
   }
operator[]() [2/2]
template<typename T > T & Luna::Spectral< T >::operator[] (const std::size_t & i) inline
Indexing operator (read / write)
Parameters
i Index
Returns
A reference to the coefficient located at the given index
Definition at line 364 of file Spectral.h.
   {
     if ( i < 0 || COEFFICIENTS.size() <= i )
     {
       throw Error( "Spectral operator [] range error" );
     }
     return COEFFICIENTS[ i ];
   }
parameter()
template<typename T > double & Luna::Spectral< T >::parameter ()
Return a pointer to the extra parameter.
Returns
A handle to the parameter
Definition at line 431 of file Spectral.h.
Referenced by Luna::Spectral< T >::~Spectral().
     {
         return PARAM;
     }
push_back()
template<typename T > void Luna::Spectral< T >::push_back (const T & new_elem)
Add a new coefficient to the back of the Vector of coefficients.
Parameters
new_elem New element to be appended to the end of the Vector of coefficients
Definition at line 419 of file Spectral.h.
Referenced by Luna::Spectral< T >::~Spectral().
     {
         COEFFICIENTS.push_back( new_elem );
     }
push_front()
template<typename T > void Luna::Spectral< T >::push_front (const T & new_elem)
Add a new coefficient to the front of the Vector of coefficients.
Parameters
new_elem New element to be added to the front of the Vector of coefficients
Definition at line 425 of file Spectral.h.
Referenced by Luna::Spectral< T >::~Spectral().
     {
         COEFFICIENTS.push_front( new_elem );
     }
set_basis()
template<typename T > void Luna::Spectral< T >::set_basis (const std::string & basis)
Set the basis specifier string.
Parameters
basis The basis specifier string (i.e. Chebyshev)
Definition at line 382 of file Spectral.h.
Referenced by Luna::Spectral< T >::~Spectral().
     {
         if ( basis != "Chebyshev" && basis != "EvenChebyshev"
           && basis != "OddChebyshev" && basis != "RationalSemi" )
             //&& basis != "Fourier" )
         {
             std::string problem;
             problem += "Spectral set_basis error: The basis function " + basis + "\n";
             problem += "is not supported.";
             throw Error( problem );
         }
         BASIS = basis;
     }
set_coefficients()
template<typename T > void Luna::Spectral< T >::set_coefficients (const Vector< T > & coeffs)
Set the spectral coefficients.
Parameters
coeffs The Vector of coefficients
Definition at line 403 of file Spectral.h.
Referenced by Luna::Spectral< T >::~Spectral().
     {
         COEFFICIENTS = coeffs;
     }
update_coefficients()
template<typename T > void Luna::Spectral< T >::update_coefficients (const Vector< T > & update)
Update the spectral coefficients (add a Vector to the Vector of coefficients)
Parameters
update The Vector to be added to the Vector of coefficients
Definition at line 409 of file Spectral.h.
References Luna::Vector< T >::size().
Referenced by main(), and Luna::Spectral< T >::~Spectral().
     {
         if ( update.size() != COEFFICIENTS.size() )
         {
             throw Error( "Spectral: update_coefficients vector size incorrect." );
         }
         COEFFICIENTS += update;
     }
The documentation for this class was generated from the following file:
include/Luna/Spectral.h