Luna: Luna::Vector< T > Class Template Reference
Luna::Vector< T > Class Template Reference
A Vector class for use with double and std::complex<double>
#include <Vector.h>
Public Types
typedef std::vector< T >::iterator iter
typedef std::vector< T >::const_iterator citer
typedef std::vector< T >::reverse_iterator riter
typedef std::vector< T >::const_reverse_iterator criter
Public Member Functions
Vector ()
Constructor for an empty Vector of unspecified size.
Vector (const std::size_t &size)
Constructor for a Vector of specified size.
Vector (const std::size_t &size, const T &elem)
Constructor of specified size and elements.
Vector (const std::initializer_list< T > &list)
Constructor from a list of elements.
Vector (const Vector< T > &source)
Copy constructor.
~Vector ()
Destructor.
const T & operator[] (const std::size_t &i) const
Indexing operator (read only)
T & operator[] (const std::size_t &i)
Indexing operator (read / write)
Vector< T > & operator= (const Vector< T > &original)
Copy assignment.
Vector< T > operator+ () const
Unary +.
Vector< T > operator- () const
Unary -.
Vector< T > operator+ (const Vector< T > &v_plus) const
Binary +.
Vector< T > operator- (const Vector< T > &v_minus) const
Binary -.
Vector< T > operator* (const T &scalar) const
Scalar multiplication.
Vector< T > operator/ (const T &divisor) const
Scalar division.
Vector< T > & operator+= (const Vector< T > &v_plus)
Addition assignment.
Vector< T > & operator-= (const Vector< T > &v_minus)
Subtraction assignment.
Vector< T > & operator*= (const T &scalar)
Scalar multiplication assignment.
Vector< T > & operator/= (const T &divisor)
Scalar division assigment.
Vector< T > & operator+= (const T &add)
Constant addition assignment.
Vector< T > & operator-= (const T &minus)
Constant subtraction assignment.
void operator() (const T &new_elem)
Push a new element into the end of the Vector (overload () to push_back)
std::size_t size () const
Size of the Vector.
void push_back (const T &new_elem)
Push a new element into the end of the Vector.
void push_front (const T &new_elem)
Push a new element into the front of the Vector.
void insert (const std::size_t &pos, const T &new_elem, const std::size_t &num=1)
Insert new elements into the Vector at a specified position.
void pop_back ()
Remove the last element in the Vector.
void pop_front ()
Remove the first element in the Vector.
std::size_t find (const T &val)
Find the first element in the Vector that is equal to a given value.
bool empty () const
Returns whether the Vector is empty.
void resize (const std::size_t &size)
Resize the Vector.
void reserve (const std::size_t &size)
Request a change in capacity.
void clear ()
Clear all the elements from the Vector.
Vector< double > abs () const
Absolute values.
void swap (const std::size_t &i, const std::size_t &j)
Swap elements i and j.
void reverse ()
Reverse the order of the elements.
void assign (const std::size_t n, const T elem)
Assign new contents to the Vector.
Vector< double > real () const
Real part of the elements of the Vector.
Vector< double > imag () const
Imaginary part of the elements of the Vector.
Vector< T > conjugate () const
Conjugate of the elements of the Vector.
void linspace (const double &a, const double &b, const std::size_t &n)
Create a linearly spaced Vector (of doubles) with n elements.
void powspace (const double &a, const double &b, const std::size_t &n, const double &p)
Create a nonuniform Vector using a power law with exponent p (1->linear)
void chebyshev_grid (const std::size_t &n)
Create a Vector of size n containing the Gauss-Chebyshev or Roots collocation points between -1 and +1.
void half_chebyshev_grid (const std::size_t &n)
Create a Vector of size n containing the Gauss-Chebyshev or Roots collocation points between 0 and 1.
void lobatto_grid (const std::size_t &n)
Create a Vector of size n containing the Gauss-Lobatto or Extrema-plus-Endpoints collocation points between -1 and +1.
void half_lobatto_grid (const std::size_t &n)
Create a Vector of size n containing the Gauss-Lobatto or Extrema-plus-Endpoints collocation points between 0 and 1.
void rational_semi_grid (const std::size_t &n, const double &L)
Create a Vector of size n containing the semi-infinite rational Chebyshev collocation points between 0 and infinity.
T product (const std::size_t &start, const std::size_t &end)
Product of the elements in the Vector (from index start to end)
T product ()
T sum (const std::size_t &start, const std::size_t &end)
Sum of the elements in the Vector (from index start to end)
T sum ()
Sum of the elements in the Vector.
T dot (const Vector< T > &w)
Dot product of two Vectors v.dot(w)
void output (std::string filename, int precision=12)
Output the Vector to a file.
void read (std::string filename, int precision=12)
Read the Vector from a file.
T max ()
Maximum element.
T min ()
Minimum element.
std::size_t max_index ()
Maximum element index.
std::size_t min_index ()
Minimum element index.
Vector< T > square () const
Square all the elements in the Vector.
Vector< T > power (const double &p) const
Raise all the elements in the Vector to the power p.
void random ()
Fill the Vector with random elements (between -1 and 1)
T & back ()
A reference to the last element in the Vector.
const T & back () const
A (read only) reference to the last element in the Vector.
double norm_1 () const
L1 norm: sum of absolute values.
double norm_2 () const
L2 norm: square root of the sum of the squares.
double norm_p (const double &p) const
Lp norm: p-th root of the sum of the absolute values to the power p.
double norm_inf () const
Inf norm: largest absolute value element (p -> infinity)
iter begin ()
Pass through the std::vector begin iterator.
riter rbegin ()
Pass through the std::vector begin reverse iterator.
citer begin () const
Pass through the std::vector begin constant iterator.
criter rbegin () const
Pass through the std::vector begin constant reverse iterator.
iter end ()
Pass through the std::vector end iterator.
riter rend ()
Pass through the std::vector end reverse iterator.
citer end () const
Pass through the std::vector end constant iterator.
criter rend () const
Pass through the std::vector end constant reverse iterator.
template<>
void linspace (const double &a, const double &b, const std::size_t &n)
template<>
void powspace (const double &a, const double &b, const std::size_t &n, const double &p)
template<>
void chebyshev_grid (const std::size_t &n)
template<>
void half_chebyshev_grid (const std::size_t &n)
template<>
void lobatto_grid (const std::size_t &n)
template<>
void half_lobatto_grid (const std::size_t &n)
template<>
void rational_semi_grid (const std::size_t &n, const double &L)
template<>
void random ()
template<>
void random ()
Friends
class Matrix< T >
class Polynomial< T >
class SparseMatrix< T >
template<class Type >
std::ostream & operator<< (std::ostream &os, const Vector< Type > &vec)
Output operator <<.
Vector< T > operator* (const T &scalar, Vector< T > &vec)
Detailed Description
template<class T>
class Luna::Vector< T >
A Vector class for use with double and std::complex<double>
Definition at line 41 of file Vector.h.
Member Typedef Documentation
citer
template<class T> typedef std::vector<T>::const_iterator Luna::Vector< T >::citer
Definition at line 374 of file Vector.h.
criter
template<class T> typedef std::vector<T>::const_reverse_iterator Luna::Vector< T >::criter
Definition at line 376 of file Vector.h.
iter
template<class T> typedef std::vector<T>::iterator Luna::Vector< T >::iter
Definition at line 373 of file Vector.h.
riter
template<class T> typedef std::vector<T>::reverse_iterator Luna::Vector< T >::riter
Definition at line 375 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/5]
template<class T> Luna::Vector< T >::Vector () inline
Constructor for an empty Vector of unspecified size.
Definition at line 54 of file Vector.h.
Referenced by Luna::Vector< X >::Vector().
 {}
Vector() [2/5]
template<typename T > Luna::Vector< T >::Vector (const std::size_t & size) inline
Constructor for a Vector of specified size.
Parameters
size Size of the Vector
Definition at line 437 of file Vector.h.
   {
     VECTOR.resize( size );
   }
Vector() [3/5]
template<typename T> Luna::Vector< T >::Vector (const std::size_t & size, const T & elem) inline
Constructor of specified size and elements.
Parameters
size Size of the Vector
elem Element to fill each entry of the Vector with
Definition at line 443 of file Vector.h.
                                             : VECTOR( size, elem )
   {}
Vector() [4/5]
template<typename T> Luna::Vector< T >::Vector (const std::initializer_list< T > & list) inline
Constructor from a list of elements.
Parameters
list A list of elements to store in the Vector
Definition at line 448 of file Vector.h.
   {
     for ( auto i = list.begin(); i != list.end(); ++i )
     {
       VECTOR.push_back( *i );
     }
   }
Vector() [5/5]
template<typename T> Luna::Vector< T >::Vector (const Vector< T > & source) inline
Copy constructor.
Parameters
source Vector to be copied when initialising
Definition at line 457 of file Vector.h.
   {
     VECTOR = source.VECTOR;
   }
~Vector()
template<class T> Luna::Vector< T >::~Vector () inline
Destructor.
Definition at line 74 of file Vector.h.
 {}
Member Function Documentation
abs()
template<typename T > Vector< double > Luna::Vector< T >::abs () const inline
Absolute values.
Returns
Vector absolute of values of the elements
Definition at line 720 of file Vector.h.
   {
     Vector<double> abs_vals;
     for (size_t i=0; i < this->size(); ++i)
     {
       abs_vals.push_back( std::abs( VECTOR[ i ] ) ) ;
     }
     return abs_vals;
   }
assign()
template<typename T> void Luna::Vector< T >::assign (const std::size_t n, const T elem) inline
Assign new contents to the Vector.
Parameters
n The number of elements to assign
elem The element to be assigned
Definition at line 746 of file Vector.h.
Referenced by Luna::Vector< X >::assign(), and Luna::LinearEigensystem< T >::eigenvectors().
   {
     VECTOR.assign( n, elem );
   }
back() [1/2]
template<typename T > T & Luna::Vector< T >::back () inline
A reference to the last element in the Vector.
Returns
A reference to the last element
Definition at line 1037 of file Vector.h.
Referenced by Luna::Vector< X >::back(), and Luna::Mesh1D< T, X >::remesh().
   {
     return VECTOR.back();
   }
back() [2/2]
template<typename T > const T & Luna::Vector< T >::back () const inline
A (read only) reference to the last element in the Vector.
Returns
The last element in the Vector
Definition at line 1043 of file Vector.h.
   {
     return VECTOR.back();
   }
begin() [1/2]
template<class T> iter Luna::Vector< T >::begin () inline
Pass through the std::vector begin iterator.
Returns
An iterator pointing to the first element
Definition at line 380 of file Vector.h.
     {
       return VECTOR.begin();
     }
begin() [2/2]
template<class T> citer Luna::Vector< T >::begin () const inline
Pass through the std::vector begin constant iterator.
Returns
A constant iterator pointing to the first element
Definition at line 394 of file Vector.h.
     {
       return VECTOR.begin();
     }
chebyshev_grid() [1/2]
template<class T> void Luna::Vector< T >::chebyshev_grid (const std::size_t & n)
Create a Vector of size n containing the Gauss-Chebyshev or Roots collocation points between -1 and +1.
Parameters
n Number of elements
Referenced by Luna::Chebyshev< T >::approximate(), Luna::Chebyshev< T >::approximate_even(), Luna::Chebyshev< T >::approximate_odd(), and main().
chebyshev_grid() [2/2]
template<> void Luna::Vector< double >::chebyshev_grid (const std::size_t & n) inline
Definition at line 808 of file Vector.h.
   {
     VECTOR.resize( n );
     for ( std::size_t i=1; i <= n; ++i )
         {
             VECTOR[ i - 1 ] = std::cos( M_PI * ( 2 * i - 1 ) / ( 2.0 * n ) );
         }
   }
clear()
template<typename T > void Luna::Vector< T >::clear () inline
Clear all the elements from the Vector.
Definition at line 714 of file Vector.h.
Referenced by Luna::Vector< X >::clear().
   {
     VECTOR.clear();
   }
conjugate()
template<typename T > Vector< T > Luna::Vector< T >::conjugate () const inline
Conjugate of the elements of the Vector.
Returns
Vector of conjugates of the elements
Definition at line 774 of file Vector.h.
   {
      Vector<T> conjugate( *this );
      for (size_t i=0; i < size(); ++i)
      {
        conjugate.VECTOR[ i ] = std::conj( VECTOR[ i ] ) ;
      }
      return conjugate;
   }
dot()
template<typename T> T Luna::Vector< T >::dot (const Vector< T > & w) inline
Dot product of two Vectors v.dot(w)
Parameters
w The Vector to be dotted with
Returns
The dot product of two vectors
Definition at line 906 of file Vector.h.
Referenced by Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), Luna::SparseMatrix< T >::solve_BiCGSTAB(), Luna::SparseMatrix< T >::solve_CG(), and Luna::SparseMatrix< T >::solve_QMR().
   {
     if ( size() != w.size() )   {
       throw Error( "Vector dot product: size error" );
     }
     T init( 0.0 );
     // \todo this can be parallelised using transform_reduce ???
     return std::inner_product ( VECTOR.cbegin(), VECTOR.cend(),
                      w.VECTOR.begin(), init );
   }
empty()
template<typename T > bool Luna::Vector< T >::empty () const inline
Returns whether the Vector is empty.
Returns
true if the Vector is size 0 and false otherwise
Definition at line 696 of file Vector.h.
Referenced by Luna::Vector< X >::empty().
   {
     return VECTOR.empty();
   }
end() [1/2]
template<class T> iter Luna::Vector< T >::end () inline
Pass through the std::vector end iterator.
Returns
An iterator referring to the past-the-end element
Definition at line 408 of file Vector.h.
     {
       return VECTOR.end();
     }
end() [2/2]
template<class T> citer Luna::Vector< T >::end () const inline
Pass through the std::vector end constant iterator.
Returns
A constant iterator referring to the past-the-end element
Definition at line 422 of file Vector.h.
     {
       return VECTOR.end();
     }
find()
template<typename T> std::size_t Luna::Vector< T >::find (const T & val) inline
Find the first element in the Vector that is equal to a given value.
Parameters
val The value to find
Returns
The index of the value in the Vector (if not found returns last)
Definition at line 682 of file Vector.h.
Referenced by Luna::SparseMatrix< T >::insert().
   {
     std::size_t index( 0 );
     std::vector<std::size_t>::iterator it;
     it = std::find( VECTOR.begin(), VECTOR.end(), val );
     for ( std::vector<std::size_t>::iterator i = VECTOR.begin();
           i != it; i++ )
     {
       index++;
     }
     return index;
   }
half_chebyshev_grid() [1/2]
template<class T> void Luna::Vector< T >::half_chebyshev_grid (const std::size_t & n)
Create a Vector of size n containing the Gauss-Chebyshev or Roots collocation points between 0 and 1.
Parameters
n Number of elements
half_chebyshev_grid() [2/2]
template<> void Luna::Vector< double >::half_chebyshev_grid (const std::size_t & n) inline
Definition at line 818 of file Vector.h.
   {
     VECTOR.resize( n );
     for ( std::size_t i=1; i <= n; ++i )
         {
             VECTOR[ i - 1 ] = std::cos( 0.5 * M_PI * ( 2 * i - 1 ) / ( 2.0 * n ) );
         }
   }
half_lobatto_grid() [1/2]
template<class T> void Luna::Vector< T >::half_lobatto_grid (const std::size_t & n)
Create a Vector of size n containing the Gauss-Lobatto or Extrema-plus-Endpoints collocation points between 0 and 1.
Parameters
n Number of elements
Referenced by main().
half_lobatto_grid() [2/2]
template<> void Luna::Vector< double >::half_lobatto_grid (const std::size_t & n) inline
Definition at line 838 of file Vector.h.
   {
     VECTOR.resize( n );
     for ( std::size_t i=0; i < n; ++i )
         {
             VECTOR[ i ] = std::cos( 0.5 * M_PI * i / ( n - 1.0 ) );
         }
   }
imag()
template<typename T > Vector< double > Luna::Vector< T >::imag () const inline
Imaginary part of the elements of the Vector.
Returns
Vector of imaginary parts of the elements
Definition at line 763 of file Vector.h.
   {
     Vector<double> imag_part( size() );
     for ( std::size_t i = 0; i < size(); ++i )
     {
       imag_part[ i ] = std::imag( VECTOR[ i ] ) ;
     }
     return imag_part;
   }
insert()
template<typename T> void Luna::Vector< T >::insert (const std::size_t & pos, const T & new_elem, const std::size_t & num = 1) inline
Insert new elements into the Vector at a specified position.
Parameters
pos The position to insert the elements
new_elem The new element to be inserted
num The number of new elements to be inserted (1 by default)
Definition at line 655 of file Vector.h.
Referenced by Luna::SparseMatrix< T >::insert(), Luna::Vector< X >::insert(), main(), and Luna::Vector< X >::push_front().
   {
     VECTOR.insert( VECTOR.begin() + pos, num, new_elem );
   }
linspace() [1/2]
template<class T> void Luna::Vector< T >::linspace (const double & a, const double & b, const std::size_t & n)
Create a linearly spaced Vector (of doubles) with n elements.
Parameters
a Start value
b End value
n Number of elements
Referenced by main().
linspace() [2/2]
template<> void Luna::Vector< double >::linspace (const double & a, const double & b, const std::size_t & n) inline
Definition at line 785 of file Vector.h.
     {
         VECTOR.resize( n );
         const double h = ( b - a ) / (n - 1)  ;
         for ( std::size_t i=0; i < n; ++i )
         {
             VECTOR[ i ] = a + h * i;
         }
     }
lobatto_grid() [1/2]
template<class T> void Luna::Vector< T >::lobatto_grid (const std::size_t & n)
Create a Vector of size n containing the Gauss-Lobatto or Extrema-plus-Endpoints collocation points between -1 and +1.
Parameters
n Number of elements
Referenced by main().
lobatto_grid() [2/2]
template<> void Luna::Vector< double >::lobatto_grid (const std::size_t & n) inline
Definition at line 828 of file Vector.h.
   {
     VECTOR.resize( n );
     for ( std::size_t i=0; i < n; ++i )
         {
             VECTOR[ i ] = std::cos( M_PI * i / ( n - 1.0 ) );
         }
   }
max()
template<typename T > T Luna::Vector< T >::max () inline
Maximum element.
Returns
The maximum element in the Vector
Definition at line 952 of file Vector.h.
Referenced by Luna::Vector< X >::norm_inf().
   {
     return VECTOR[ this-> max_index() ];
   }
max_index()
template<typename T > std::size_t Luna::Vector< T >::max_index () inline
Maximum element index.
Returns
The index of the largest element (first index if more than one)
Definition at line 964 of file Vector.h.
   {
     return std::distance( VECTOR.begin(),
                            std::max_element( VECTOR.begin(), VECTOR.end() ) );
   }
min()
template<typename T > T Luna::Vector< T >::min () inline
Minimum element.
Returns
The minimum element in the Vector
Definition at line 958 of file Vector.h.
   {
     return VECTOR[ this-> min_index() ];
   }
min_index()
template<typename T > std::size_t Luna::Vector< T >::min_index () inline
Minimum element index.
Returns
The index of the smallest element (first index if more than one)
Definition at line 971 of file Vector.h.
   {
     return std::distance( VECTOR.begin(),
                            std::min_element( VECTOR.begin(), VECTOR.end() ) );
   }
norm_1()
template<typename T > double Luna::Vector< T >::norm_1 () const inline
L1 norm: sum of absolute values.
Returns
The L1 norm of the Vector
Definition at line 1051 of file Vector.h.
   {
     return ( this->abs() ).sum();
   }
norm_2()
template<typename T > double Luna::Vector< T >::norm_2 () const inline
L2 norm: square root of the sum of the squares.
Returns
The L2 norm of the Vector
Definition at line 1057 of file Vector.h.
Referenced by main(), Luna::SparseMatrix< T >::solve_BiCG(), Luna::SparseMatrix< T >::solve_BiCGSTAB(), Luna::SparseMatrix< T >::solve_CG(), and Luna::SparseMatrix< T >::solve_QMR().
   {
     return std::sqrt( ( this->abs() ).square().sum() );
   }
norm_inf()
template<typename T > double Luna::Vector< T >::norm_inf () const inline
Inf norm: largest absolute value element (p -> infinity)
Returns
The infinity norm of the Vector
Definition at line 1069 of file Vector.h.
Referenced by Luna::ODE_BVP< T, X >::adapt(), Luna::Newton< T >::arclength_solve(), Luna::ODE_BVP< T, X >::arclength_solve(), Luna::Newton< T >::iterate(), and Luna::ODE_BVP< T, X >::solve_bvp().
   {
     return ( this->abs() ).max();
   }
norm_p()
template<typename T > double Luna::Vector< T >::norm_p (const double & p) const inline
Lp norm: p-th root of the sum of the absolute values to the power p.
Parameters
p The exponent for the p-norm
Returns
The Lp norm of the Vector
Definition at line 1063 of file Vector.h.
   {
     return std::pow( ( this->abs() ).power( p ).sum(), 1.0 / p );
   }
operator()()
template<typename T> void Luna::Vector< T >::operator() (const T & new_elem) inline
Push a new element into the end of the Vector (overload () to push_back)
Parameters
new_elem New element to be appended to the end of the Vector
Definition at line 629 of file Vector.h.
   {
     VECTOR.push_back( new_elem );
   }
operator*()
template<typename T> Vector< T > Luna::Vector< T >::operator* (const T & scalar) const inline
Scalar multiplication.
Parameters
scalar The scalar to multiply the Vector by
Returns
The Vector multiplied by the scalar
Definition at line 547 of file Vector.h.
Referenced by Luna::Vector< X >::~Vector().
   {
     Vector<T> temp( *this );
     std::transform ( temp.VECTOR.cbegin(), temp.VECTOR.cend(),
                      temp.VECTOR.begin(),
                      std::bind( std::multiplies<T>(),
                                 std::placeholders::_1, scalar ) );
     return temp;
   }
operator*=()
template<typename T> Vector< T > & Luna::Vector< T >::operator*= (const T & scalar) inline
Scalar multiplication assignment.
Parameters
scalar The scalar to multiply the Vector by
Returns
A reference to the Vector after multiplication by a scalar
Definition at line 595 of file Vector.h.
   {
     std::transform ( VECTOR.cbegin(), VECTOR.cend(), VECTOR.begin(),
                      std::bind( std::multiplies<T>(),
                                 std::placeholders::_1, scalar ) );
     return *this;
   }
operator+() [1/2]
template<typename T > Vector< T > Luna::Vector< T >::operator+ () const inline
Unary +.
Returns
The Vector
Definition at line 504 of file Vector.h.
Referenced by Luna::Vector< X >::~Vector().
   {
     return *this;
   }
operator+() [2/2]
template<typename T> Vector< T > Luna::Vector< T >::operator+ (const Vector< T > & v_plus) const inline
Binary +.
Parameters
v_plus The Vector to be added
Returns
The sum of this Vector and v_plus
Definition at line 519 of file Vector.h.
   {
     Vector<T> temp( *this );
     if ( v_plus.VECTOR.size() != temp.VECTOR.size() )
     {
       throw Error( "Vector dimension error in + operator." );
     }
     std::transform ( temp.VECTOR.cbegin(), temp.VECTOR.cend(),
                      v_plus.VECTOR.begin(), temp.VECTOR.begin(),
                      std::plus<T>() );
     return temp;
   }
operator+=() [1/2]
template<typename T> Vector< T > & Luna::Vector< T >::operator+= (const Vector< T > & v_plus) inline
Addition assignment.
Parameters
v_plus The Vector to be added
Returns
A reference to the Vector after addition by v_plus
Definition at line 569 of file Vector.h.
   {
     if ( v_plus.VECTOR.size() != VECTOR.size() )
     {
       throw Error( "Vector dimension error in += operator." );
     }
     std::transform ( VECTOR.cbegin(), VECTOR.cend(),
                      v_plus.VECTOR.begin(), VECTOR.begin(),
                      std::plus<T>() );
     return *this;
   }
operator+=() [2/2]
template<typename T> Vector< T > & Luna::Vector< T >::operator+= (const T & add) inline
Constant addition assignment.
Parameters
add The constant to be added to each element
Returns
A reference to the Vector after addition by a constant
Definition at line 613 of file Vector.h.
   {
     std::transform ( VECTOR.cbegin(), VECTOR.cend(), VECTOR.begin(),
                      std::bind( std::plus<T>(), std::placeholders::_1, add ) );
     return *this;
   }
operator-() [1/2]
template<typename T > Vector< T > Luna::Vector< T >::operator- () const inline
Unary -.
Returns
The negation of the Vector
Definition at line 510 of file Vector.h.
Referenced by Luna::Vector< X >::~Vector().
   {
     Vector<T> temp( *this );
     std::transform ( temp.VECTOR.cbegin(), temp.VECTOR.cend(),
                      temp.VECTOR.begin(), std::negate<T>() );
     return temp;
   }
operator-() [2/2]
template<typename T> Vector< T > Luna::Vector< T >::operator- (const Vector< T > & v_minus) const inline
Binary -.
Parameters
v_minus The Vector to be subtracted
Returns
The subtraction of v_minus from this Vector
Definition at line 533 of file Vector.h.
   {
     Vector<T> temp( *this );
     if ( v_minus.VECTOR.size() != temp.VECTOR.size() )
     {
       throw Error( "Vector dimension error in - operator." );
     }
     std::transform ( temp.VECTOR.cbegin(), temp.VECTOR.cend(),
                      v_minus.VECTOR.begin(), temp.VECTOR.begin(),
                      std::minus<T>() );
     return temp;
   }
operator-=() [1/2]
template<typename T> Vector< T > & Luna::Vector< T >::operator-= (const Vector< T > & v_minus) inline
Subtraction assignment.
Parameters
v_minus The Vector to be subtracted
Returns
A reference to the Vector after subtraction by v_minus
Definition at line 582 of file Vector.h.
   {
     if ( v_minus.VECTOR.size() != VECTOR.size() )
     {
       throw Error( "Vector dimension error in -= operator." );
     }
     std::transform ( VECTOR.cbegin(), VECTOR.cend(),
                      v_minus.VECTOR.begin(), VECTOR.begin(),
                      std::minus<T>() );
     return *this;
   }
operator-=() [2/2]
template<typename T> Vector< T > & Luna::Vector< T >::operator-= (const T & minus) inline
Constant subtraction assignment.
Parameters
minus The constant to be subtracted from each element
Returns
A reference to the Vector after subtraction by a constant
Definition at line 621 of file Vector.h.
   {
     std::transform ( VECTOR.cbegin(), VECTOR.cend(), VECTOR.begin(),
                      std::bind( std::minus<T>(), std::placeholders::_1, minus ));
     return *this;
   }
operator/()
template<typename T> Vector< T > Luna::Vector< T >::operator/ (const T & divisor) const inline
Scalar division.
Parameters
scalar The divisor to divide the Vector by
Returns
The Vector divided by the divisor
Definition at line 558 of file Vector.h.
   {
     Vector<T> temp( *this );
     std::transform ( temp.VECTOR.cbegin(), temp.VECTOR.cend(),
                      temp.VECTOR.begin(),
                      std::bind( std::divides<T>(),
                                 std::placeholders::_1, divisor ) );
     return temp;
   }
operator/=()
template<typename T> Vector< T > & Luna::Vector< T >::operator/= (const T & divisor) inline
Scalar division assigment.
Parameters
scalar The divisor to divide the Vector by
Returns
A reference to the Vector after division by a divisor
Definition at line 604 of file Vector.h.
   {
     std::transform ( VECTOR.cbegin(), VECTOR.cend(), VECTOR.begin(),
                      std::bind( std::divides<T>(),
                                 std::placeholders::_1, divisor ) );
     return *this;
   }
operator=()
template<typename T> Vector< T > & Luna::Vector< T >::operator= (const Vector< T > & original) inline
Copy assignment.
Parameters
original Vector to be copied
Returns
The new Vector
Definition at line 496 of file Vector.h.
Referenced by Luna::Vector< X >::~Vector().
   {
     if ( this == &original ){ return *this; }
     VECTOR = original.VECTOR;
     return *this;
   }
operator[]() [1/2]
template<typename T > const T & Luna::Vector< T >::operator[] (const std::size_t & i) const inline
Indexing operator (read only)
Parameters
i Index
Returns
A constant reference to the element located at the given index
Definition at line 476 of file Vector.h.
Referenced by Luna::Vector< X >::~Vector().
   {
     if ( i < 0 || VECTOR.size() <= i )
     {
       throw Error( "Vector operator [] range error" );
     }
     return VECTOR[ i ];
   }
operator[]() [2/2]
template<typename T > T & Luna::Vector< T >::operator[] (const std::size_t & i) inline
Indexing operator (read / write)
Parameters
i Index
Returns
A reference to the element located at the given index
Definition at line 486 of file Vector.h.
   {
     if ( i < 0 || VECTOR.size() <= i )
     {
       throw Error( "Vector operator [] range error" );
     }
     return VECTOR[ i ];
   }
output()
template<typename T > void Luna::Vector< T >::output (std::string filename, int precision = 12) inline
Output the Vector to a file.
Parameters
filename The name of the file to output the Vector to
precision The precision of the elements to be stored
Definition at line 918 of file Vector.h.
   {
     std::ofstream out;
     out.open( filename.c_str() );
     out.precision( precision );
     out.setf( std::ios::showpoint );
     out.setf( std::ios::showpos );
     out.setf( std::ios::scientific );
     for ( std::size_t i = 0; i < size(); ++i )
     {
       out << VECTOR[ i ] << std::endl;
     }
   }
pop_back()
template<typename T > void Luna::Vector< T >::pop_back () inline
Remove the last element in the Vector.
Definition at line 662 of file Vector.h.
   {
     if( VECTOR.empty() )
     {
       throw Error( "Vector pop_back: vector is empty.");
     }
     VECTOR.pop_back();
   }
pop_front()
template<typename T > void Luna::Vector< T >::pop_front () inline
Remove the first element in the Vector.
Definition at line 672 of file Vector.h.
   {
     if( VECTOR.empty() )
     {
       throw Error( "Vector pop_front: vector is empty.");
     }
     VECTOR.erase( VECTOR.begin() );
   }
power()
template<typename T > Vector< T > Luna::Vector< T >::power (const double & p) const inline
Raise all the elements in the Vector to the power p.
Parameters
p The exponent to raise each of the elements to
Returns
Vector of the elements raised to the power p
Definition at line 989 of file Vector.h.
   {
     Vector<T> power;
     for (size_t i=0; i < size(); ++i)
     {
       power.VECTOR.push_back( std::pow( VECTOR[ i ], p ) );
     }
     return power;
   }
powspace() [1/2]
template<class T> void Luna::Vector< T >::powspace (const double & a, const double & b, const std::size_t & n, const double & p)
Create a nonuniform Vector using a power law with exponent p (1->linear)
Parameters
a Start value
b End value
n Number of elements
p Exponent
Referenced by main().
powspace() [2/2]
template<> void Luna::Vector< double >::powspace (const double & a, const double & b, const std::size_t & n, const double & p) inline
Definition at line 797 of file Vector.h.
   {
     VECTOR.resize( n );
     for ( std::size_t i = 0; i < n; ++i )
     {
       VECTOR[ i ] = a + ( b - a ) * std::pow( ( double )i / ( n - 1 ), p );
     }
   }
product() [1/2]
template<typename T > T Luna::Vector< T >::product (const std::size_t & start, const std::size_t & end) inline
Product of the elements in the Vector (from index start to end)
Parameters
start Start index
end End index
Returns
Product of the elements in the Vector
Definition at line 861 of file Vector.h.
   {
     if ( start > end )  { throw Error( "Vector product: start > end" );}
     if ( start<0 || size()<=start ) {
       throw Error( "Vector product method range error" );}
     if ( end<0 || size()<=end ) {
       throw Error( "Vector product method range error" );}
     T prod( VECTOR[ start ] );
     for ( std::size_t i=start+1; i<=end; ++i )
     {
       prod *= VECTOR[ i ];
     }
     return prod;
   }
product() [2/2]
template<typename T > T Luna::Vector< T >::product () inline
Returns
Product of the elements in the Vector
Definition at line 878 of file Vector.h.
   {
     return this->product( 0, size() - 1 );
   }
push_back()
template<typename T> void Luna::Vector< T >::push_back (const T & new_elem) inline
Push a new element into the end of the Vector.
Parameters
new_elem New element to be appended to the end of the Vector
Definition at line 643 of file Vector.h.
Referenced by Luna::Vector< X >::abs(), Luna::ODE_BVP< T, X >::adapt(), Luna::SparseMatrix< T >::col_index(), Luna::LinearEigensystem< T >::eigenvectors(), Luna::Mesh1D< T, X >::get_nodes_vars(), Luna::Mesh2D< T >::get_nodes_vars(), Luna::SparseMatrix< T >::insert(), main(), Luna::Matrix< double >::multiply(), Luna::Vector< X >::operator()(), Luna::Vector< X >::push_back(), Luna::Tridiagonal< T >::solve(), Luna::SparseMatrix< T >::SparseMatrix(), and Luna::Vector< X >::Vector().
   {
     VECTOR.push_back( new_elem );
   }
push_front()
template<typename T> void Luna::Vector< T >::push_front (const T & new_elem) inline
Push a new element into the front of the Vector.
Parameters
new_elem New element to be added to the front of the Vector
Definition at line 649 of file Vector.h.
Referenced by Luna::LinearEigensystem< T >::compute_real_symmetric_tridiagonal(), and Luna::Tridiagonal< T >::solve().
   {
     VECTOR.insert( VECTOR.begin(), new_elem );
   }
random() [1/3]
template<class T> void Luna::Vector< T >::random ()
Fill the Vector with random elements (between -1 and 1)
Referenced by main().
random() [2/3]
template<> void Luna::Vector< double >::random () inline
Definition at line 1000 of file Vector.h.
   {
     std::mt19937_64 rng;
     // initialize the random number generator with time-dependent seed
     auto start = std::chrono::high_resolution_clock::now();
     uint64_t timeSeed = start.time_since_epoch().count();
     std::seed_seq ss{uint32_t(timeSeed & 0xffffffff), uint32_t(timeSeed>>32)};
     rng.seed(ss);
     // initialize a uniform distribution between -1 and 1
     std::uniform_real_distribution<double> unif(-1, 1);
     for ( std::size_t i = 0; i < VECTOR.size(); ++i )
     {
       double num( unif(rng) );
       VECTOR[ i ] = num;
     }
   }
random() [3/3]
template<> void Luna::Vector< std::complex< double > >::random () inline
Definition at line 1018 of file Vector.h.
   {
     std::mt19937_64 rng;
     // initialize the random number generator with time-dependent seed
     auto start = std::chrono::high_resolution_clock::now();
     uint64_t timeSeed = start.time_since_epoch().count();
     std::seed_seq ss{uint32_t(timeSeed & 0xffffffff), uint32_t(timeSeed>>32)};
     rng.seed(ss);
     // initialize a uniform distribution between -1 and 1
     std::uniform_real_distribution<double> unif(-1, 1);
     for ( std::size_t i = 0; i < VECTOR.size(); ++i )
     {
       double real( unif(rng) );
       double imag( unif(rng) );
       VECTOR[ i ] = std::complex<double> ( real, imag );
     }
   }
rational_semi_grid() [1/2]
template<class T> void Luna::Vector< T >::rational_semi_grid (const std::size_t & n, const double & L)
Create a Vector of size n containing the semi-infinite rational Chebyshev collocation points between 0 and infinity.
Parameters
n Number of elements
L The mapping parameter
Referenced by Luna::RationalSemi< T >::approximate(), and main().
rational_semi_grid() [2/2]
template<> void Luna::Vector< double >::rational_semi_grid (const std::size_t & n, const double & L) inline
Definition at line 848 of file Vector.h.
   {
     VECTOR.resize( n );
     double t;
     for ( std::size_t i=0; i < n; ++i )
         {
       t = ( 2 * ( i + 1 ) - 1 ) * M_PI / ( 2 * n );
             VECTOR[ i ] = L * std::pow( 1 / std::tan( t / 2 ) , 2 );
         }
   }
rbegin() [1/2]
template<class T> riter Luna::Vector< T >::rbegin () inline
Pass through the std::vector begin reverse iterator.
Returns
A reverse iterator pointing to the last element
Definition at line 387 of file Vector.h.
     {
       return VECTOR.rbegin();
     }
rbegin() [2/2]
template<class T> criter Luna::Vector< T >::rbegin () const inline
Pass through the std::vector begin constant reverse iterator.
Returns
A constant reverse iterator pointing to the last element
Definition at line 401 of file Vector.h.
     {
       return VECTOR.rbegin();
     }
read()
template<typename T > void Luna::Vector< T >::read (std::string filename, int precision = 12) inline
Read the Vector from a file.
Parameters
filename The name of the file to read the Vector from
precision The precision of the elements to be read in
Definition at line 933 of file Vector.h.
   {
     std::ifstream inFile;
         inFile.open( filename.c_str() );
         inFile.precision( precision );
         inFile.setf( std::ios::showpoint );
         inFile.setf( std::ios::showpos );
         inFile.setf( std::ios::scientific );
         if (!inFile) { throw Error( "Vector.read() unable to open file" ); }
     VECTOR.resize( 0 );
     T val;
     while ( inFile >> val )
     {
       VECTOR.push_back( val );
     }
     inFile.close();
   }
real()
template<typename T > Vector< double > Luna::Vector< T >::real () const inline
Real part of the elements of the Vector.
Returns
Vector of real parts of the elements
Definition at line 752 of file Vector.h.
Referenced by Luna::Mesh1D< T, X >::get_interpolated_vars(), and main().
   {
     Vector<double> real_part( size() );
     for ( std::size_t i = 0; i < size(); ++i )
     {
       real_part[ i ] = std::real( VECTOR[ i ] ) ;
     }
     return real_part;
   }
rend() [1/2]
template<class T> riter Luna::Vector< T >::rend () inline
Pass through the std::vector end reverse iterator.
Returns
A reverse iterator pointing to the element before the first
Definition at line 415 of file Vector.h.
     {
       return VECTOR.rend();
     }
rend() [2/2]
template<class T> criter Luna::Vector< T >::rend () const inline
Pass through the std::vector end constant reverse iterator.
Returns
A constant reverse iterator pointing to the element before the first
Definition at line 429 of file Vector.h.
     {
       return VECTOR.rend();
     }
reserve()
template<typename T > void Luna::Vector< T >::reserve (const std::size_t & size) inline
Request a change in capacity.
Parameters
size Minimum capacity for the Vector
Definition at line 708 of file Vector.h.
Referenced by Luna::Matrix< double >::multiply(), and Luna::Vector< X >::reserve().
   {
     VECTOR.reserve( size );
   }
resize()
template<typename T > void Luna::Vector< T >::resize (const std::size_t & size) inline
Resize the Vector.
Parameters
size New size of the Vector
Definition at line 702 of file Vector.h.
Referenced by Luna::Vector< X >::chebyshev_grid(), Luna::LinearEigensystem< T >::compute_real_symmetric(), Luna::LinearEigensystem< T >::compute_real_symmetric_tridiagonal(), Luna::BandedMatrix< T >::det(), Luna::LinearEigensystem< T >::eigenvectors(), Luna::gamma(), Luna::Vector< X >::half_chebyshev_grid(), Luna::Vector< X >::half_lobatto_grid(), Luna::Vector< X >::linspace(), Luna::Vector< X >::lobatto_grid(), main(), Luna::Vector< X >::powspace(), Luna::Vector< X >::rational_semi_grid(), Luna::Vector< X >::resize(), and Luna::BandedMatrix< T >::solve().
   {
     VECTOR.resize( size );
   }
reverse()
template<typename T > void Luna::Vector< T >::reverse () inline
Reverse the order of the elements.
Definition at line 740 of file Vector.h.
   {
     std::reverse( VECTOR.begin(), VECTOR.end() );
   }
size()
template<typename T > std::size_t Luna::Vector< T >::size () const inline
Size of the Vector.
Returns
The number of elements in the Vector
Definition at line 637 of file Vector.h.
Referenced by Luna::Arclength< T >::arclength_residual(), Luna::SparseMatrix< T >::col_index(), Luna::LinearEigensystem< T >::compute_real_symmetric_tridiagonal(), Luna::RationalSemi< T >::derivative(), Luna::Vector< X >::dot(), Luna::LinearEigensystem< T >::eigenvectors(), Luna::RationalSemi< T >::evaluate(), Luna::Chebyshev< T >::first_kind(), Luna::SparseMatrix< T >::get(), Luna::Mesh1D< T, X >::get_interpolated_vars(), Luna::Mesh1D< T, X >::get_nodes_vars(), Luna::SparseMatrix< T >::insert(), Luna::Mesh1D< T, X >::integral(), Luna::Newton< T >::iterate(), Luna::Arclength< T >::Jac_arclength_residual(), main(), Luna::Mesh1D< T, X >::Mesh1D(), Luna::SparseMatrix< T >::multiply(), Luna::Matrix< double >::multiply(), Luna::Mesh1D< T, X >::nnodes(), Luna::Spectral< T >::operator()(), Luna::Chebyshev< T >::operator()(), Luna::BandedMatrix< T >::operator*(), Luna::Tridiagonal< T >::operator*(), Luna::Mesh1D< T, X >::output(), Luna::Polynomial< T >::Polynomial(), Luna::Mesh1D< T, X >::read(), Luna::Mesh2D< T >::remesh(), Luna::Mesh1D< T, X >::remesh(), Luna::Chebyshev< T >::second_kind(), Luna::Tridiagonal< T >::set_main(), Luna::Mesh1D< T, X >::set_nodes_vars(), Luna::Mesh2D< T >::set_nodes_vars(), Luna::Matrix< double >::set_row(), Luna::Tridiagonal< T >::set_sub(), Luna::Tridiagonal< T >::set_super(), Luna::Mesh1D< T, X >::set_vars_from_vector(), Luna::Vector< X >::size(), Luna::BandedMatrix< T >::solve(), Luna::Tridiagonal< T >::solve(), Luna::Matrix< double >::solve_basic(), Luna::SparseMatrix< T >::solve_BiCG(), Luna::SparseMatrix< T >::solve_BiCGSTAB(), Luna::SparseMatrix< T >::solve_CG(), Luna::Matrix< double >::solve_LU(), Luna::Matrix< double >::solve_QR(), Luna::SparseMatrix< T >::SparseMatrix(), Luna::SparseMatrix< T >::transpose_multiply(), Luna::Tridiagonal< T >::Tridiagonal(), Luna::Spectral< T >::update_coefficients(), Luna::Arclength< T >::update_theta(), and Luna::Vector< X >::Vector().
   {
     return VECTOR.size();
   }
square()
template<typename T > Vector< T > Luna::Vector< T >::square () const inline
Square all the elements in the Vector.
Returns
Vector of squares of the elements
Definition at line 978 of file Vector.h.
   {
     Vector<T> square;
     for (size_t i=0; i < size(); ++i)
     {
       square.VECTOR.push_back( VECTOR[ i ] * VECTOR[ i ] );
     }
     return square;
   }
sum() [1/2]
template<typename T > T Luna::Vector< T >::sum (const std::size_t & start, const std::size_t & end) inline
Sum of the elements in the Vector (from index start to end)
Parameters
start Start index
end End index
Returns
Sum of the elements in the Vector
Definition at line 884 of file Vector.h.
Referenced by Luna::Vector< X >::norm_1().
   {
     if ( start > end )  { throw Error( "Vector sum: start > end" );}
     if ( start<0 || size()<=start ) {
       throw Error( "Vector sum method range error" );}
     if ( end<0 || size()<=end ) {
       throw Error( "Vector sum method range error" );}
     T Sum( VECTOR[ start ] );
     for ( std::size_t i=start+1; i<=end; ++i )
     {
       Sum += VECTOR[ i ];
     }
     return Sum;
   }
sum() [2/2]
template<typename T > T Luna::Vector< T >::sum () inline
Sum of the elements in the Vector.
Returns
Sum of the elements in the Vector
Definition at line 900 of file Vector.h.
   {
     return this->sum( 0, size() - 1 );
   }
swap()
template<typename T > void Luna::Vector< T >::swap (const std::size_t & i, const std::size_t & j) inline
Swap elements i and j.
Parameters
i The index of the first element to swap
j The index of the second element to swap
Definition at line 731 of file Vector.h.
Referenced by Luna::Matrix< double >::inverse().
   {
     if ( i<0 || size()<=i ) { throw Error( "swap method Vector range error" );}
     if ( j<0 || size()<=j ) { throw Error( "swap method Vector range error" );}
     if ( i == j ) { return; }
     std::swap<T>( VECTOR[ i ], VECTOR[ j ] );
   }
Friends And Related Function Documentation
Matrix< T >
template<class T> friend class Matrix< T > friend
Definition at line 47 of file Vector.h.
operator*
template<class T> Vector<T> operator* (const T & scalar, Vector< T > & vec) friend
Definition at line 120 of file Vector.h.
     {
       return vec * scalar;
     }
operator<<
template<class T> template<class Type > std::ostream& operator<< (std::ostream & os, const Vector< Type > & vec) friend
Output operator <<.
Definition at line 465 of file Vector.h.
Referenced by Luna::Vector< X >::~Vector().
   {
     for (std::size_t i = 0; i < vec.VECTOR.size(); ++i )
     {
       os << std::setw( 6 ) << std::setprecision( 2 ) << std::fixed
          << vec.VECTOR[ i ] << " ";
     }
     return os;
   }
Polynomial< T >
template<class T> friend class Polynomial< T > friend
Definition at line 48 of file Vector.h.
SparseMatrix< T >
template<class T> friend class SparseMatrix< T > friend
Definition at line 49 of file Vector.h.
The documentation for this class was generated from the following file:
include/Luna/Vector.h