Luna: Luna::Chebyshev< T > Class Template Reference
Luna::Chebyshev< T > Class Template Reference
A templated class for Chebyshev basis functions.
#include <Chebyshev.h>
Public Member Functions
Chebyshev ()
Constructor.
virtual ~Chebyshev ()
Destructor (virtual since we have virtual functions)
T operator() (const T &x, const int &n)
Evaluation operator for the nth Chebyshev polynomial at point x.
Vector< T > operator() (const Vector< T > &x, const int &n)
Evaluation operator for the nth Chebyshev polynomial at a Vector of points.
T operator() (const T &x, const int &n, const int &d)
Evaluation operator for the dth derivative of the nth Chebyshev polynomial at point x.
Vector< T > operator() (const Vector< T > &x, const int &n, const int &d)
Evaluation operator for the dth derivative of the nth Chebyshev polynomial at a Vector of points.
Chebyshev< T > & operator= (const Chebyshev< T > &original)
Copy assignment.
T first_kind (const T &x, const int &n)
Return the nth Chebyshev polynomial of the first kind at point x.
Vector< T > first_kind (const Vector< T > &x, const int &n)
Return the nth Chebyshev polynomial at a Vector of points.
T second_kind (const T &x, const int &n)
Return the nth Chebyshev polynomial of the second kind at point x.
Vector< T > second_kind (const Vector< T > &x, const int &n)
Return the nth Chebyshev polynomial of the second kind at a Vector of points.
T gegenbauer (const T &x, const int &n, const int &m)
Return the Gegenbauer or ultraspherical polynomial at a point x.
Vector< T > approximate (T func(const T &), const int &N)
Approximate a given function by a Chebyshev polynomial in the interval [-1, 1].
Vector< T > approximate_even (T func(const T &), const int &N)
Approximate a given function by an even Chebyshev polynomial in the interval [-1, 1].
Vector< T > approximate_odd (T func(const T &), const int &N)
Approximate a given function by an odd Chebyshev polynomial in the interval [-1, 1].
Public Member Functions inherited from Luna::Basis< T >
Basis ()
Constructor.
virtual ~Basis ()
Destructor (virtual since we have virtual functions)
virtual T operator() (const T &x, const std::size_t &n)
Evaluation operator for the nth basis function at point x.
virtual Vector< T > operator() (const Vector< T > &x, const std::size_t &n)
Evaluation operator for the nth basis function at a Vector of points.
virtual T operator() (const T &x, const std::size_t &n, const std::size_t &d)
Evaluation operator for the dth derivative of the nth basis function at point x.
virtual Vector< T > operator() (const Vector< T > &x, const std::size_t &n, const std::size_t &d)
Evaluation operator for the dth derivative of the nth basis function at a Vector of points.
Basis< T > & operator= (const Basis< T > &original)
Copy assignment.
void set_identifier (std::string identifier)
Set the basis function identification string.
std::string get_identifier ()
Get the basis function identification string.
Detailed Description
template<class T>
class Luna::Chebyshev< T >
A templated class for Chebyshev basis functions.
Definition at line 21 of file Chebyshev.h.
Constructor & Destructor Documentation
Chebyshev()
template<typename T > Luna::Chebyshev< T >::Chebyshev ()
Constructor.
Definition at line 141 of file Chebyshev.h.
References Luna::Basis< T >::set_identifier().
     {
         this->set_identifier( "Chebyshev" );
     }
~Chebyshev()
template<typename T > Luna::Chebyshev< T >::~Chebyshev () virtual
Destructor (virtual since we have virtual functions)
Definition at line 147 of file Chebyshev.h.
     {}
Member Function Documentation
approximate()
template<typename T > Vector< T > Luna::Chebyshev< T >::approximate (T funcconst T &, const int & N) inline
Approximate a given function by a Chebyshev polynomial in the interval [-1, 1].
Parameters
func The function to be approximated
N The number of Chebyshev coefficients to calculate
Returns
A Vector containing the Chebyshev coefficients
Definition at line 330 of file Chebyshev.h.
References Spectral_ODE_BVP_plot::c, Luna::Vector< T >::chebyshev_grid(), Heat_plot::N, and Heat_plot::x.
     {
         Vector<T> c( N );
         Vector<double> x;
         x.chebyshev_grid( N );
         for ( std::size_t j = 0; j < N; j++ )
         {
             T sum( 0.0 );
             for ( std::size_t k = 0; k < N; k++ )
             {
                 sum += func( x[ k ] ) * std::cos( ( j * M_PI * ( k + 0.5 ) ) / N );
             }
             c[ j ] = ( 2.0 / N ) * sum;
         }
         return c;
     }
approximate_even()
template<typename T > Vector< T > Luna::Chebyshev< T >::approximate_even (T funcconst T &, const int & N) inline
Approximate a given function by an even Chebyshev polynomial in the interval [-1, 1].
Parameters
func The function to be approximated
N The number of even Chebyshev coefficients to calculate
Returns
A Vector containing the even Chebyshev coefficients
Definition at line 348 of file Chebyshev.h.
References Spectral_ODE_BVP_plot::c, Luna::Vector< T >::chebyshev_grid(), Heat_plot::N, and Heat_plot::x.
     {
         Vector<T> c( N );
         Vector<double> x;
         x.chebyshev_grid( 2 * N );
         for ( std::size_t j = 0; j < N; j++ )
         {
             T sum( 0.0 );
             for ( std::size_t k = 0; k < 2 * N; k++ )
             {
                 sum += func( x[ k ] ) * std::cos( ( 2 * j * M_PI * ( k + 0.5 ) )
                                                                                 / ( 2. * N ) );
             }
             c[ j ] = ( 2.0 / ( 2. * N ) ) * sum;
         }
         return c;
     }
approximate_odd()
template<typename T > Vector< T > Luna::Chebyshev< T >::approximate_odd (T funcconst T &, const int & N) inline
Approximate a given function by an odd Chebyshev polynomial in the interval [-1, 1].
Parameters
func The function to be approximated
N The number of odd Chebyshev coefficients to calculate
Returns
A Vector containing the odd Chebyshev coefficients
Definition at line 368 of file Chebyshev.h.
References Spectral_ODE_BVP_plot::c, Luna::Vector< T >::chebyshev_grid(), Heat_plot::N, Luna::Chebyshev< T >::second_kind(), and Heat_plot::x.
Referenced by main().
     {
         Vector<T> c( N );
         Vector<double> x;
         x.chebyshev_grid( 2 * N );
         for ( std::size_t j = 0; j < N; j++ )
         {
             T sum( 0.0 );
             for ( std::size_t k = 0; k < 2 * N; k++ )
             {
                 sum += func( x[ k ] ) * std::cos( ( ( 2 * j + 1 ) * M_PI *
                                                                                     ( k + 0.5 ) ) / ( 2. * N ) );
             }
             c[ j ] = ( 2.0 / ( 2. * N ) ) * sum;
         }
         return c;
     }
first_kind() [1/2]
template<typename T > T Luna::Chebyshev< T >::first_kind (const T & x, const int & n) inline
Return the nth Chebyshev polynomial of the first kind at point x.
Parameters
x The point where the Chebyshev polynomial is evaluated
n The degree of the Chebyshev polynomial
Returns
The value of the nth degree Chebyshev polynomial at x
Definition at line 235 of file Chebyshev.h.
References Heat_plot::x.
Referenced by Luna::Chebyshev< T >::first_kind(), and Luna::Chebyshev< T >::operator()().
     {
         if ( n == 0 ){
             return 1;
         }
         if ( n == 1 ){
             return x;
         }
         if ( n == 2 ){
             return 2 * x * x - 1.0;
         }
         else {
             /* Could use the recursuve definition
                 return 2 * x * first_kind( x, n - 1 ) - first_kind( x, n - 2 );
             but this is a bit slow.
             */
             T tnm1( 2 * x * x - 1.0 );
             T tnm2( x );
             T tn( tnm1 );
             for ( unsigned l = 3; l <= n; l++ )
             {
                 tn = 2. * x * tnm1 - tnm2;
                 tnm2 = tnm1;
                 tnm1 = tn;
             }
             return tn;
         }
     }
first_kind() [2/2]
template<typename T > Vector< T > Luna::Chebyshev< T >::first_kind (const Vector< T > & x, const int & n) inline
Return the nth Chebyshev polynomial at a Vector of points.
Parameters
x A Vector of points where the Chebyshev polynomial is evaluated
n The degree of the Chebyshev polynomial
Returns
A Vector of values of the nth degree Chebyshev polynomial
Definition at line 266 of file Chebyshev.h.
References Luna::Chebyshev< T >::first_kind(), and Luna::Vector< T >::size().
     {
         Vector<T> temp( x.size() );
         for ( std::size_t i = 0; i != x.size(); i++) {
             temp[ i ] = first_kind( x[ i ], n );
         }
         return temp;
     }
gegenbauer()
template<typename T > T Luna::Chebyshev< T >::gegenbauer (const T & x, const int & n, const int & m) inline
Return the Gegenbauer or ultraspherical polynomial at a point x.
Parameters
x The point where the Gegenbauer polynomial is evaluated
n The degree of the Gegenbauer polynomial
m The m parameter in the Gegenbauer polynomial
Returns
The value of the Gegenbauer polynomial at x
Definition at line 313 of file Chebyshev.h.
References Heat_plot::x.
Referenced by main(), and Luna::Chebyshev< T >::operator()().
     {
         if ( n <= 0 ){
             return 1;
         }
         if ( n == 1 ){
             return 2 * m * x;
         }
         else {
             return ( 2 * x * ( n + m - 1 ) * gegenbauer( x, n - 1, m )
                             - ( n + 2 * m - 2 ) * gegenbauer( x, n - 2, m ) )
                             / ( 1.0 * n );
         }
     }
operator()() [1/4]
template<typename T > T Luna::Chebyshev< T >::operator() (const T & x, const int & n) inline
Evaluation operator for the nth Chebyshev polynomial at point x.
Parameters
x The point where the Chebyshev polynomial is evaluated
n The degree of the Chebyshev polynomial
Returns
The value of the nth degree Chebyshev polynomial at x
Definition at line 151 of file Chebyshev.h.
References Luna::Chebyshev< T >::first_kind().
     {
         return first_kind( x, n );
     }
operator()() [2/4]
template<typename T > Vector< T > Luna::Chebyshev< T >::operator() (const Vector< T > & x, const int & n) inline
Evaluation operator for the nth Chebyshev polynomial at a Vector of points.
Parameters
x A Vector of points where the Chebyshev polynomial is evaluated
n The degree of the Chebyshev polynomial
Returns
A Vector of values of the nth degree Chebyshev polynomial
Definition at line 157 of file Chebyshev.h.
References Luna::Chebyshev< T >::first_kind().
     {
         return first_kind( x, n );
     }
operator()() [3/4]
template<typename T > T Luna::Chebyshev< T >::operator() (const T & x, const int & n, const int & d) inline
Evaluation operator for the dth derivative of the nth Chebyshev polynomial at point x.
Parameters
x The point where the Chebyshev polynomial is evaluated
n The degree of the Chebyshev polynomial
d The derivative to return
Returns
The dth derivative of the nth degree Chebyshev polynomial at the point x
Todo:
TODO d = 4,... (really speeds things up)
Definition at line 163 of file Chebyshev.h.
References Luna::factorial(), and Luna::Chebyshev< T >::gegenbauer().
     {
         if ( n < d ){
             return 0;
         } if ( d == 1 ) {
             return first_kind_derivative( x, n );
         } if ( d == 2 ) {
                 /*if ( x == 1.0 ) {
                     return 1. * n * n * ( n * n - 1 ) / 3.0;
                 }
                 if ( x == -1.0 ) {
                     int p;
                     p = n % 2 ? -1 : 1;
                     return 1. * p * n * n * ( n * n - 1 ) / 3.0;
                 } else {
                     return 1. * n * ( ( n + 1 ) * first_kind( x, n )
                                                                             - second_kind( x, n ) ) / ( x * x - 1. );
                 }*/
                 return first_kind_second_derivative( x, n );
         } if ( d == 3 ) {
             return first_kind_third_derivative( x, n );
             /// \todo TODO d = 4,... (really speeds things up)
         } else {
                 return n * std::pow( 2.0, d - 1 ) * factorial( d - 1 )
                                  * gegenbauer( x, n - d, d );
         }
     }
operator()() [4/4]
template<typename T > Vector< T > Luna::Chebyshev< T >::operator() (const Vector< T > & x, const int & n, const int & d) inline
Evaluation operator for the dth derivative of the nth Chebyshev polynomial at a Vector of points.
Parameters
x A Vector of points where the Chebyshev polynomial is evaluated
n The degree of the Chebyshev polynomial
d The derivative to return
Returns
A Vector of the dth derivative of the nth degree Chebyshev polynomial at the Vector of points
Todo:
TODO d = 4,... (really speeds things up)
Definition at line 193 of file Chebyshev.h.
References Luna::factorial(), Luna::Chebyshev< T >::gegenbauer(), and Luna::Vector< T >::size().
     {
         Vector<T> temp( x.size(), 0 );
         if ( n < d ){
             return temp;
         } if ( d == 1 ) {
             for ( std::size_t i = 0; i != x.size(); i++) {
                 temp[ i ] = first_kind_derivative( x[ i ], n );
             }
             return temp;
         } if ( d == 2 ) {
             for ( std::size_t i = 0; i != x.size(); i++) {
                 temp[ i ] = first_kind_second_derivative( x[ i ], n );
             }
             return temp;
         } if ( d == 3 ) {
             for ( std::size_t i = 0; i != x.size(); i++) {
                 temp[ i ] = first_kind_third_derivative( x[ i ], n );
             }
             return temp;
         /// \todo TODO d = 4,... (really speeds things up)
         } else {
                 for ( std::size_t i = 0; i != x.size(); i++) {
                     temp[ i ] = n * std::pow( 2.0, d - 1 ) * factorial( d - 1 )
                                                 * gegenbauer( x[ i ], n - d, d );
             }
             return temp;
         }
     }
operator=()
template<typename T > Chebyshev< T > & Luna::Chebyshev< T >::operator= (const Chebyshev< T > & original) inline
Copy assignment.
Parameters
original Chebyshev polynomial to be copied
Returns
The new Chebyshev polynomial
Definition at line 225 of file Chebyshev.h.
References Luna::Basis< T >::set_identifier().
   {
         if ( this == &original ){ return *this; }
         this->set_identifier( "Chebyshev" );
     return *this;
   }
second_kind() [1/2]
template<typename T > T Luna::Chebyshev< T >::second_kind (const T & x, const int & n) inline
Return the nth Chebyshev polynomial of the second kind at point x.
Parameters
x The point where the Chebyshev polynomial is evaluated
n The degree of the Chebyshev polynomial
Returns
The value of the nth degree Chebyshev polynomial at x
Definition at line 276 of file Chebyshev.h.
References Heat_plot::x.
Referenced by Luna::Chebyshev< T >::approximate_odd(), main(), and Luna::Chebyshev< T >::second_kind().
     {
         if ( n == 0 ){
             return 1;
         }
         if ( n == 1 ){
             return 2 * x;
         }
         if ( n == 2 ){
             return 4 * x * x - 1.0;
         }
         else {
             T unm1( 4 * x * x - 1.0 );
             T unm2( 2 * x );
             T un( unm1 );
             for ( unsigned l = 3; l <= n; l++ )
             {
                 un = 2. * x * unm1 - unm2;
                 unm2 = unm1;
                 unm1 = un;
             }
             return un;
         }
     }
second_kind() [2/2]
template<typename T > Vector< T > Luna::Chebyshev< T >::second_kind (const Vector< T > & x, const int & n) inline
Return the nth Chebyshev polynomial of the second kind at a Vector of points.
Parameters
x A Vector of points where the Chebyshev polynomial is evaluated
n The degree of the Chebyshev polynomial
Returns
A Vector of values of the nth degree Chebyshev polynomial
Definition at line 303 of file Chebyshev.h.
References Luna::Chebyshev< T >::second_kind(), and Luna::Vector< T >::size().
     {
         Vector<T> temp( x.size() );
         for ( std::size_t i = 0; i != x.size(); i++) {
             temp[ i ] = second_kind( x[ i ], n );
         }
         return temp;
     }
The documentation for this class was generated from the following file:
include/Luna/Chebyshev.h