Luna: Luna::Tridiagonal< T > Class Template Reference
Luna::Tridiagonal< T > Class Template Reference
A Tridiagonal matrix class for use with double and std::complex<double>
#include <Tridiagonal.h>
Public Member Functions
Tridiagonal ()
Constructor for an empty Tridiagonal matrix of unspecified size.
Tridiagonal (const std::size_t &size)
Constructor for a Tridiagonal matrix of specified size.
Tridiagonal (const Vector< T > &sub, const Vector< T > &main, const Vector< T > &super)
Constructor for a Tridiagonal matrix using specified Vectors.
Tridiagonal (const T &sub_elem, const T &main_elem, const T &super_elem, const std::size_t n)
Constructor for a Tridiagonal matrix using specified elements.
~Tridiagonal ()
Destructor.
const T & operator() (const std::size_t &i, const std::size_t &j) const
Indexing operator (read only)
T & operator() (const std::size_t &i, const std::size_t &j)
Indexing operator (read / write)
Tridiagonal< T > & operator= (const Tridiagonal< T > &original)
Copy assignment.
Tridiagonal< T > operator+ () const
Unary +.
Tridiagonal< T > operator- () const
Unary -.
Tridiagonal< T > operator+ (const Tridiagonal< T > &m_plus) const
Binary +.
Tridiagonal< T > operator- (const Tridiagonal< T > &m_minus) const
Binary -.
Tridiagonal< T > operator* (const T &scalar) const
Scalar multiplication.
Tridiagonal< T > operator/ (const T &divisor) const
Scalar division.
Tridiagonal< T > & operator+= (const Tridiagonal< T > &m_plus)
Addition assignment.
Tridiagonal< T > & operator-= (const Tridiagonal< T > &m_minus)
Subtraction assignment.
Tridiagonal< T > & operator*= (const T &scalar)
Scalar multiplication assignment.
Tridiagonal< T > & operator/= (const T &divisor)
Scalar division assigment.
Tridiagonal< T > & operator+= (const T &add)
Constant addition assignment.
Tridiagonal< T > & operator-= (const T &minus)
Constant subtraction assignment.
Vector< T > operator* (Vector< T > &x)
Tridiagonal matrix Vector multiplication.
std::size_t size () const
Size of the main diagonal of the matrix.
void set_sub (const Vector< T > &sub)
Set the subdiagonal of the matrix.
void set_main (const Vector< T > &main)
Set the main diagonal of the matrix.
void set_super (const Vector< T > &super)
Set the superdiagonal of the matrix.
void set_sub (const T &sub_elem)
Set the subdiagonal of the matrix.
void set_main (const T &main_elem)
Set the main diagonal of the matrix.
void set_super (const T &super_elem)
Set the superdiagonal of the matrix.
Vector< T > get_sub ()
Get the subdiagonal of the matrix.
Vector< T > get_main ()
Get the main diagonal of the matrix.
Vector< T > get_super ()
Get the superdiagonal of the matrix.
Vector< T > get_row (const std::size_t &row)
Get a row of the tridiagonal matrix as a Vector.
void transpose_in_place ()
Replace the current Matrix with its transpose.
Tridiagonal< T > transpose () const
Return the transpose of the Matrix.
void resize (const std::size_t &size)
Resize the Tridiagonal matrix.
Tridiagonal< T > conjugate () const
Take the complex conjugate of each element of the Tridiagonal matrix.
Matrix< T > convert ()
Convert the Tridiagonal matrix to a dense Matrix.
Vector< T > solve (const Vector< T > &r)
Solve the Tridiagonal system of equations Tu=r where u and r are Vectors.
Matrix< T > solve (const Matrix< T > &R)
Solve the Tridiagonal system TU=R where U and R are Matrices.
T det ()
Calculate the determinant of the matrix.
Friends
template<class Type >
std::ostream & operator<< (std::ostream &os, const Tridiagonal< Type > &m)
Output operator <<.
Tridiagonal< T > operator* (const T &scalar, Tridiagonal< T > &mat)
Detailed Description
template<class T>
class Luna::Tridiagonal< T >
A Tridiagonal matrix class for use with double and std::complex<double>
Definition at line 24 of file Tridiagonal.h.
Constructor & Destructor Documentation
Tridiagonal() [1/4]
template<class T> Luna::Tridiagonal< T >::Tridiagonal () inline
Constructor for an empty Tridiagonal matrix of unspecified size.
Definition at line 34 of file Tridiagonal.h.
References main(), and Luna::Tridiagonal< T >::size().
 : N( 0 ) {}
Tridiagonal() [2/4]
template<typename T > Luna::Tridiagonal< T >::Tridiagonal (const std::size_t & size) inline
Constructor for a Tridiagonal matrix of specified size.
Parameters
size Size of the main diagonal of the matrix
Definition at line 238 of file Tridiagonal.h.
References Luna::Tridiagonal< T >::size().
   {
     a.resize( size - 1 );
     b.resize( size );
     c.resize( size - 1 );
     N = size;
   }
Tridiagonal() [3/4]
template<typename T > Luna::Tridiagonal< T >::Tridiagonal (const Vector< T > & sub, const Vector< T > & main, const Vector< T > & super) inline
Constructor for a Tridiagonal matrix using specified Vectors.
Parameters
sub The subdiagonal of the matrix as a Vector
main The main diagonal of the matrix as a Vector
super The superdiagonal of the matrix as a Vector
Definition at line 247 of file Tridiagonal.h.
References main(), and Luna::Vector< T >::size().
   {
     if ( main.size() != sub.size() + 1 || main.size() != super.size() + 1 )
     {
       std::string problem;
       problem = "Tridiagonal constructor error: ";
       problem += "size of Vectors are incompatible.";
       throw Error( problem );
     }
     a = sub;
     b = main;
     c = super;
     N = main.size();
   }
Tridiagonal() [4/4]
template<typename T > Luna::Tridiagonal< T >::Tridiagonal (const T & sub_elem, const T & main_elem, const T & super_elem, const std::size_t n) inline
Constructor for a Tridiagonal matrix using specified elements.
Parameters
sub_elem The element to populate the subdiagonal
main_elem The element to populate the main diagonal
super_elem The element to populate the superdiagonal
n The size of the main diagonal
Definition at line 265 of file Tridiagonal.h.
   {
     a.assign( n - 1, sub_elem );
     b.assign( n, main_elem );
     c.assign( n - 1, super_elem );
     N = n;
   }
~Tridiagonal()
template<class T> Luna::Tridiagonal< T >::~Tridiagonal () inline
Destructor.
Definition at line 56 of file Tridiagonal.h.
References Luna::Tridiagonal< T >::operator()(), Luna::Tridiagonal< T >::operator*(), Luna::Tridiagonal< T >::operator+(), Luna::Tridiagonal< T >::operator-(), Luna::Tridiagonal< T >::operator<<, and Luna::Tridiagonal< T >::operator=().
 {}
Member Function Documentation
conjugate()
template<typename T > Tridiagonal< T > Luna::Tridiagonal< T >::conjugate () const inline
Take the complex conjugate of each element of the Tridiagonal matrix.
Returns
The complex conjugate Tridiagonal matrix
Definition at line 673 of file Tridiagonal.h.
   {
     Tridiagonal<T> temp( *this );
     temp.a = temp.a.conjugate();
     temp.b = temp.b.conjugate();
     temp.c = temp.c.conjugate();
     return temp;
   }
convert()
template<typename T > Matrix< T > Luna::Tridiagonal< T >::convert () inline
Convert the Tridiagonal matrix to a dense Matrix.
Returns
The dense Matrix form of the Tridiagonal matrix
Definition at line 683 of file Tridiagonal.h.
   {
     Matrix<T> dense( N, N, 0 );
     if ( N == 0 ) { throw Error( "Tridiagonal error: zero size matrix." ); }
     if ( N == 1 ) {
       dense( 0, 0 ) = b[ 0 ];
       dense( 0, 1 ) = c[ 0 ];
     } else if ( N == 2 ) {
       dense( 0, 0 ) = b[ 0 ];
       dense( 0, 1 ) = c[ 0 ];
       dense( N - 1, N - 2 ) = a[ N - 2 ];
       dense( N - 1, N - 1 ) = b[ N - 1 ];
     } else {
       dense( 0, 0 ) = b[ 0 ];
       dense( 0, 1 ) = c[ 0 ];
       for ( std::size_t i = 1; i < N - 1; i++ )
       {
         dense( i, i - 1 ) = a[ i - 1 ];
         dense( i, i ) = b[ i ];
         dense( i, i + 1 ) = c[ i ];
       }
       dense( N - 1, N - 2 ) = a[ N - 2 ];
       dense( N - 1, N - 1 ) = b[ N - 1 ];
     }
     return dense;
   }
det()
template<typename T > T Luna::Tridiagonal< T >::det () inline
Calculate the determinant of the matrix.
Returns
The determinant of the Tridiagonal matrix
Definition at line 774 of file Tridiagonal.h.
References f.
   {
     Vector<T> f( N + 1 );
     f[ 0 ] = 1;
     f[ 1 ] = b[ 0 ] * f[ 0 ];
     for ( std::size_t j = 2; j < N + 1; j++ )
     {
       f[ j ] = b[ j - 1 ] * f[ j - 1 ] - a[ j - 2 ] * c[ j - 2 ] * f[ j - 2];
     }
     return f[ N ];
   }
get_main()
template<typename T > Vector< T > Luna::Tridiagonal< T >::get_main () inline
Get the main diagonal of the matrix.
Returns
The main diagonal of the matrix as a Vector
Definition at line 608 of file Tridiagonal.h.
   {
     Vector<T> temp( b );
     return temp;
   }
get_row()
template<typename T > Vector< T > Luna::Tridiagonal< T >::get_row (const std::size_t & row) inline
Get a row of the tridiagonal matrix as a Vector.
Parameters
row The row index
Returns
A Vector of the row of the Tridiagonal matrix
Definition at line 622 of file Tridiagonal.h.
   {
     if ( row < 0 || N <= row ){
       throw Error( "Tridiagonal range error in get_row method." );
     }
     Vector<T> temp( N );
     if ( row == 0 )
     {
       temp[ 0 ] = b[ 0 ];
       temp[ 1 ] = c[ 0 ];
     }
     else if ( row == N - 1 )
     {
       temp[ N - 1 ] = b[ N - 1 ];
       temp[ N - 2 ] = a[ N - 2 ];
     }
     else
     {
       temp[ row - 1 ] = a[ row - 1 ];
       temp[ row ]     = b[ row ];
       temp[ row + 1 ] = c[ row ];
     }
     return temp;
   }
get_sub()
template<typename T > Vector< T > Luna::Tridiagonal< T >::get_sub () inline
Get the subdiagonal of the matrix.
Returns
The subdiagonal of the matrix as a Vector
Definition at line 601 of file Tridiagonal.h.
   {
     Vector<T> temp( a );
     return temp;
   }
get_super()
template<typename T > Vector< T > Luna::Tridiagonal< T >::get_super () inline
Get the superdiagonal of the matrix.
Returns
The superdiagonal of the matrix as a Vector
Definition at line 615 of file Tridiagonal.h.
   {
     Vector<T> temp( c );
     return temp;
   }
operator()() [1/2]
template<typename T > const T & Luna::Tridiagonal< T >::operator() (const std::size_t & i, const std::size_t & j) const inline
Indexing operator (read only)
Parameters
i Row index
j Column index
Definition at line 308 of file Tridiagonal.h.
Referenced by Luna::Tridiagonal< T >::~Tridiagonal().
   {
     if ( i<0 || N<=i )  { throw Error( "Tridiagonal range error: row." ); }
     if ( j<0 || N<=j )  { throw Error( "Tridiagonal range error: column." ); }
     // First row
     if ( i == 0 )
     {
       if ( j == 0 ) { return b[ 0 ]; }
       if ( j == 1 ) { return c[ 0 ]; }
       else{
         throw Error( "Tridiagonal error: off diagonal entry." );
       }
     }
     // Last row
     if ( i == N - 1 )
     {
       if ( j == N - 1 ) { return b[ N - 1 ]; }
       if ( j == N - 2 ) { return a[ N - 2 ]; }
       else {
         throw Error( "Tridiagonal error: off diagonal entry." );
       }
     }
     // Middle rows
     if ( i > 0 && i < N - 1 )
     {
       if ( i == j ) { return b[ j ]; }
       if ( i == j + 1 ) { return a[ j ]; }
       if ( i == j - 1 ) { return c[ i ]; }
       else {
         throw Error( "Tridiagonal error: off diagonal entry." );
       }
     }
   }
operator()() [2/2]
template<typename T > T & Luna::Tridiagonal< T >::operator() (const std::size_t & i, const std::size_t & j) inline
Indexing operator (read / write)
Parameters
i Row index
j Column index
Definition at line 344 of file Tridiagonal.h.
   {
     if ( i<0 || N<=i )  { throw Error( "Tridiagonal range error: row." );}
     if ( j<0 || N<=j )  { throw Error( "Tridiagonal range error: column." );}
     // First row
     if ( i == 0 )
     {
       if ( j == 0 ) { return b[ 0 ]; }
       if ( j == 1 ) { return c[ 0 ]; }
       else{
         throw Error( "Tridiagonal error: off diagonal entry." );
       }
     }
     // Last row
     else if ( i == N - 1 )
     {
       if ( j == N - 1 ) { return b[ N - 1 ]; }
       if ( j == N - 2 ) { return a[ N - 2 ]; }
       else {
         throw Error( "Tridiagonal error: off diagonal entry." );
       }
     }
     // Middle rows
     else //if ( i > 0 && i < N - 1 )
     {
       if ( i == j ) { return b[ j ]; }
       if ( i == j + 1 ) { return a[ j ]; }
       if ( i == j - 1 ) { return c[ i ]; }
       else {
         throw Error( "Tridiagonal error: off diagonal entry." );
       }
     }
   }
operator*() [1/2]
template<typename T > Tridiagonal< T > Luna::Tridiagonal< T >::operator* (const T & scalar) const inline
Scalar multiplication.
Parameters
scalar The scalar to multiply the Tridiagonal matrix by
Returns
The Tridiagonal matrix multiplied by the scalar
Definition at line 441 of file Tridiagonal.h.
Referenced by Luna::Tridiagonal< T >::~Tridiagonal().
   {
     Tridiagonal<T> temp( *this );
     temp.a = a * scalar;
     temp.b = b * scalar;
     temp.c = c * scalar;
     return temp;
   }
operator*() [2/2]
template<typename T > Vector< T > Luna::Tridiagonal< T >::operator* (Vector< T > & x) inline
Tridiagonal matrix Vector multiplication.
Parameters
x The Vector which is to be multiplied
Returns
The result vector T * x
Definition at line 526 of file Tridiagonal.h.
References Luna::Vector< T >::size().
   {
     if ( N != x.size() )
     {
       throw Error( "Tridiagonal: dimensions do not agree in multiply method." );
     }
     Vector<T> result( N );
     result[ 0 ] = b[ 0 ] * x[ 0 ] + c[ 0 ] * x[ 1 ];
     for ( std::size_t i = 1; i < N - 1; i++ )
     {
       result[ i ] = a[ i - 1 ] * x[ i - 1 ] + b[ i ] * x[ i ]
                   + c[ i ] * x[ i + 1 ];
     }
     result[ N - 1 ] = a[ N - 2 ] * x[ N - 2 ] + b[ N - 1 ] * x[ N - 1 ];
     return result;
   }
operator*=()
template<typename T > Tridiagonal< T > & Luna::Tridiagonal< T >::operator*= (const T & scalar) inline
Scalar multiplication assignment.
Parameters
scalar The scalar to multiply the Tridiagonal matrix by
Returns
A reference to the Tridiagonal matrix after multiplication by a scalar
Definition at line 490 of file Tridiagonal.h.
   {
     a *= scalar;
     b *= scalar;
     c *= scalar;
     return *this;
   }
operator+() [1/2]
template<typename T > Tridiagonal< T > Luna::Tridiagonal< T >::operator+ () const inline
Unary +.
Returns
The Tridiagonal matrix
Definition at line 395 of file Tridiagonal.h.
Referenced by Luna::Tridiagonal< T >::~Tridiagonal().
   {
     return *this;
   }
operator+() [2/2]
template<typename T > Tridiagonal< T > Luna::Tridiagonal< T >::operator+ (const Tridiagonal< T > & m_plus) const inline
Binary +.
Parameters
m_plus The Tridiagonal matrix to be added
Returns
The sum of this Tridiagonal matrix and m_plus
Definition at line 411 of file Tridiagonal.h.
   {
     Tridiagonal<T> temp( *this );
     if ( m_plus.N != N  )
     {
       throw Error( "Tridiagonal matrix dimension error in + operator." );
     }
     temp.a = a + m_plus.a;
     temp.b = b + m_plus.b;
     temp.c = c + m_plus.c;
     return temp;
   }
operator+=() [1/2]
template<typename T > Tridiagonal< T > & Luna::Tridiagonal< T >::operator+= (const Tridiagonal< T > & m_plus) inline
Addition assignment.
Parameters
m_plus The Tridiagonal matrix to be added
Returns
A reference to the Tridiagonal matrix after addition by m_plus
Definition at line 462 of file Tridiagonal.h.
   {
     if ( m_plus.N != N )
     {
       throw Error( "Tridiagonal matrix dimension error in += operator." );
     }
     a = a + m_plus.a;
     b = b + m_plus.b;
     c = c + m_plus.c;
     return *this;
   }
operator+=() [2/2]
template<typename T > Tridiagonal< T > & Luna::Tridiagonal< T >::operator+= (const T & add) inline
Constant addition assignment.
Parameters
add The constant to be added to each element
Returns
A reference to the Tridiagonal matrix after addition by a constant
Definition at line 508 of file Tridiagonal.h.
   {
     a += add;
     b += add;
     c += add;
     return *this;
   }
operator-() [1/2]
template<typename T > Tridiagonal< T > Luna::Tridiagonal< T >::operator- () const inline
Unary -.
Returns
The negation of the Tridiagonal matrix
Definition at line 401 of file Tridiagonal.h.
Referenced by Luna::Tridiagonal< T >::~Tridiagonal().
   {
     Tridiagonal<T> temp( *this );
     temp.a = - a;
     temp.b = - b;
     temp.c = - c;
     return temp;
   }
operator-() [2/2]
template<typename T > Tridiagonal< T > Luna::Tridiagonal< T >::operator- (const Tridiagonal< T > & m_minus) const inline
Binary -.
Parameters
m_minus The Tridiagonal matrix to be subtracted
Returns
The subtraction of m_minus from this Tridiagonal matrix
Definition at line 426 of file Tridiagonal.h.
   {
     Tridiagonal<T> temp( *this );
     if ( m_minus.N != N )
     {
       throw Error( "Tridiagonal matrix dimension error in - operator." );
     }
     temp.a = a - m_minus.a;
     temp.b = b - m_minus.b;
     temp.c = c - m_minus.c;
     return temp;
   }
operator-=() [1/2]
template<typename T > Tridiagonal< T > & Luna::Tridiagonal< T >::operator-= (const Tridiagonal< T > & m_minus) inline
Subtraction assignment.
Parameters
m_minus The Tridiagonal matrix to be subtracted
Returns
A reference to the Tridiagonal matrix after subtraction by m_minus
Definition at line 476 of file Tridiagonal.h.
   {
     if ( m_minus.N != N )
     {
       throw Error( "Tridiagonal matrix dimension error in -= operator." );
     }
     a = a - m_minus.a;
     b = b - m_minus.b;
     c = c - m_minus.c;
     return *this;
   }
operator-=() [2/2]
template<typename T > Tridiagonal< T > & Luna::Tridiagonal< T >::operator-= (const T & minus) inline
Constant subtraction assignment.
Parameters
minus The constant to be subtracted from each element
Returns
A reference to the Tridiagonal matrix after subtraction by a constant
Definition at line 517 of file Tridiagonal.h.
   {
     a -= minus;
     b -= minus;
     c -= minus;
     return *this;
   }
operator/()
template<typename T > Tridiagonal< T > Luna::Tridiagonal< T >::operator/ (const T & divisor) const inline
Scalar division.
Parameters
divisor The divisor to divide the Tridiagonal matrix by
Returns
The Tridiagonal matrix divided by the divisor
Definition at line 451 of file Tridiagonal.h.
   {
     Tridiagonal<T> temp( *this );
     temp.a = a / divisor;
     temp.b = b / divisor;
     temp.c = c / divisor;
     return temp;
   }
operator/=()
template<typename T > Tridiagonal< T > & Luna::Tridiagonal< T >::operator/= (const T & divisor) inline
Scalar division assigment.
Parameters
divisor The divisor to divide the Tridiagonal matrix by
Returns
A reference to the Tridiagonal matrix after division by a scalar
Definition at line 499 of file Tridiagonal.h.
   {
     a /= divisor;
     b /= divisor;
     c /= divisor;
     return *this;
   }
operator=()
template<typename T > Tridiagonal< T > & Luna::Tridiagonal< T >::operator= (const Tridiagonal< T > & original) inline
Copy assignment.
Parameters
original Tridiagonal matrix to be copied
Returns
The Tridiagonal matrix to which the original matrix is assigned
Definition at line 380 of file Tridiagonal.h.
Referenced by Luna::Tridiagonal< T >::~Tridiagonal().
   {
     if ( this == &original )
     {
       return *this;
     }
     a = original.a;
     b = original.b;
     c = original.c;
     N = original.N;
     return *this;
   }
resize()
template<typename T > void Luna::Tridiagonal< T >::resize (const std::size_t & size) inline
Resize the Tridiagonal matrix.
Parameters
size The new size of the main diagonal of the matrix
Definition at line 664 of file Tridiagonal.h.
References Luna::Tridiagonal< T >::size().
   {
     N = size;
     a.resize( size - 1 );
     b.resize( size );
     c.resize( size - 1 );
   }
set_main() [1/2]
template<typename T > void Luna::Tridiagonal< T >::set_main (const Vector< T > & main) inline
Set the main diagonal of the matrix.
Parameters
main The main diagonal of the matrix as a Vector
Definition at line 563 of file Tridiagonal.h.
References main(), and Luna::Vector< T >::size().
   {
     if ( main.size() != N )
     {
       throw Error( "Tridiagonal error: main diagonal wrong size." );
     }
     b = main;
   }
set_main() [2/2]
template<typename T > void Luna::Tridiagonal< T >::set_main (const T & main_elem) inline
Set the main diagonal of the matrix.
Parameters
main The main diagonal element of the matrix
Definition at line 589 of file Tridiagonal.h.
   {
     b.assign( N, main_elem );
   }
set_sub() [1/2]
template<typename T > void Luna::Tridiagonal< T >::set_sub (const Vector< T > & sub) inline
Set the subdiagonal of the matrix.
Parameters
sub The subdiagonal of the matrix as a Vector
Definition at line 553 of file Tridiagonal.h.
References Luna::Vector< T >::size().
   {
     if ( sub.size() != N - 1 )
     {
       throw Error( "Tridiagonal error: subdiagonal wrong size." );
     }
     a = sub;
   }
set_sub() [2/2]
template<typename T > void Luna::Tridiagonal< T >::set_sub (const T & sub_elem) inline
Set the subdiagonal of the matrix.
Parameters
sub The subdiagonal element of the matrix
Definition at line 583 of file Tridiagonal.h.
   {
     a.assign( N, sub_elem );
   }
set_super() [1/2]
template<typename T > void Luna::Tridiagonal< T >::set_super (const Vector< T > & super) inline
Set the superdiagonal of the matrix.
Parameters
super The superdiagonal of the matrix as a Vector
Definition at line 573 of file Tridiagonal.h.
References Luna::Vector< T >::size().
   {
     if ( super.size() != N - 1 )
     {
       throw Error( "Tridiagonal error: superdiagonal wrong size." );
     }
     c = super;
   }
set_super() [2/2]
template<typename T > void Luna::Tridiagonal< T >::set_super (const T & super_elem) inline
Set the superdiagonal of the matrix.
Parameters
super The superdiagonal element of the matrix
Definition at line 595 of file Tridiagonal.h.
   {
     c.assign( N, super_elem );
   }
size()
template<typename T > std::size_t Luna::Tridiagonal< T >::size () const inline
Size of the main diagonal of the matrix.
Returns
The number of elements in the main diagonal
Definition at line 547 of file Tridiagonal.h.
Referenced by Luna::Tridiagonal< T >::resize(), and Luna::Tridiagonal< T >::Tridiagonal().
   {
     return N;
   }
solve() [1/2]
template<typename T > Vector< T > Luna::Tridiagonal< T >::solve (const Vector< T > & r) inline
Solve the Tridiagonal system of equations Tu=r where u and r are Vectors.
Parameters
r The right-side Vector of the system of equations
Returns
The solution Vector u
Definition at line 716 of file Tridiagonal.h.
References Luna::beta(), Luna::gamma(), Luna::Vector< T >::push_back(), Luna::Vector< T >::push_front(), Luna::Vector< T >::size(), and Heat_plot::u.
Referenced by main(), and Luna::Tridiagonal< T >::solve().
   {
     if ( r.size() != N ) {
       throw Error( "Tridiagonal solve error: Vector incorrect size." );
     }
     Vector<T> u( N );
     Vector<T> a_temp( a );
     Vector<T> c_temp( c );
     a_temp.push_front( 0.0 );
     c_temp.push_back( 0.0 );
     T beta( b[ 0 ] );
     Vector<T> gamma( N );
     if ( b[ 0 ] == 0.0 ) {
       throw Error( "Tridiagonal solve error: zero on leading diagonal." );
     }
     u[ 0 ] = r[ 0 ] / beta;
     for ( int j = 1; j < N; j++ )
     {
       gamma[ j ] = c_temp[ j - 1 ] / beta;
       beta = b[ j ] - a_temp[ j ] * gamma[ j ];
       if ( beta == 0.0 ) {
         throw Error( "Tridiagonal solve error: zero pivot." );
       }
       u[ j ] = ( r[ j ] - a_temp[ j ] * u[ j - 1 ] ) / beta;
     }
     for ( int j = (N - 2); j >= 0; j-- )
     {
       u[ j ] -= gamma[ j + 1 ] * u[ j + 1 ];
     }
     return u;
   }
solve() [2/2]
template<typename T > Matrix< T > Luna::Tridiagonal< T >::solve (const Matrix< T > & R) inline
Solve the Tridiagonal system TU=R where U and R are Matrices.
Parameters
R The right-side Matrix of the system of equations
Returns
The solution Matrix U
Definition at line 755 of file Tridiagonal.h.
References Luna::Matrix< T >::cols(), Luna::Matrix< T >::get_col(), Luna::Matrix< T >::rows(), Luna::Matrix< T >::set_col(), Luna::Tridiagonal< T >::solve(), and Heat_plot::u.
   {
     if ( R.rows() != N ) {
       throw Error( "Tridiagonal solve error: Matrix rows incorrect size." );
     }
     Matrix<T> U( R );
     Vector<T> u( N );
     for ( std::size_t j = 0; j < R.cols(); ++j )
     {
       u = U.get_col( j );
       u = solve( u );
       U.set_col( j, u );
     }
     return U;
   }
transpose()
template<typename T > Tridiagonal< T > Luna::Tridiagonal< T >::transpose () const inline
Return the transpose of the Matrix.
Returns
The transpose of the Matrix
Definition at line 656 of file Tridiagonal.h.
References Luna::Tridiagonal< T >::transpose_in_place().
   {
     Tridiagonal<T> temp( *this );
     temp.transpose_in_place();
     return temp;
   }
transpose_in_place()
template<typename T > void Luna::Tridiagonal< T >::transpose_in_place () inline
Replace the current Matrix with its transpose.
Definition at line 648 of file Tridiagonal.h.
Referenced by Luna::Tridiagonal< T >::transpose().
   {
     Vector<T> temp( a );
     a = c;
     c = temp;
   }
Friends And Related Function Documentation
operator*
template<class T> Tridiagonal<T> operator* (const T & scalar, Tridiagonal< T > & mat) friend
Definition at line 102 of file Tridiagonal.h.
     {
       return mat * scalar;
     }
operator<<
template<class T> template<class Type > std::ostream& operator<< (std::ostream & os, const Tridiagonal< Type > & m) friend
Output operator <<.
Definition at line 277 of file Tridiagonal.h.
Referenced by Luna::Tridiagonal< T >::~Tridiagonal().
   {
     os << std::endl;
     if ( m.N == 0 ) { return os; }
     if ( m.N > 0 )
     {
       for (std::size_t j = 0; j < m.N; ++j )
       {
         std::string tabs;
         for ( std::size_t i = 0; i < j; i++ ){ tabs += "\t"; }
         if ( j == 0 )
         {
           os << "\t" << m.b[ 0 ] << "\t" << m.c[ 0 ] << std::endl;
         }
         else if ( j == m.N - 1 )
         {
           os << tabs << m.a[ m.N - 2 ] << "\t" << m.b[ m.N - 1 ] << std::endl;
         }
         else
         {
           os << tabs << m.a[ j - 1 ] << "\t" << m.b[ j ]
              << "\t" << m.c[ j ] << std::endl;
         }
       }
     }
     return os;
   }
The documentation for this class was generated from the following file:
include/Luna/Tridiagonal.h