Luna: Luna::Triplet< T > Class Template Reference
Luna::Triplet< T > Class Template Reference
A templated class to define triplets.
#include <Triplet.h>
Public Member Functions
Triplet ()
Constructor for an unspecified Triplet.
Triplet (const std::size_t &row, const std::size_t &col, const T &val)
Constructor for a Triplet with specified values.
Triplet (const Triplet< T > &source)
Copy constructor.
~Triplet ()
Destructor.
void operator() (const std::size_t &row, const std::size_t &col, const T &val)
Access operator (write)
Triplet< T > & operator= (const Triplet< T > &original)
Copy assignment.
std::size_t & row ()
The row index of the Triplet.
std::size_t & col ()
The column index of the Triplet.
T & val ()
The value stored in the Triplet.
std::size_t get_row () const
The row index of the Triplet (read only)
std::size_t get_col () const
The column index of the Triplet (read only)
T get_val () const
The value stored in the Triplet (read only)
Friends
template<class Type >
std::ostream & operator<< (std::ostream &os, const Triplet< Type > &trip)
Output operator.
template<class Type >
bool operator< (const Triplet< Type > &t_1, const Triplet< Type > &t_2)
Compare indices for column major sorting.
Detailed Description
template<class T>
class Luna::Triplet< T >
A templated class to define triplets.
Definition at line 20 of file Triplet.h.
Constructor & Destructor Documentation
Triplet() [1/3]
template<class T> Luna::Triplet< T >::Triplet () inline
Constructor for an unspecified Triplet.
Definition at line 30 of file Triplet.h.
Referenced by Luna::Triplet< T >::Triplet().
 : ROW( 0 ), COL( 0 ), VAL( 0 ) {}
Triplet() [2/3]
template<class T> Luna::Triplet< T >::Triplet (const std::size_t & row, const std::size_t & col, const T & val) inline
Constructor for a Triplet with specified values.
Parameters
row Row index
col Column index
val Value
Definition at line 36 of file Triplet.h.
References Luna::Triplet< T >::Triplet().
                 : ROW( row ), COL( col ), VAL( val ) {}
Triplet() [3/3]
template<typename T > Luna::Triplet< T >::Triplet (const Triplet< T > & source) inline
Copy constructor.
Parameters
source The source Triplet to be copied
Definition at line 101 of file Triplet.h.
   {
     *this = source;
   }
~Triplet()
template<class T> Luna::Triplet< T >::~Triplet () inline
Destructor.
Definition at line 44 of file Triplet.h.
References Luna::Triplet< T >::col(), Luna::Triplet< T >::get_col(), Luna::Triplet< T >::get_row(), Luna::Triplet< T >::get_val(), Luna::Triplet< T >::operator()(), Luna::Triplet< T >::operator<<, Luna::Triplet< T >::operator=(), Luna::Triplet< T >::row(), and Luna::Triplet< T >::val().
 {}
Member Function Documentation
col()
template<typename T > std::size_t & Luna::Triplet< T >::col () inline
The column index of the Triplet.
Returns
A reference to the column index
Definition at line 164 of file Triplet.h.
Referenced by Luna::Triplet< T >::operator()(), and Luna::Triplet< T >::~Triplet().
     {
         return COL;
     }
get_col()
template<typename T > std::size_t Luna::Triplet< T >::get_col () const inline
The column index of the Triplet (read only)
Returns
The column index
Definition at line 182 of file Triplet.h.
Referenced by Luna::Triplet< T >::~Triplet().
     {
         return COL;
     }
get_row()
template<typename T > std::size_t Luna::Triplet< T >::get_row () const inline
The row index of the Triplet (read only)
Returns
The row index
Definition at line 176 of file Triplet.h.
Referenced by Luna::Triplet< T >::~Triplet().
     {
         return ROW;
     }
get_val()
template<typename T > T Luna::Triplet< T >::get_val () const inline
The value stored in the Triplet (read only)
Returns
The stored value
Definition at line 188 of file Triplet.h.
Referenced by Luna::Triplet< T >::~Triplet().
     {
         return VAL;
     }
operator()()
template<typename T > void Luna::Triplet< T >::operator() (const std::size_t & row, const std::size_t & col, const T & val) inline
Access operator (write)
Parameters
row Row index
col Column index
val Value
Definition at line 116 of file Triplet.h.
References Luna::Triplet< T >::col(), Luna::Triplet< T >::row(), and Luna::Triplet< T >::val().
Referenced by Luna::Triplet< T >::~Triplet().
     {
         ROW = row;
         COL = col;
         VAL = val;
     }
operator=()
template<typename T > Triplet< T > & Luna::Triplet< T >::operator= (const Triplet< T > & original) inline
Copy assignment.
Parameters
original Triplet to be copied
Returns
The new Triplet
Definition at line 125 of file Triplet.h.
Referenced by Luna::Triplet< T >::~Triplet().
   {
     if ( this == &original ){ return *this; }
     ROW = original.ROW;
         COL = original.COL;
         VAL = original.VAL;
     return *this;
   }
row()
template<typename T > std::size_t & Luna::Triplet< T >::row () inline
The row index of the Triplet.
Returns
A reference to the row index
Definition at line 158 of file Triplet.h.
Referenced by Luna::Triplet< T >::operator()(), and Luna::Triplet< T >::~Triplet().
     {
         return ROW;
     }
val()
template<typename T > T & Luna::Triplet< T >::val () inline
The value stored in the Triplet.
Returns
A reference to the stored value
Definition at line 170 of file Triplet.h.
Referenced by Luna::Triplet< T >::operator()(), and Luna::Triplet< T >::~Triplet().
     {
         return VAL;
     }
Friends And Related Function Documentation
operator<
template<class T> template<class Type > bool operator< (const Triplet< Type > & t_1, const Triplet< Type > & t_2) friend
Compare indices for column major sorting.
Parameters
t_1 The first Triplet
t_2 The second Triplet
Definition at line 135 of file Triplet.h.
     {
         bool compare;
         if ( t_1.COL < t_2.COL )
         {
             compare = true;
         } else if ( t_1.COL == t_2.COL ) {
             if ( t_1.ROW < t_2.ROW )
             {
                 compare = true;
             } else {
                 compare = false;
             }
         } else {
             compare = false;
         }
         return compare;
     }
operator<<
template<class T> template<class Type > std::ostream& operator<< (std::ostream & os, const Triplet< Type > & trip) friend
Output operator.
Definition at line 109 of file Triplet.h.
Referenced by Luna::Triplet< T >::~Triplet().
   {
         os << "( " << trip.ROW << ", " << trip.COL << ", " << trip.VAL << " )";
     return os;
   }
The documentation for this class was generated from the following file:
include/Luna/Triplet.h