Luna: Luna Namespace Reference
Luna Namespace Reference
Namespaces
Example
Utility
Classes
class Arclength
A templated arc length solver class.
class BandedMatrix
A banded matrix class for use with double and std::complex<double>
class Basis
A templated base class to be inherited by spectral basis objects.
struct Bessel
class Chebyshev
A templated class for Chebyshev basis functions.
class Equation
class Equation_1matrix
class Error
A generic runtime error.
class LinearEigensystem
A LinearEigensystem class for use with double and std::complex<double>
class Matrix
A Matrix class for use with double and std::complex<double>
class Mesh1D
A templated class.
class Mesh2D
class Newton
A templated Newton iteration class.
class ODE_BVP
A templated object for boundary-value problems as systems of first-order ordinary differential equations.
class Polynomial
A templated class for defining polynomials.
class RationalSemi
A templated class for Rational Chebyshev basis functions TL_n(y)
class Residual
A templated base class to be inherited by objects that define residuals.
class Residual_with_coords
class SparseMatrix
A SparseMatrix class for use with double and std::complex<double>
class Spectral
A templated class for spectral solutions.
class Timer
A simple timer class for timing methods.
class Tridiagonal
A Tridiagonal matrix class for use with double and std::complex<double>
class Triplet
A templated class to define triplets.
class Vector
A Vector class for use with double and std::complex<double>
Typedefs
typedef std::complex< double > cmplx
Functions
template<class Type >
std::ostream & operator<< (std::ostream &os, const BandedMatrix< Type > &m)
template<class Type >
std::ostream & operator<< (std::ostream &os, const Matrix< Type > &m)
template<typename T >
T gamma (const T &z)
The gamma function
\[ \Gamma(z) = \int_0^{\infty} x^{z-1}e^{-x} dx \]
.
template<typename T >
T lngamma (const T &z)
The log-gamma function.
double factorial (const std::size_t &n)
The factorial function \(n! \).
double lnfactorial (const std::size_t &n)
The Log-Factorial function \(\ln(n!) \).
template<typename T >
T beta (const T &z, const T &w)
The beta function
\[ B(z,w)=\frac{\Gamma(z)\Gamma(w)}{\Gamma(z+w)} \]
.
template<typename T >
T erfccheb (const T &z)
Complementary error function Chebyshev approximation.
template<typename T >
T erf (const T &z)
The error function
\[ erf(z) = \frac{1}{\sqrt{\pi}} \int_{-z}^{z} e^{-t^2} dt \]
.
template<typename T >
T erfc (const T &z)
The complementary error function
\[ erfc(z) = 1 - erf(z) \]
.
template<class Type >
std::ostream & operator<< (std::ostream &os, const Tridiagonal< Type > &m)
template<class Type >
std::ostream & operator<< (std::ostream &os, const Triplet< Type > &trip)
template<class Type >
bool operator< (const Triplet< Type > &t_1, const Triplet< Type > &t_2)
template<class Type >
std::ostream & operator<< (std::ostream &os, const Vector< Type > &vec)
Detailed Description
Todo:
Lots of the Vector methods could be done better using stl algorithms
Typedef Documentation
cmplx
typedef std::complex< double > Luna::cmplx
Definition at line 376 of file LinearEigensystem.h.
Function Documentation
beta()
template<typename T > T Luna::beta (const T & z, const T & w)
The beta function
\[ B(z,w)=\frac{\Gamma(z)\Gamma(w)}{\Gamma(z+w)} \]
.
Parameters
z The first argument of the function \((Re(z) > 0) \)
w The second argument of the function \((Re(w) > 0) \)
Returns
The beta function \(B(z,w) \)
Definition at line 117 of file Special.h.
References lngamma().
Referenced by main(), Luna::Tridiagonal< T >::solve(), Luna::SparseMatrix< T >::solve_BiCG(), Luna::SparseMatrix< T >::solve_BiCGSTAB(), Luna::SparseMatrix< T >::solve_CG(), and Luna::SparseMatrix< T >::solve_QMR().
     {
       return std::exp( lngamma(z) + lngamma(w) - lngamma(z+w) );
     }
erf()
template<typename T > T Luna::erf (const T & z)
The error function
\[ erf(z) = \frac{1}{\sqrt{\pi}} \int_{-z}^{z} e^{-t^2} dt \]
.
Parameters
z The arguement of the function
Returns
The error function \(erf(z) \)
Definition at line 157 of file Special.h.
References erfccheb().
Referenced by main().
     {
       if ( std::real( z ) >= 0. ) return 1.0 - erfccheb( z );
       else return erfccheb( - z ) - 1.0;
     }
erfc()
template<typename T > T Luna::erfc (const T & z)
The complementary error function
\[ erfc(z) = 1 - erf(z) \]
.
Parameters
z The arguement of the function
Returns
The complementary error function \(erfc(z) \)
Definition at line 167 of file Special.h.
References erfccheb().
Referenced by main().
     {
       if ( std::real( z ) >= 0. ) return erfccheb( z );
       else return 2.0 - erfccheb( - z );
     }
erfccheb()
template<typename T > T Luna::erfccheb (const T & z)
Complementary error function Chebyshev approximation.
Parameters
z The arguement of the function
Returns
The Chebyshev approximation to the complementary error function
Definition at line 126 of file Special.h.
References Heat_plot::t.
Referenced by erf(), and erfc().
     {
       int ncof( 28 );
       const double cof[28] = {-1.3026537197817094, 6.4196979235649026e-1,
         1.9476473204185836e-2,-9.561514786808631e-3,-9.46595344482036e-4,
         3.66839497852761e-4,4.2523324806907e-5,-2.0278578112534e-5,
         -1.624290004647e-6,1.303655835580e-6,1.5626441722e-8,-8.5238095915e-8,
         6.529054439e-9,5.059343495e-9,-9.91364156e-10,-2.27365122e-10,
         9.6467911e-11, 2.394038e-12,-6.886027e-12,8.94487e-13, 3.13092e-13,
         -1.12708e-13,3.81e-16,7.106e-15,-1.523e-15,-9.4e-17,1.21e-16,-2.8e-17};
       T t, ty, tmp, d = 0., dd = 0.;
       if ( std::real( z ) < 0. )
       {
         throw Error(" Nonnegative argument required in erfccheb");
       }
       t = 2. / ( 2. + z );
       ty = 4. * t - 2.;
       for ( std::size_t j = ncof - 1; j > 0; j-- )
       {
         tmp = d;
         d = ty * d - dd + cof[ j ];
         dd = tmp;
       }
       return t * exp( - z * z + 0.5 * ( cof[ 0 ] + ty * d ) - dd );
     }
factorial()
double Luna::factorial (const std::size_t & n)
The factorial function \(n! \).
Parameters
n The arguement of the function
Returns
The factorial of n as a double precision floating-point number
Definition at line 75 of file Special.h.
Referenced by main(), and Luna::Chebyshev< T >::operator()().
     {
       // Create static table on the first call then lookup on subsequent calls
       static std::vector<double> a( 171 );
       static bool init( true );
       if ( init ) {
         init = false;
         a[ 0 ] = 1.;
         for ( std::size_t i = 1; i < 171; i++ )
         {
           a[ i ] = i * a[ i - 1 ];
         }
       }
       if ( n < 0 || n > 170 ){ throw Error( " Range error in factorial" ); }
       return a[ n ];
     }
gamma()
template<typename T > T Luna::gamma (const T & z)
The gamma function
\[ \Gamma(z) = \int_0^{\infty} x^{z-1}e^{-x} dx \]
.
Parameters
z The argument of the function (not a negative integer or zero)
Returns
The gamma function \(\Gamma(z)\) using Spouge's approximation
Definition at line 24 of file Special.h.
References Spectral_ODE_BVP_plot::c, and Luna::Vector< T >::resize().
Referenced by main(), Luna::Tridiagonal< T >::solve(), and Luna::SparseMatrix< T >::solve_QMR().
     {
       const int a = 12;
       Vector<T> c;
       c.resize( a );
       int k;
       T accm;
       double factrl = 1.0; // (k - 1)!*(-1)^k with 0!==1
       c[ 0 ] = std::sqrt( 2.0 * M_PI );
       for(k=1; k < a; k++) {
         c[ k ] =    std::exp( 1. * a - k )
                   * std::pow( 1. * a - k, k - 0.5 ) / factrl;
         factrl *= -k;
       }
       accm = c[ 0 ];
       for( k = 1; k < a; k++ )
       {
         accm += c[ k ] / ( z + 1. * k );
       }
       accm *= std::exp( - ( z + 1. * a ) ) * std::pow( z + 1. * a, z + 0.5 );
       return accm / z; // Gamma(z) = Gamma(z+1) / z
     }
lnfactorial()
double Luna::lnfactorial (const std::size_t & n)
The Log-Factorial function \(\ln(n!) \).
Parameters
n The arguement of the function
Returns
The log-factorial as a double precision floating-point number
Definition at line 95 of file Special.h.
References lngamma().
Referenced by main().
     {
       static const std::size_t NTOP( 2000 );
       static std::vector<double> a( NTOP );
       static bool init( true );
       if ( init ) {
         init = false;
         for ( std::size_t i = 0; i < NTOP; i++ )
         {
           a[ i ] = lngamma( i + 1. );
         }
       }
       if ( n < 0 ){ throw Error( " Negative arguement in lnfactorial" ); }
       if ( n < NTOP ){ return a[ n ]; }
       return lngamma( n + 1. ); // Out of range of table
     }
lngamma()
template<typename T > T Luna::lngamma (const T & z)
The log-gamma function.
Parameters
z The argument of the function \((z > 0) \)
Returns
The log of the gamma function \(\ln \Gamma(z) \)
Definition at line 52 of file Special.h.
References Heat_plot::x, and Spectral_ODE_Rational_plot::y.
Referenced by beta(), lnfactorial(), and main().
{
         T x, tmp, y, ser;
         static const double cof[ 14 ]={ 57.1562356658629235, -59.5979603554754912,
         14.1360979747417471, -0.491913816097620199, .339946499848118887e-4,
         .465236289270485756e-4, -.983744753048795646e-4, .158088703224912494e-3,
         -.210264441724104883e-3, .217439618115212643e-3, -.164318106536763890e-3,
         .844182239838527433e-4, -.261908384015814087e-4, .368991826595316234e-5 };
         if ( std::real( z ) <= 0) throw Error( " lngamma: invalid argument " );
         y = x = z;
         tmp = x + 5.24218750000000000;
         tmp = ( x + 0.5 ) * log( tmp ) - tmp;
         ser = 0.999999999999997092;
         for ( std::size_t j = 0;j < 14; j++ )
       {
         y += 1.0;
         ser += cof[ j ] / y;
       }
         return tmp + std::log( 2.5066282746310005 * ser / x );
     }
operator<()
template<class Type > bool Luna::operator< (const Triplet< Type > & t_1, const Triplet< Type > & t_2) inline
Parameters
t_1 The first Triplet
t_2 The second Triplet
Definition at line 135 of file Triplet.h.
     {
         bool compare;
         if ( t_1.COL < t_2.COL )
         {
             compare = true;
         } else if ( t_1.COL == t_2.COL ) {
             if ( t_1.ROW < t_2.ROW )
             {
                 compare = true;
             } else {
                 compare = false;
             }
         } else {
             compare = false;
         }
         return compare;
     }
operator<<() [1/5]
template<class Type > std::ostream& Luna::operator<< (std::ostream & os, const Triplet< Type > & trip) inline
Definition at line 109 of file Triplet.h.
   {
         os << "( " << trip.ROW << ", " << trip.COL << ", " << trip.VAL << " )";
     return os;
   }
operator<<() [2/5]
template<class Type > std::ostream& Luna::operator<< (std::ostream & os, const BandedMatrix< Type > & m) inline
Definition at line 221 of file BandedMatrix.h.
   {
     os << std::endl;
     if ( m.N == 0 ) { return os; }
     if ( m.N > 0 )
     {
       for ( std::size_t i = 0; i < m.N; ++i )
       {
         for ( std::size_t j = 0; j < m.N; ++j )
         {
           if ( j > i + m.M2 || i > j + m.M1 )
           {
             os << "\t";
           } else {
             os << "\t" << m.COMPACT( i, j - i + m.M1 );
           }
         }
         os << std::endl;
       }
     }
     return os;
   }
operator<<() [3/5]
template<class Type > std::ostream& Luna::operator<< (std::ostream & os, const Tridiagonal< Type > & m) inline
Definition at line 277 of file Tridiagonal.h.
   {
     os << std::endl;
     if ( m.N == 0 ) { return os; }
     if ( m.N > 0 )
     {
       for (std::size_t j = 0; j < m.N; ++j )
       {
         std::string tabs;
         for ( std::size_t i = 0; i < j; i++ ){ tabs += "\t"; }
         if ( j == 0 )
         {
           os << "\t" << m.b[ 0 ] << "\t" << m.c[ 0 ] << std::endl;
         }
         else if ( j == m.N - 1 )
         {
           os << tabs << m.a[ m.N - 2 ] << "\t" << m.b[ m.N - 1 ] << std::endl;
         }
         else
         {
           os << tabs << m.a[ j - 1 ] << "\t" << m.b[ j ]
              << "\t" << m.c[ j ] << std::endl;
         }
       }
     }
     return os;
   }
operator<<() [4/5]
template<class Type > std::ostream& Luna::operator<< (std::ostream & os, const Matrix< Type > & m) inline
Definition at line 461 of file Matrix.h.
   {
     os << std::endl;
     for (std::size_t j = 0; j < m.ROWS; ++j )
     {
       if ( m.MATRIX[ j ].size() != m.COLS ){
         throw Error( "Matrix dimension error: wrong sized row in Matrix." );
       }
       os << "\t" << m.MATRIX[ j ] << std::endl;
     }
     return os;
   }
operator<<() [5/5]
template<class Type > std::ostream& Luna::operator<< (std::ostream & os, const Vector< Type > & vec) inline
Definition at line 465 of file Vector.h.
   {
     for (std::size_t i = 0; i < vec.VECTOR.size(); ++i )
     {
       os << std::setw( 6 ) << std::setprecision( 2 ) << std::fixed
          << vec.VECTOR[ i ] << " ";
     }
     return os;
   }