Luna: Spectral_Poisson_plot Namespace Reference
Spectral_Poisson_plot Namespace Reference
Variables
int N_levels = 11
data = np.loadtxt("./DATA/Spectral_Poisson.dat")
x = data[:,0]
y = data[:,1]
u_exact = data[:,2]
u_spectral = data[:,3]
error = u_exact - u_spectral
min_x = np.min(x)
max_x = np.max(x)
min_y = np.min(y)
max_y = np.max(y)
int npts = 500
xi = np.linspace(min_x, max_x, npts)
yi = np.linspace(min_y, max_y, npts)
u_exacti = mlab.griddata(x, y, u_exact, xi, yi, interp = 'linear')
u_spectrali = mlab.griddata(x, y, u_spectral, xi, yi, interp = 'linear')
errori = mlab.griddata(x, y, error, xi, yi, interp = 'linear')
string origin = 'lower'
cmap = plt.cm.YlGnBu_r
levels = np.linspace(np.min(u_exact), np.max(u_exact), N_levels)
CS
CB = plt.colorbar(CS, shrink=1)
rotation
axes = plt.gca()
Variable Documentation
axes
Spectral_Poisson_plot.axes = plt.gca()
Definition at line 54 of file Spectral_Poisson_plot.py.
CB
Spectral_Poisson_plot.CB = plt.colorbar(CS, shrink=1)
Definition at line 47 of file Spectral_Poisson_plot.py.
cmap
Spectral_Poisson_plot.cmap = plt.cm.YlGnBu_r
Definition at line 33 of file Spectral_Poisson_plot.py.
CS
Spectral_Poisson_plot.CS
Initial value:
 =  plt.contourf(xi, yi, u_exacti, levels,
                   #[-1, -0.1, 0, 0.1],
                   #alpha=0.5,
                   cmap=cmap,
                   origin=origin,
                   extend='both')
Definition at line 39 of file Spectral_Poisson_plot.py.
data
Spectral_Poisson_plot.data = np.loadtxt("./DATA/Spectral_Poisson.dat")
Definition at line 8 of file Spectral_Poisson_plot.py.
error
Spectral_Poisson_plot.error = u_exact - u_spectral
Definition at line 15 of file Spectral_Poisson_plot.py.
errori
Spectral_Poisson_plot.errori = mlab.griddata(x, y, error, xi, yi, interp = 'linear')
Definition at line 30 of file Spectral_Poisson_plot.py.
levels
Spectral_Poisson_plot.levels = np.linspace(np.min(u_exact), np.max(u_exact), N_levels)
Definition at line 35 of file Spectral_Poisson_plot.py.
max_x
Spectral_Poisson_plot.max_x = np.max(x)
Definition at line 19 of file Spectral_Poisson_plot.py.
max_y
Spectral_Poisson_plot.max_y = np.max(y)
Definition at line 21 of file Spectral_Poisson_plot.py.
min_x
Spectral_Poisson_plot.min_x = np.min(x)
Definition at line 18 of file Spectral_Poisson_plot.py.
min_y
Spectral_Poisson_plot.min_y = np.min(y)
Definition at line 20 of file Spectral_Poisson_plot.py.
N_levels
int Spectral_Poisson_plot.N_levels = 11
Definition at line 6 of file Spectral_Poisson_plot.py.
npts
int Spectral_Poisson_plot.npts = 500
Definition at line 24 of file Spectral_Poisson_plot.py.
origin
string Spectral_Poisson_plot.origin = 'lower'
Definition at line 32 of file Spectral_Poisson_plot.py.
rotation
Spectral_Poisson_plot.rotation
Definition at line 51 of file Spectral_Poisson_plot.py.
u_exact
Spectral_Poisson_plot.u_exact = data[:,2]
Definition at line 13 of file Spectral_Poisson_plot.py.
u_exacti
Spectral_Poisson_plot.u_exacti = mlab.griddata(x, y, u_exact, xi, yi, interp = 'linear')
Definition at line 28 of file Spectral_Poisson_plot.py.
u_spectral
Spectral_Poisson_plot.u_spectral = data[:,3]
Definition at line 14 of file Spectral_Poisson_plot.py.
u_spectrali
Spectral_Poisson_plot.u_spectrali = mlab.griddata(x, y, u_spectral, xi, yi, interp = 'linear')
Definition at line 29 of file Spectral_Poisson_plot.py.
x
Spectral_Poisson_plot.x = data[:,0]
Definition at line 10 of file Spectral_Poisson_plot.py.
xi
Spectral_Poisson_plot.xi = np.linspace(min_x, max_x, npts)
Definition at line 26 of file Spectral_Poisson_plot.py.
Referenced by main(), and Luna::SparseMatrix< T >.solve_QMR().
y
Spectral_Poisson_plot.y = data[:,1]
Definition at line 11 of file Spectral_Poisson_plot.py.
yi
Spectral_Poisson_plot.yi = np.linspace(min_y, max_y, npts)
Definition at line 27 of file Spectral_Poisson_plot.py.
Referenced by main().