Luna: Luna::Example Namespace Reference
Luna::Example Namespace Reference
Classes
class Arc_problem
class free_BC
class left_BC
class nonlinear_equation
class plate_BC
class right_BC
class test_equation
class test_residual
Functions
double KB (0.0)
double initial_guess (const double &y)
double initial_guess_H (const double &y)
double initial_guess_G (const double &y)
double function (const double &x)
Function Documentation
function()
double Luna::Example::function (const double & x)
Definition at line 13 of file Spectral_test.cpp.
References Heat_plot::x.
     {
       return std::sinh( x );
     }
initial_guess()
double Luna::Example::initial_guess (const double & y)
Definition at line 25 of file Falkner.cpp.
Referenced by main().
     {
       return - y * exp( - y );
     }
initial_guess_G()
double Luna::Example::initial_guess_G (const double & y)
Definition at line 21 of file Falkner_3D_alternative.cpp.
Referenced by main().
     {
       //return 2. + ( y * y + 2 * y + 2. ) * exp( - y );
       //return 0.0;
       return 0.35 * ( 1.0 - exp( - y ) );
       //return y + exp( - y ) - std::erf( 1. / y ) - y * exp( - 1. / ( y * y ) );
     }
initial_guess_H()
double Luna::Example::initial_guess_H (const double & y)
Todo:
need K parameter
Definition at line 15 of file Falkner_3D_alternative.cpp.
Referenced by main().
     {
       /// \todo need K parameter
       return - y * exp( - y );
     }
KB()
double Luna::Example::KB (0. 0)
Referenced by Luna::Example::plate_BC::residual_fn().