Luna: Examples/Spectral/ODE_BVP.cpp File Reference
ODE_BVP.cpp File Reference
The equation
\[ u''(x) - (x^6 + 3x^2)u(x) = 0 \]
is solved subject to the boundary conditions \(u(-1) = u(1) = 1. \) The system is solved using a Chebyshev spectral method.
#include "Luna/Core"
#include "Luna/ODE"
#include "Luna/Spectral"
Namespaces
Luna
Luna::Example
Functions
int main ()
Detailed Description
The equation
\[ u''(x) - (x^6 + 3x^2)u(x) = 0 \]
is solved subject to the boundary conditions \(u(-1) = u(1) = 1. \) The system is solved using a Chebyshev spectral method.
The solution \(u(x) \) is symmetric so only even Chebyshev polynomials are needed to approximate the solution such that
\[ u(x) \approx u_n(x) = \sum_{i=0}^n a_i T_{2i}(x) .\]
Here \(n \) is the number of spectral coefficients \(a_i \) and \(T_{2i}(x) \) are the corresponding Chebyshev polynomials. The exact solution is given by
\[ u(x) = \exp \left[ \frac{x^4 - 1}{4} \right]. \]
The spectral solution is found on \(x \in [0,1] \) and then because the solution is symmetric this gives the solution in the entire domain \(x \in [-1,1]. \)
Definition in file ODE_BVP.cpp.
Function Documentation
main()
int main ()
Definition at line 32 of file ODE_BVP.cpp.
References Luna::Vector< T >::half_lobatto_grid(), Luna::Vector< T >::linspace(), Heat_plot::N, Luna::Vector< T >::norm_2(), Luna::Mesh1D< T, X >::output(), Luna::Vector< T >::push_back(), Luna::Vector< T >::size(), Luna::Matrix< T >::solve(), Heat_plot::x, and Spectral_Poisson_plot::xi.
 {
   cout << "------------------------- ODE_BVP ------------------------" << endl;
   cout << " * The equation u'' + (x^6 + 3x^2)u = 0 is solved " << endl
        << " * subject to the boundary conditions u(-1) = u(1) = 0." << endl
        << " * Only symmetric even Chebyshev polynomials are used in" << endl
        << " * the spectral solution. " << endl;
   int n( 1 );           // Number of spectral coefficients
   int N( 100 );         // Number of output points
   int num_out( 3 );     // Number of different n values
   int step( 2 );
   Vector<int> n_values;
   Vector<double> grid;
   grid.linspace( -1.0, 1.0, N );
   Mesh1D<double> solution( grid, 1 + num_out );
   Vector<double> exact( N ), numerical( N );
   for ( std::size_t i = 0; i < N; i++ )
   {
     solution( i, 0 ) = std::exp( 0.25 * ( std::pow( grid[ i ], 4 ) - 1.0 ) );
     exact[ i ] = solution( i, 0 );
   }
   int counter( 0 );
   do
   {
     Vector<double> x;
     x.half_lobatto_grid( n );
     Matrix<double> L( n, n, 0.0 );
     Vector<double> F( n ), a( n );
     Chebyshev<double> cheby;
     // x = 1 boundary u(1) = 1
     for ( std::size_t j = 0; j < n; j++ )
     {
       L( 0, j ) = cheby( 1.0, 2 * j );
     }
     F[ 0 ] = 1.0;
     // Internal nodes and x = 0 symmetric boundary
     for ( std::size_t i = 1; i < n; i++ )
     {
       double xi = x[ i ];
       double xi2 = xi * xi;
       double xi6 = std::pow( xi, 6 );
       for ( std::size_t j = 0; j < n; j++ )
       {
         L( i, j ) = cheby( xi, 2 * j, 2 );                     // u_xx
         L( i, j ) += - ( xi6 + 3 * xi2 ) * cheby( xi, 2 * j ); // (x^6 + 3x^2)u
       }
       F[ i ] = 0.0;
     }
     cout << " L = " << L << endl;
     // Solve the system for the spectral coefficients
     a = L.solve( F );
     Spectral<double> spectral( a, "EvenChebyshev" );
     numerical = spectral( grid );
     Vector<double> diff;
     diff = exact - numerical;
     cout << " * ||u_exact - u_spectral|| ( n = " << n << " ) = "
          << std::scientific << diff.norm_2() << endl;
     for ( std::size_t i = 0; i < N; i++ )
     {
       solution( i, 1 + counter ) = spectral( grid[ i ] );
     }
     n_values.push_back( n );
     n += step;
     counter++;
   }while( counter < num_out );
   solution.output( "./DATA/Spectral_ODE_BVP.dat" );
   cout << " * For a comparison of the spectral/exact solutions run: " << endl;
   cout << "python Plotting/Spectral_ODE_BVP_plot.py --n";
   for ( std::size_t i = 0; i < n_values.size(); i++ )
   {
     cout << " " << n_values[ i ];
   }
   cout << endl;
   cout << "--- FINISHED ---" << endl;
 }