Luna: Examples/Root_finding.cpp File Reference
Root_finding.cpp File Reference
Examples of the numerical solution of equations using Newton's method and arc-length continuation and the solution of polynomial equations.
#include "Luna/Core"
Classes
class Luna::Example::test_residual
class Luna::Example::Arc_problem
Namespaces
Luna
Luna::Example
Functions
int main ()
Detailed Description
Examples of the numerical solution of equations using Newton's method and arc-length continuation and the solution of polynomial equations.
Definition in file Root_finding.cpp.
Function Documentation
main()
int main ()
Definition at line 57 of file Root_finding.cpp.
References Luna::Newton< T >::arclength_solve(), Spectral_ODE_BVP_plot::c, Luna::Polynomial< T >::coeffs(), f, Luna::Arclength< T >::init_arc(), Luna::Example::Arc_problem::p, Luna::Polynomial< T >::quadratic_solve(), Luna::Polynomial< T >::roots(), Luna::Newton< T >::solve(), Heat_plot::u, and ODE_BVP_System_plot::v.
 {
   cout << "----------------- Root finding -----------------" << endl;
   cout << " * Solving the set of equations " << endl
        << " * x^3 + y - 1 = 0, " << endl
        << " * y^3 - x + 1 = 0, " << endl
        << " * using Newton's method and the initial guess " << endl;
   test_residual Res;                           // Create residual
   Vector<double> x_0(2, 0.5);                        // Initial guess
   x_0[1] = 0.25;
   cout << " * x_0 = " << x_0 << endl;
   Newton<double> newton( &Res );               // Create Newton object
   newton.solve( x_0 );                               // Solve the system
   cout << " * gives the solution (x,y)= " << x_0 << endl;
   cout << endl << "----- Arc continuation of x^2 + p^2 = 2.0 -----" << endl;
   // Instantiate the problem
   Arc_problem arc_prob;
   arc_prob.p = 1.0;
   const double tol = 1.e-6;
   // Scalar newton iteration problem
   Newton<double> newton_arc( &arc_prob, 8, tol );
   // Initial guess
   Vector<double> state( 1, 1.0 );
   double arc_step( 0.1 );
   double max_arc_step( 0.5 );
   newton_arc.init_arc( state, &arc_prob.p, arc_step, max_arc_step );
   do
   {
     newton_arc.arclength_solve( state );
     cout << "x = " << state[ 0 ] << ", p = " << arc_prob.p << endl;
   }while( state[ 0 ] < 1.0 );
   cout << endl << "--------- Polynomial equations ---------" << endl;
   cout << " * Define the function f(x) = -1 + 2x + x^2" << endl;
   Polynomial<double> f( std::vector<double> { -1.0, 2.0, 1.0, 1.0 } );
   cout << " * Access the x coefficient f[1] = " << f[1] << endl;
   cout << " * Evaluate the polynomial at x = 0.1 " << endl
        << " * f( 0.1 ) = " << f( 0.1 ) << endl << endl;
   cout << " * Solve the complex quadratic equation " << endl
        << " * ( 1 + i )x^2 - ( 2 + i )x - 1 = 0 " << endl;
   Polynomial< std::complex<double> > p;
   std::complex<double> a ( 1.0, 1.0 );
   std::complex<double> b ( - 2.0, - 1.0 );
   std::complex<double> c ( - 1.0, 0.0 );
   Vector< std::complex<double> > roots;
   roots = p.quadratic_solve( a, b, c );
   cout << " * The two roots of the equation are" << endl;
   cout << " * x_0 = " << roots[ 0 ] << endl;
   cout << " * x_1 = " << roots[ 1 ] << endl << endl;
   cout << " * Solve the cubic equation" << endl
        << " * 2x^3 + x^2 + 2x - 1 = 0 " << endl;
   Vector<std::complex<double>> f_roots;
   f_roots = f.cubic_solve( 2.0, 1.0, 2.0, - 1.0 );
   cout << " * The three roots of the equation are" << endl;
   cout << " * x_0 = " << f_roots[ 0 ] << endl;
   cout << " * x_1 = " << f_roots[ 1 ] << endl;
   cout << " * x_2 = " << f_roots[ 2 ] << endl << endl;
   cout << " * Dividing the polynomial u(x) = x^3 - 2x^2 - 4" << endl
        << " * by v(x) = x - 3 gives the quotient " << endl;
   Polynomial<double> u( std::vector<double> { -4.0, 0.0, -2.0, 1.0 } );
   Polynomial<double> v( std::vector<double> { -3.0, 1.0 } );
   Polynomial<double> q, r;
   u.polydiv( v, q, r );
   cout << " * q(x) = " << q.coeffs()[0] << " + " << q.coeffs()[1] << "x + "
        << q.coeffs()[2] << "x^2" << endl
        << " * and the remainder " << endl
        << " * r(x) = " << r.coeffs() << endl
        << " * such that u(x) = q(x) * v(x) + r(x)." << endl << endl;
   cout << " * Find the roots of the quartic equation " << endl
        << " * 3 + x + x^2 + x^4 = 0 using Laguerre's method. " << endl;
   Polynomial<double> poly( std::vector<double> { 3.0, 1.0, 1.0, 0.0, 1.0 } );
   Vector<std::complex<double>> poly_roots;
   poly_roots = poly.roots( true );
   cout << " * The roots of the equation are" << endl
        << " * x_0 = " << poly_roots[0] << endl
        << " * x_1 = " << poly_roots[1] << endl
        << " * x_2 = " << poly_roots[2] << endl
        << " * x_3 = " << poly_roots[3] << endl << endl;
   cout << "--- FINISHED ---" << endl;
 }