Luna: Examples/Spectral/Spectral_test.cpp File Reference
Spectral_test.cpp File Reference
#include "Luna/Core"
#include "Luna/ODE"
#include "Luna/Spectral"
Namespaces
Luna
Luna::Example
Functions
double Luna::Example::function (const double &x)
int main ()
Function Documentation
main()
int main ()
Definition at line 24 of file Spectral_test.cpp.
References Luna::Vector< T >::chebyshev_grid(), Luna::Chebyshev< T >::gegenbauer(), Heat_plot::N, Luna::Chebyshev< T >::second_kind(), and Heat_plot::x.
 {
   cout << "------------------- Spectral_test ------------------" << endl;
   Basis<double> basis_function;
   int N( 5 );
   Vector<double> x;
   x.chebyshev_grid( N );
   cout << " x (Chebyshev) = " << x << endl;
   Chebyshev<double> cheby;
   cout << " cheby( 0.5, 3 ) = " << cheby( 0.5, 3 ) << endl;
   cout << " cheby( x, 3 ) = " << cheby( x, 3 ) << endl;
   cout << " gegenbauer( 0.0, 4, 2 ) = " << cheby.gegenbauer( 0.0, 4, 2 ) << endl;
   cout << " cheby( 1.0, 3, 1 ) = " << cheby( 0.1, 1, 2 ) << endl;
   cout << " cheby( x, 3, 2 ) = " << cheby( x, 3, 2 ) << endl;
   cout << " cheby.second_kind( 0.5, 6 ) = " << cheby.second_kind( 0.5, 6 ) << endl;
   cout << " cheby.second_kind( x, 1 ) = " << cheby.second_kind( x, 1 ) << endl;
   /*Vector<double> c( N, 0.0 );
   for ( std::size_t j = 0; j < N; j++ )
   {
     double sum( 0.0 );
     for ( std::size_t k = 0; k < N; k++ )
     {
       sum += Example::function( x[ k ] ) * std::cos( ( j * M_PI * ( k + 0.5 ) ) / N );
     }
     c[ j ] = ( 2.0 / N ) * sum;
   }
   cout << " c = " << c << endl;
   c = cheby.approximate_odd( Example::function, N / 2 );
   cout << " c = " << std::scientific << c << endl;
   Spectral<double> spectral( c, "OddChebyshev" );*/
   /*double L( 3.0 );
   RationalSemi<double> rationalsemi( L );
   Vector<double> y;
   y.rational_semi_grid( N, L );
   cout << " y (Rational Chebyshev Semi) = " << y << endl;
   y.push_back( 0.0 );
   cout << " y (Rational Chebyshev Semi) = " << y << endl;
   cout << " rationalsemi( 0.5, 1 ) = " << rationalsemi( 0.5, 1 ) << endl;
   cout << " rationalsemi( y, 1 ) = " << rationalsemi( y, 1 ) << endl;
   cout << " rationalsemi( 0.5, 2, 2 ) = " << rationalsemi( 0.5, 2, 2 ) << endl;
   cout << " rationalsemi( y, 2, 2 ) = " << rationalsemi( y, 2, 2 ) << endl;*/
   cout << "--- FINISHED ---" << endl;
 }