Luna: Luna::Bessel< T > Struct Template Reference
Luna::Bessel< T > Struct Template Reference
#include <Special.h>
Public Member Functions
Bessel ()
void rat (const T x, const double *r, const double *s, const int n)
void asp (const double *pn, const double *pd, const double *qn, const double *qd, const double fac)
T J0 (const T &x)
The Bessel function \(J_0(x) \).
T J1 (const T &x)
The Bessel function \(J_1(x) \).
T Y0 (const T &x)
The Bessel function \(Y_0(x) \).
T Y1 (const T &x)
The Bessel function \(Y_1(x) \).
T Jn (const int n, const T &x)
The Bessel function \(J_n(x) \).
T Yn (const int n, const T &x)
The Bessel function \(Y_n(x) \).
Public Attributes
const double xj00
const double xj10
const double xj01
const double xj11
const double twoopi
const double pio4
const double j0r [7]
const double j0s [7]
const double j0pn [5]
const double j0pd [5]
const double j0qn [5]
const double j0qd [5]
const double j1r [7]
const double j1s [7]
const double j1pn [5]
const double j1pd [5]
const double j1qn [5]
const double j1qd [5]
const double y0r [9]
const double y0s [9]
const double y0pn [5]
const double y0pd [5]
const double y0qn [5]
const double y0qd [5]
const double y1r [8]
const double y1s [8]
const double y1pn [5]
const double y1pd [5]
const double y1qn [5]
const double y1qd [5]
double ax
T nump
T denp
T numq
T denq
T xx
T y
T z
Detailed Description
template<typename T>
struct Luna::Bessel< T >
Definition at line 174 of file Special.h.
Constructor & Destructor Documentation
Bessel()
template<typename T> Luna::Bessel< T >::Bessel () inline
Definition at line 241 of file Special.h.
                : xj00( 5.783185962946785 ),
                  xj10( 3.047126234366209e1 ),
                  xj01( 1.468197064212389e1 ),
                  xj11( 4.921845632169460e1 ),
                  twoopi( 0.6366197723675813 ),
                  pio4( 0.7853981633974483 )
       {
       }
Member Function Documentation
asp()
template<typename T> void Luna::Bessel< T >::asp (const double * pn, const double * pd, const double * qn, const double * qd, const double fac) inline
Definition at line 263 of file Special.h.
References Luna::Bessel< T >::ax, Luna::Bessel< T >::pio4, and Luna::Bessel< T >::z.
Referenced by Luna::Bessel< T >::J0(), Luna::Bessel< T >::J1(), Luna::Bessel< T >::Y0(), and Luna::Bessel< T >::Y1().
       {
             z = 8.0 / ax;
             y = z * z;
             xx = ax - fac * pio4;
             nump = pn[ 4 ];
             denp = pd[ 4 ];
             numq = qn[ 4 ];
             denq = qd[ 4 ];
             for ( int i = 3; i >= 0; i-- )
         {
                 nump = nump * y + pn[ i ];
                 denp = denp * y + pd[ i ];
                 numq = numq * y + qn[ i ];
                 denq = denq * y + qd[ i ];
             }
         }
J0()
template<typename T> T Luna::Bessel< T >::J0 (const T & x) inline
The Bessel function \(J_0(x) \).
Parameters
x The arguement of the function
Returns
The Bessel function of the first kind \(J_0(x) \)
Definition at line 285 of file Special.h.
References Luna::Bessel< T >::asp(), Luna::Bessel< T >::denp, Luna::Bessel< T >::denq, Luna::Bessel< T >::rat(), and Luna::Bessel< T >::xj00.
Referenced by Luna::Bessel< T >::Jn(), and Luna::Bessel< T >::Y0().
       {
             if ( ( ax = abs( std::real(x) ) ) < 8.0 ) {
                 rat( x, j0r, j0s, 6 );
                 return nump * ( y - xj00 ) * ( y - xj10 ) / denp;
             } else {
                 asp( j0pn, j0pd, j0qn, j0qd, 1. );
                 return sqrt( twoopi / ax ) * ( cos( xx ) * nump / denp - z * sin( xx )
                  * numq / denq );
             }
         }
J1()
template<typename T> T Luna::Bessel< T >::J1 (const T & x) inline
The Bessel function \(J_1(x) \).
Parameters
x The arguement of the function
Returns
The Bessel function of the first kind \(J_1(x) \)
Definition at line 300 of file Special.h.
References Luna::Bessel< T >::asp(), Luna::Bessel< T >::denp, Luna::Bessel< T >::denq, Luna::Bessel< T >::rat(), and Luna::Bessel< T >::xj01.
Referenced by Luna::Bessel< T >::Jn(), and Luna::Bessel< T >::Y1().
{
             if ( ( ax = abs( std::real(x) ) ) < 8.0 ) {
                 rat( x, j1r, j1s, 6 );
                 return x * nump * ( y - xj01 ) * ( y - xj11 ) / denp;
             } else {
                 asp( j1pn, j1pd, j1qn, j1qd, 3. );
                 T ans = sqrt( twoopi / ax ) * ( cos( xx ) * nump / denp
                        - z * sin( xx ) * numq / denq );
                 return std::real( x ) > 0.0 ? ans : -ans;
             }
         }
Jn()
template<typename T> T Luna::Bessel< T >::Jn (const int n, const T & x) inline
The Bessel function \(J_n(x) \).
Parameters
n The Bessel function number (integer)
x The arguement of the function
Returns
The Bessel function of the first kind \(J_n(x) \)
Definition at line 348 of file Special.h.
References Luna::Bessel< T >::ax, Heat_plot::int, Luna::Bessel< T >::J0(), Luna::Bessel< T >::J1(), and Heat_plot::x.
       {
         const double ACC = 160.0;
         const int IEXP = std::numeric_limits<T>::max_exponent / 2;
         bool jsum;
         int j , k, m;
         T bj , bjm, bjp, dum, sum, tox, ans;
         double ax;
         if (n==0) return J0(x);
         if (n==1) return J1(x);
         // ax=abs(x);
         ax = abs( std::real( x ) );
         if ( ax * ax <= 8.0 * std::numeric_limits<double>::min() ) return 0.0;
         else if ( ax > double( n ) ) {
             //tox=2.0/ax;
             //bjm=J0(ax);
             //bj=J1(ax);
           tox = 2.0 / x;
           bjm = J0( x );
           bj = J1( x );
             for ( j = 1; j < n; j++ ) {
                 bjp = 1. * j * tox * bj - bjm;
                 bjm = bj;
                 bj = bjp;
             }
             ans = bj;
         } else {
             //tox=2.0/ax;
           tox = 2.0 / x;
             m = 2 * ( ( n + int( sqrt( ACC * n ) ) ) / 2 );
             jsum=false;
             bjp=ans=sum=0.0;
             bj=1.0;
             for ( j = m; j > 0; j-- ) {
                 bjm = 1. * j * tox * bj - bjp;
                 bjp = bj;
                 bj = bjm;
                 dum.real( frexp( std::real( bj ), &k ) );
                 if (k > IEXP) {
                     bj.real( ldexp( std::real( bj ), -IEXP ) );
                     bjp.real( ldexp( std::real( bjp ), -IEXP ) );
                     ans.real( ldexp( std::real( ans ), -IEXP ) );
                     sum.real( ldexp( std::real( sum ), -IEXP ) );
                 }
             dum.imag( frexp( std::imag( bj ), &k ) );
                 if (k > IEXP) {
                     bj.imag( ldexp( std::imag( bj ), -IEXP ) );
                     bjp.imag( ldexp( std::imag( bjp ), -IEXP ) );
                     ans.imag( ldexp( std::imag( ans ), -IEXP ) );
                     sum.imag( ldexp( std::imag( sum ), -IEXP ) );
                 }
                 if ( jsum ) sum += bj;
                 jsum =! jsum;
                 if (j == n) ans = bjp;
             }
             sum = 2.0 * sum - bj;
             ans /= sum;
         }
         return std::real( x ) < 0.0 && (n & 1) ? -ans : ans;
       }
rat()
template<typename T> void Luna::Bessel< T >::rat (const T x, const double * r, const double * s, const int n) inline
Definition at line 250 of file Special.h.
References Heat_plot::x, and Luna::Bessel< T >::y.
Referenced by Luna::Bessel< T >::J0(), Luna::Bessel< T >::J1(), Luna::Bessel< T >::Y0(), and Luna::Bessel< T >::Y1().
       {
             y = x * x;
             z = 64.0 - y;
             nump = r[ n ];
             denp = s[ n ];
             for ( int i = n-1; i >= 0; i-- )
         {
                 nump = nump * z + r[ i ];
                 denp = denp * y + s[ i ];
             }
         }
Y0()
template<typename T> T Luna::Bessel< T >::Y0 (const T & x) inline
The Bessel function \(Y_0(x) \).
Parameters
x The arguement of the function
Returns
The Bessel function of the second kind \(Y_0(x) \)
Definition at line 315 of file Special.h.
References Luna::Bessel< T >::asp(), Luna::Bessel< T >::denq, Luna::Bessel< T >::J0(), and Luna::Bessel< T >::rat().
Referenced by Luna::Bessel< T >::Yn().
{
             if ( std::real( x ) < 8.0) {
                 T j0x = J0( x );
                 rat( x, y0r, y0s, 8 );
                 return nump / denp + twoopi * j0x * log( x );
             } else {
                 ax = std::real( x );
                 asp( y0pn, y0pd, y0qn, y0qd, 1. );
                 return sqrt( twoopi / x ) * ( sin( xx ) * nump / denp
                  + z * cos( xx ) * numq / denq );
             }
         }
Y1()
template<typename T> T Luna::Bessel< T >::Y1 (const T & x) inline
The Bessel function \(Y_1(x) \).
Parameters
x The arguement of the function
Returns
The Bessel function of the second kind \(Y_1(x) \)
Definition at line 331 of file Special.h.
References Luna::Bessel< T >::asp(), Luna::Bessel< T >::denq, Luna::Bessel< T >::J1(), Luna::Bessel< T >::rat(), and Heat_plot::x.
Referenced by Luna::Bessel< T >::Yn().
{
             if ( std::real( x ) < 8.0 ) {
                 T j1x = J1( x );
                 rat( x, y1r, y1s, 7 );
                 return x * nump / denp + twoopi * ( j1x * log( x ) - 1.0 / x );
             } else {
                 ax = std::real( x );
                 asp( y1pn, y1pd, y1qn, y1qd, 3. );
                 return sqrt( twoopi / x ) * ( sin( xx ) * nump / denp
                  + z * cos( xx ) * numq / denq );
             }
         }
Yn()
template<typename T> T Luna::Bessel< T >::Yn (const int n, const T & x) inline
The Bessel function \(Y_n(x) \).
Parameters
n The Bessel function number (integer)
x The arguement of the function
Returns
The Bessel function of the second kind \(Y_n(x) \)
Definition at line 414 of file Special.h.
References Heat_plot::x, Luna::Bessel< T >::Y0(), and Luna::Bessel< T >::Y1().
Referenced by main().
       {
         int j;
         T by, bym, byp, tox;
         if ( n == 0 ) return Y0( x );
         if ( n == 1 ) return Y1( x );
         tox = 2.0 / x;
         by = Y1( x );
         bym = Y0( x );
         for ( j = 1; j < n; j++ ) {
             byp =1. * j * tox * by - bym;
             bym = by;
             by = byp;
         }
         return by;
       }
Member Data Documentation
ax
template<typename T> double Luna::Bessel< T >::ax
Definition at line 238 of file Special.h.
Referenced by Luna::Bessel< T >::asp(), and Luna::Bessel< T >::Jn().
denp
template<typename T> T Luna::Bessel< T >::denp
Definition at line 239 of file Special.h.
Referenced by Luna::Bessel< T >::J0(), and Luna::Bessel< T >::J1().
denq
template<typename T> T Luna::Bessel< T >::denq
Definition at line 239 of file Special.h.
Referenced by Luna::Bessel< T >::J0(), Luna::Bessel< T >::J1(), Luna::Bessel< T >::Y0(), and Luna::Bessel< T >::Y1().
j0pd
template<typename T> const double Luna::Bessel< T >::j0pd[5]
Initial value:
={1.0,1.040797262528109,2.588070904043728e-1,
        1.529954477721284e-2,1.168931211650012e-4}
Definition at line 184 of file Special.h.
j0pn
template<typename T> const double Luna::Bessel< T >::j0pn[5]
Initial value:
={9.999999999999999e-1,1.039698629715637,
        2.576910172633398e-1,1.504152485749669e-2,1.052598413585270e-4}
Definition at line 182 of file Special.h.
j0qd
template<typename T> const double Luna::Bessel< T >::j0qd[5]
Initial value:
={1.0,1.237980436358390,3.838793938147116e-1,
        3.100323481550864e-2,4.165515825072393e-4}
Definition at line 188 of file Special.h.
j0qn
template<typename T> const double Luna::Bessel< T >::j0qn[5]
Initial value:
={-1.562499999999992e-2,-1.920039317065641e-2,
        -5.827951791963418e-3,-4.372674978482726e-4,-3.895839560412374e-6}
Definition at line 186 of file Special.h.
j0r
template<typename T> const double Luna::Bessel< T >::j0r[7]
Initial value:
={1.682397144220462e-4,2.058861258868952e-5,
        5.288947320067750e-7,5.557173907680151e-9,2.865540042042604e-11,
        7.398972674152181e-14,7.925088479679688e-17}
Definition at line 176 of file Special.h.
j0s
template<typename T> const double Luna::Bessel< T >::j0s[7]
Initial value:
={1.0,1.019685405805929e-2,5.130296867064666e-5,
        1.659702063950243e-7,3.728997574317067e-10,
        5.709292619977798e-13,4.932979170744996e-16}
Definition at line 179 of file Special.h.
j1pd
template<typename T> const double Luna::Bessel< T >::j1pd[5]
Initial value:
={1.0,1.012208056357845,2.408580305488938e-1,
        1.309511056184273e-2,7.746422941504713e-5}
Definition at line 199 of file Special.h.
j1pn
template<typename T> const double Luna::Bessel< T >::j1pn[5]
Initial value:
={1.0,1.014039111045313,2.426762348629863e-1,
        1.350308200342000e-2,9.516522033988099e-5}
Definition at line 197 of file Special.h.
j1qd
template<typename T> const double Luna::Bessel< T >::j1qd[5]
Initial value:
={1.0,1.210119370463693,3.626494789275638e-1,
        2.761695824829316e-2,3.240517192670181e-4}
Definition at line 203 of file Special.h.
j1qn
template<typename T> const double Luna::Bessel< T >::j1qn[5]
Initial value:
={4.687499999999991e-2,5.652407388406023e-2,
        1.676531273460512e-2,1.231216817715814e-3,1.178364381441801e-5}
Definition at line 201 of file Special.h.
j1r
template<typename T> const double Luna::Bessel< T >::j1r[7]
Initial value:
={7.309637831891357e-5,3.551248884746503e-6,
        5.820673901730427e-8,4.500650342170622e-10,1.831596352149641e-12,
        3.891583573305035e-15,3.524978592527982e-18}
Definition at line 191 of file Special.h.
j1s
template<typename T> const double Luna::Bessel< T >::j1s[7]
Initial value:
={1.0,9.398354768446072e-3,4.328946737100230e-5,
        1.271526296341915e-7,2.566305357932989e-10,
        3.477378203574266e-13,2.593535427519985e-16}
Definition at line 194 of file Special.h.
nump
template<typename T> T Luna::Bessel< T >::nump
Definition at line 239 of file Special.h.
numq
template<typename T> T Luna::Bessel< T >::numq
Definition at line 239 of file Special.h.
pio4
template<typename T> const double Luna::Bessel< T >::pio4
Definition at line 175 of file Special.h.
Referenced by Luna::Bessel< T >::asp().
twoopi
template<typename T> const double Luna::Bessel< T >::twoopi
Definition at line 175 of file Special.h.
xj00
template<typename T> const double Luna::Bessel< T >::xj00
Definition at line 175 of file Special.h.
Referenced by Luna::Bessel< T >::J0().
xj01
template<typename T> const double Luna::Bessel< T >::xj01
Definition at line 175 of file Special.h.
Referenced by Luna::Bessel< T >::J1().
xj10
template<typename T> const double Luna::Bessel< T >::xj10
Definition at line 175 of file Special.h.
xj11
template<typename T> const double Luna::Bessel< T >::xj11
Definition at line 175 of file Special.h.
xx
template<typename T> T Luna::Bessel< T >::xx
Definition at line 239 of file Special.h.
y
template<typename T> T Luna::Bessel< T >::y
Definition at line 239 of file Special.h.
Referenced by Luna::Bessel< T >::rat().
y0pd
template<typename T> const double Luna::Bessel< T >::y0pd[5]
Initial value:
={1.0,1.040797262528109,2.588070904043728e-1,
        1.529954477721284e-2,1.168931211650012e-4}
Definition at line 215 of file Special.h.
y0pn
template<typename T> const double Luna::Bessel< T >::y0pn[5]
Initial value:
={9.999999999999999e-1,1.039698629715637,
        2.576910172633398e-1,1.504152485749669e-2,1.052598413585270e-4}
Definition at line 213 of file Special.h.
y0qd
template<typename T> const double Luna::Bessel< T >::y0qd[5]
Initial value:
={1.0,1.237980436358390,3.838793938147116e-1,
        3.100323481550864e-2,4.165515825072393e-4}
Definition at line 219 of file Special.h.
y0qn
template<typename T> const double Luna::Bessel< T >::y0qn[5]
Initial value:
={-1.562499999999992e-2,-1.920039317065641e-2,
        -5.827951791963418e-3,-4.372674978482726e-4,-3.895839560412374e-6}
Definition at line 217 of file Special.h.
y0r
template<typename T> const double Luna::Bessel< T >::y0r[9]
Initial value:
={-7.653778457189104e-3,-5.854760129990403e-2,
        3.720671300654721e-4,3.313722284628089e-5,4.247761237036536e-8,
        -4.134562661019613e-9,-3.382190331837473e-11,
        -1.017764126587862e-13,-1.107646382675456e-16}
Definition at line 206 of file Special.h.
y0s
template<typename T> const double Luna::Bessel< T >::y0s[9]
Initial value:
={1.0,1.125494540257841e-2,6.427210537081400e-5,
        2.462520624294959e-7,7.029372432344291e-10,1.560784108184928e-12,
        2.702374957564761e-15,3.468496737915257e-18,2.716600180811817e-21}
Definition at line 210 of file Special.h.
y1pd
template<typename T> const double Luna::Bessel< T >::y1pd[5]
Initial value:
={1.0,1.012208056357845,2.408580305488938e-1,
        1.309511056184273e-2,7.746422941504713e-5}
Definition at line 231 of file Special.h.
y1pn
template<typename T> const double Luna::Bessel< T >::y1pn[5]
Initial value:
={1.0,1.014039111045313,2.426762348629863e-1,
        1.350308200342000e-2,9.516522033988099e-5}
Definition at line 229 of file Special.h.
y1qd
template<typename T> const double Luna::Bessel< T >::y1qd[5]
Initial value:
={1.0,1.210119370463693,3.626494789275638e-1,
        2.761695824829316e-2,3.240517192670181e-4}
Definition at line 235 of file Special.h.
y1qn
template<typename T> const double Luna::Bessel< T >::y1qn[5]
Initial value:
={4.687499999999991e-2,5.652407388406023e-2,
        1.676531273460512e-2,1.231216817715814e-3,1.178364381441801e-5}
Definition at line 233 of file Special.h.
y1r
template<typename T> const double Luna::Bessel< T >::y1r[8]
Initial value:
={-1.041835425863234e-1,-1.135093963908952e-5,
        2.212118520638132e-4,1.270981874287763e-6,
        -3.982892100836748e-8,-4.820712110115943e-10,
        -1.929392690596969e-12,-2.725259514545605e-15}
Definition at line 222 of file Special.h.
y1s
template<typename T> const double Luna::Bessel< T >::y1s[8]
Initial value:
={1.0,1.186694184425838e-2,7.121205411175519e-5,
        2.847142454085055e-7,8.364240962784899e-10,1.858128283833724e-12,
        3.018846060781846e-15,3.015798735815980e-18}
Definition at line 226 of file Special.h.
z
template<typename T> T Luna::Bessel< T >::z
Definition at line 239 of file Special.h.
Referenced by Luna::Bessel< T >::asp().
The documentation for this struct was generated from the following file:
include/Luna/Special.h